final List idklineslist_he = [
  0,
  'סבתא',
  'אמא',
  'בת',
  'בן',
  'אבא',
  'סבא',
  1,
  'חיי גן עדן של סבתא מורכבים מהר מדי',
  'ביטוי עצמי מורכב של אמא מגיע מוקדם מדי',
  'יצירתיות מורכבת של הבת דוחפת את אחיה',
  'יצירתיות מורכבת של הבן יוצר את המשפחה',
  'ביטוי עצמי של אבא נוגע מרכיב את העולם',
  'ביטוי עצמי של סבא מרכיב את גן עדן',
  2,
  'חייה השקטים של סבתא נקלטים באדמה',
  'חייה השקטים של אמא נקלטים אצלה',
  'חייה השקטים של הבת נקלטים במורשת הנשית',
  'חייו השקטים של הבן כבדים על אחותו',
  'חייו השקטים של אבא מכבידים על העולם',
  'חייו השקטים של סבא לא נקלטים בגן עדן',
  3,
  'הקושי בהתחלה הפשוטה של סבתא קורה מהר מדי',
  'הקושי בהתחלה הפשוטה של אמא מקרקע אותה',
  'הקושי של הבת לשתוק בהתחלה תומך באמא שלה',
  'הקושי של הבן לשתוק בהתחלה מכביד על אחותו',
  'הקושי הפשוט בהתחלה של אבא מקל על העולם',
  'הקושי הפשוט בהתחלה של סבא מכביד על כל הדורות',
  4,
  'שאיפתה של סבתא מתקרקעת את תשובתה',
  'אמא נושפת את תשובתה מוקדם מדי',
  'התשובה השותקת של הבת תומכת באמא שלה',
  'תשובתו השותקת של הבן מכבידה על אחותו',
  'שאיפתו של אבא להשיב מכבידה על העולם',
  'נשיפתו של סבא משיבה לגן עדן',
  5,
  'ההמתנה המורכבת של סבתא דוחפת את התור מהר מדי',
  'ההמתנה המורכבת של אמא דוחפת אותה יותר מדי בתור',
  'ההמתנה הפשוטה של הבת דוחפת את אחיה',
  'ההמתנה הפשוטה של הבן מכבידה על אחותו',
  'סבלנותו הפשוטה של אבא חוצה אוקיאנוסים',
  'סבלנותו הפשוטה של סבא נדחית על ידי גן עדן',
  6,
  'סבתא שואפת חיכוך ומתקרקעת במים',
  'נשיפתה של אמא גורמת לה לחיכוך מהיר מדי',
  'בת שואפת חיכוך כדי לתמוך באמא שלה',
  'בן נושף חיכוך החוצה מן המשפחה',
  'חיכוכים מורכבים של אבא יוצרים את העולם',
  'חיכוכים מורכבים של סבא יוצרים את גן עדן',
  7,
  'שאיפת התפקיד של סבתא נקלט במים',
  'נשיפת התפקיד של אמא נדחה במים',
  'התפקיד השותק של הבת תומך באמא שלה',
  'התפקיד השותק של הבן כבד על אחותו',
  'התפקיד השותק של אבא כבד על העולם',
  'תפקידו השותק של סבא גורם לגן עדן להיות גיהנום',
  8,
  'התרומה השותקת של סבתא נקלטת בקרקע',
  'התרומה השותקת של אמא נקלטת על ידה',
  'התרומה השותקת של הבת תומכת בגוף הנשי',
  'התרומה השותקת של הבן כבדה על אחותו',
  'התרומה הפשוטה של אבא נודעת בכל העולם',
  'התרומה הפשוטה של סבא מכבידה על המורשת שלו',
  9,
  'grandmother complex focus has no ground at all',
  'mother complex focus is not grounded ',
  'daughter simple focus is to run from her mothers',
  'son simple focus burdens his family',
  'father complex focus reaches globally',
  'grandfather complex focus is known in heaven',
  10,
  'grandmother complex behavior is a regret in the lake',
  'mother complex behavior is not shining',
  'daughter inhales her behavior to fit her role',
  'son exhales his behavior and is rewarded in the family',
  'father complex behavior saves the world',
  'grandfather complex behavior is a role model in heaven',
  11,
  'grandmother complex idea shines too early',
  'mother complex idea shines too fast',
  'daughter simple idea is to leave her mother',
  'son simple idea is a burden to his sister',
  'father idea is silenced in the world',
  'grandfather idea is silenced in heaven',
  12,
  'grandmother silent caution is deeply rooted',
  'mother silent caution protects her',
  'daughter breath sometimes cautions her mothers',
  'son breath moves cautiously to his fathers ',
  'father breath cautions strangers',
  'grandfather breath cautions heaven',
  13,
  'grandmother simple secret is revealed too easily',
  'mother simple secret is properly kept hidden',
  'daughter complex secret is mistakenly revealed to her brother',
  'son complex secret is properly told to father',
  'father complex secret is exposed to everyone',
  'grandfather complex secret reaches god',
  14,
  'grandmother wisdom is blackened',
  'mother wisdom is shadowed',
  'daughter wisdom cuts the feminine roots',
  'son is inspired to be like grandfather and oppose his father',
  'father breath heavily and suffer',
  'grandfather is happy his grandson carries his wealth',
  15,
  'grandmother silent modesty is her epitaph of love',
  'mother silent modesty grounds love',
  'daughter simple modesty pushes her brother',
  'son simple modesty burdens his sister',
  'father silent modesty is not loved in the world',
  'grandfather silent modesty is not accepted in heaven ',
  16,
  'grandmother silent skills are grounded for lifetimes',
  'mother silent skills grounds her',
  'daughter breathe skills from her mothers',
  'son breathe skills from his father',
  'father silent skills are not welcome in the world',
  'grandfather silent skills burdens his entire legacy',
  17,
  'grandmother light opinion do not serve her',
  'mother simple opinion grounds her',
  'daughter sound opinion grounds her mothers',
  'son sound opinion follows his father',
  'father simple opinion is followed worldwide',
  'grandfather simple opinion is hell for his legacy',
  18,
  'grandmother correctly inhales earth',
  'mother incorrectly exhales too soon',
  'daughter simple correction is too light',
  'son simple correction is too heavy',
  'father breath correction is rejected worldwide',
  'grandfather breath correction is welcome on heaven',
  19,
  'grandmother complex needs do not approach her roots',
  'mother complex needs do not yield to her mother',
  'daughter silent needs repent for her mothers',
  'son silent needs are a burden to his sister',
  'father silent needs are a burden to his son',
  'grandfather silent needs are a burden to his son',
  20,
  'grandmother is silent now all the way to the grave',
  'mother is silent now with her mother',
  'daughter contemplates the female silence',
  'son silent contemplation is not welcome by his sister',
  'father complex contemplation is worldly known',
  'grandfather complex contemplates now in heaven',
  21,
  'grandmother simple control escapes too much',
  'mother simple control grounds her',
  'daughter controlled breath of grounds her mother',
  'son controlled breath is aspired by father',
  'father controlled breath is a burden to the world',
  'grandfather controlled breath moves in heaven',
  22,
  'grandmother simple grace escapes her',
  'mother simple grace grounds her',
  'daughter simple grace pushes her brother',
  'son simple grace is heavy on his sister',
  'father gracefully inhale the burden of the world',
  'grandfather exhale grace into heaven',
  23,
  'grandmother silent knowing speaks for the earth',
  'mother silent knowing speaks for her',
  'daughter silent knowing supports on her mothers',
  'son silent knowing is heavy on his sister',
  'father knows to inhale the burden in the world',
  'grandfather knows how to exhale up to heaven',
  24,
  'grandmother simple rational thought is too light',
  'mother simple rational thought is considered',
  'daughter silent rational thought supports her mother',
  'son silent rational thought is heavy on his sister',
  'father silent rational thought is a burden in the world',
  'grandfather silent rational thought falls from heaven',
  25,
  'grandmother simple innocence does not ground love',
  'mother simple innocence grounds love',
  'daughter innocent breath grounds her mothers love',
  'son innocent breath aspires family love',
  'father innocence complex aspires worldly love',
  'grandfather innocence complex aspires heavenly love',
  26,
  'grandmother complex trick is exposed too much',
  'mother complex trick is exposed to her daughter',
  'daughter simple trick is to escape her mother',
  'son simple trick is to block his sister',
  'father inhalation trick is not welcome in the world',
  'grandfather exhalation trick is heavenly ',
  27,
  'grandmother simple care is too positive',
  'mother simple care grounds her',
  'daughter silent care grounds her mother',
  'son silent care is heavy on his sister',
  'father inhales worldly care too heavily',
  'grandfather exhales care up to heaven',
  28,
  'grandmother inhale grounded risk',
  'mother premature risk escapes her',
  'daughter complex risk pushes her brother',
  'son complex risk aspires the family',
  'father simple risk is success in the world ',
  'grandfather simple risk is a burden to his son',
  29,
  'grandmother inhalation is persevered in the deep water',
  'mother exhalation do not persevere in mid water',
  'daughter persevere in silent high water',
  'son silent perseverance is a heavy on the family',
  'father simple swim perseveres through dark clouds',
  'grandfather simple swim do not persevere in heaven',
  30,
  'grandmother simple fire is quickly extinguished',
  'mother simple fire is long lasting',
  'daughter complex fire burns her brother',
  'son complex fire lightens the family',
  'father inhales fire and is burnt in the world',
  'grandfather exhaled fire enlightens heavenly bonfire',
  31,
  'grandmother leads silently even in the grave',
  'mother leads silently during life',
  'daughter influences her complex brother too lightly',
  'son leads the complex of the family',
  'father simple influence leads the world',
  'grandfather simple influence is heavy on his son',
  32,
  'grandmother inhales failure during wind',
  'mother exhales failure too early during wind',
  'daughter complex failure escapes the wind of her mothers',
  'son complex failure moves during thunder',
  'father silent thundering failure is ruined in the world',
  'grandfather silent failure is ruining his son',
  33,
  'grandmother silent retreat deep in the mountain',
  'mother silent retreat with her mother',
  'daughter complex retreat away from the mountain',
  'son timely advances to his fathers',
  'father timing is remembered throughout the world',
  'grandfather timing is heavenly memory',
  34,
  'grandmother complex power is blinding',
  'mother complex power is too bright',
  'daughter complex power is outshined by brother',
  'son complex power shines in the family',
  'father silent power is heavy on the world',
  'grandfather silent power is hidden from heaven',
  35,
  'grandmother silent progress does not change even in the grave',
  'mother silent progress does not change life',
  'daughter inhale progress in changing earth',
  'son exhales progress to change his family',
  'father inhales worldly changes heavily',
  'grandfather exhales change into heaven',
  36,
  'grandmother simple crisis is too easy in the firebase',
  'mother simple crisis allows the fire to burn on the ground',
  'daughter simple crisis extinguishes the fire',
  'son simple crisis is heavy on the family',
  'father silent world crisis is heavy on the sky',
  'grandfather silent heavenly crisis rejects liberation',
  37,
  'grandmother simple family escapes her',
  'mother simple family protects her',
  'daughter escapes the simple family',
  'son is stuck in the simple family',
  'father complex family shines in the world',
  'grandfather complex family shines in heaven',
  38,
  'grandmother complex fight misses the picnic on the lake',
  'mother all too often fights her daughter in the lake',
  'daughter inhales the fight to balance her mothers on the lake',
  'son exhales the firefight for family balance',
  'father inhales world firefight and is burnt',
  'grandfather exhales to heaven any firefight',
  39,
  'grandmother provokes silence deep in the mountain',
  'mother provokes grounding silence',
  'daughter simple provocation escapes the mountain',
  'son simple provocation opposes his sister escape',
  'father simple provocation is a bridge over troubled ocean',
  'grandfather simple provocation floods the world',
  40,
  'grandmother inhales family work as hard as ice',
  'mother exhales family work in premature deliverance',
  'daughter inhales family work to repent for her mother',
  'son exhales family work to shine for his fathers',
  'father work in the world is rejected',
  'grandfather work is banished from heaven',
  41,
  'grandmother fantasy time arrives too soon',
  'mother fantasy time arrives only too short',
  'daughter silent fantasy grounds her mothers',
  'son silent fantasy burdens his sister',
  'father inhale burden of world fantasy',
  'grandfather exhale his fantasy up to heaven',
  42,
  'grandmother simple growth is cut prematurely',
  'mother simple growth is safe and sound',
  'daughter silent growth grounds her mother',
  'son silent growth burdens his sister',
  'father complex growth enlightens the world',
  'grandfather complex growth penetrates heaven',
  43,
  'grandmother complex insight is too light',
  'mother complex insight is too early',
  'daughter complex insight pushes her brother',
  'son complex insight inspires the family',
  'father simple insight crosses the world',
  'grandfather simple insight is a heavy on his son',
  44,
  'grandmother is alert to inhale wind slowly',
  'mother is alert and exhales wind too fast ',
  'daughter complex alert escapes the wind',
  'son time alert aspires his family',
  'father time alert crosses the world  ',
  'grandfather time alert goes beyond the universe',
  45,
  'grandmother is the silent owner of earth',
  'mother is the silent owner of her body',
  'daughter inhales her mothers property',
  'son exhales shines the family ownership',
  'father simple ownership gathers the world',
  'grandfather simple ownership cuts through his sons',
  46,
  'grandmother determined inhalation balances the wind',
  'mother determined exhalation blows the wind too early',
  'daughter simple determination pushes her brother',
  'son simple determination is heavy on his sister',
  'father silent determination is a world burden',
  'grandfather silent determination is rejected from heaven',
  47,
  'grandmother oppresses inhalation in deep water',
  'mother oppressed exhalation escapes the water too early',
  'daughter oppressed inhalation on the water surface',
  'son oppressed exhalation is exalted in the family',
  'father simple realization polishes the world',
  'grandfather simple realization is not welcome in heaven',
  48,
  'grandmother inhales solutions deep into the wind',
  'mother exhales solutions to early into the wind',
  'daughter simple solution in blown by the wind',
  'son simple solution is is dropped on his sister',
  'father simple solution rides through the ocean',
  'grandfather simple solution is banished from heaven',
  49,
  'grandmother simple principle is a revolution too soon',
  'mother simple principle is a welcomed revolution',
  'daughter complex principle pushes her brother revolution',
  'son complex principle inspires the family revolution',
  'father simple principle is reflected in world revolution',
  'grandfather simple principle is a burden to his son',
  50,
  'grandmother value is to inhale the wind to ground',
  'mother value is to exhale the wind too early',
  'daughter complex value pushes her brother',
  'son complex value fires through the family',
  'father inhales world value too heavily',
  'grandfather exhales heavenly value',
  51,
  'grandmother simple shock roars too easily',
  'mother simple shock roars from the ground',
  'daughter inhales shock of mothers roar',
  'son exhales shock inspire family roar',
  'father silent shock depresses the world',
  'grandfather silent shock is banished from heaven',
  52,
  'grandmother silent meditation serves lifetimes',
  'mother silent meditation serves her life',
  'daughter simple meditation is to escape the mountain',
  'son simple meditation is a burden to his sister',
  'father inhales mediation to depress the world',
  'grandfather exhales meditation to exalt heaven',
  53,
  'grandmother begins silence deep in the mountain',
  'mother begins silence on the ground ',
  'daughter simple start pushes her brother',
  'son simple start is heavy on his sister',
  'father complex development begins in the world',
  'grandfather complex development begins in heaven',
  54,
  'grandmother complex ambition drives all too fast',
  'mother complex ambition drives her too early',
  'daughter inhales ambition to balance her mothers',
  'son exhales ambition to inspire his family',
  'father silent ambition is heavy on the world',
  'grandfather silent ambition is rejected from heaven',
  55,
  'grandmother simple spirit fires too fast',
  'mother simple spirit fires the ground',
  'daughter complex spirit pushes her brother',
  'son complex spirit inspires the family',
  'father silent spirit is heavy on the world',
  'grandfather silent spirit is rejected from heaven',
  56,
  'grandmother silently wanders the mountain',
  'mother silently wanders on the ground',
  'daughter complex belief pushes her brother',
  'son complex belief inspires the family',
  'father inhales world belief too seriously',
  'grandfather exhales the story of heaven',
  57,
  'grandmother inhales the wind to the ground',
  'mother exhales the wind too soon',
  'daughter exhales the wind to push her brother',
  'son inhales the wind to depress his sister',
  'father is gentle through the wind of the world',
  'grandfather gentle blow reaches heaven',
  58,
  'grandmother joy complex is brushed easily',
  'mother joy complex does not serve her',
  'daughter inhales joy to cover her mothers',
  'son exhales joy through family',
  'father simple joy keeps the world alive',
  'grandfather simple joy is rejected from heaven',
  59,
  'grandmother inhales sexuality through deep water',
  'mother exhales sexuality to disperse water early',
  'daughter silent sexuality is taken from mothers',
  'son silent sexuality is heavy on his sister',
  'father complex sexuality spreads through the world',
  'grandfather complex sexuality spreads through heaven',
  60,
  'grandmother complex limitation is too strong',
  'mother complex limitation is too early',
  'daughter silent limitation accepts her mother',
  'son silent limitation burdens his sister',
  'father simple acceptance shines in the world',
  'grandfather simple acceptance is rejected by heaven',
  61,
  'grandmother complex mystery is exposed too much',
  'mother complex mystery is exposed too early',
  'daughter silent truth grounds her mother',
  'son silent truth burdens his sister',
  'father complex mystery is truth in the world',
  'grandfather complex mystery is truth in heaven',
  62,
  'grandmother silent detail is for lifetimes',
  'mother silent detail serves her',
  'daughter complex detail pushes her brother',
  'son complex detail shines through the family',
  'father silent detail is a world burden',
  'grandfather silent detail is rejected from heaven',
  63,
  'grandmother simple doubt is all too early',
  'mother simple doubt serves her well',
  'daughter simple doubt pushes her brother',
  'son simple doubt blocks his sister',
  'father simple doubt inspires the world',
  'grandfather simple doubt in heaven rejects him afterlife',
  64,
  'grandmother inhales confusion into deep water',
  'mother exhales confusion to escape the water early',
  'daughter inhales confusion to ground her mother',
  'son exhales confusion to shine through the family',
  'father inhales a confused world too seriously',
  'grandfather exhales heaven before all is completed',
];