final List hexlinesList = [
  0,
  'grandmother',
  'mother',
  'daughter',
  'son',
  'father',
  'grandfather',
  1,
  'grandmother stuck in hell',
  'mother life is hell',
  'daughter complicated life',
  'son complicated life',
  'father is one foot from heaven',
  'grandfather died and is up in heaven',
  2,
  'grandmother remains silent',
  'mother tries to remain silent',
  'daughter suffers from silence',
  'son suffers from silence',
  'father is tortured from silence',
  'grandfather is silently falling from the top',
  3,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  4,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  5,
  'grandmother cannot wait in the Q',
  'mother waits impatiently in the Q',
  'daughter waits all life to blossom',
  'son does not wait and regrets',
  'father patience crosses oceans',
  'grandfather waits angrily',
  6,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  7,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  8,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  9,
  'grandmother focus is too bright',
  'mother focus is too light',
  'daughter focus runs away',
  'son focus on mothers and suffer with sister ',
  'father focus is tremendous and looks up to his father',
  'grandfather focus is in ultimate liberation',
  10,
  'grandmother good behavior is never seen',
  'mother good behavior is rarely appreciated',
  'daughter negative behavior fits her role',
  'son behavior is rewarded',
  'father behavior is known world wide',
  'grandfather behavior remembered for generations',
  11,
  'grandmother idea brings war',
  'mother idea brings no resolution',
  'daughter idea is to leave the family',
  'son is not peaceful with his ideas',
  'father is not the ideal father',
  'grandfather forgets all his memory',
  12,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  13,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  14,
  'grandmother wisdom is blackened',
  'mother wisdom is shadowed',
  'daughter wisdom cuts the feminine roots',
  'son is inspired to be like granfather and oppose his father',
  'father breath heavily and suffer',
  'grandfather is happy his grandson carries his wealth',
  15,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  16,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  17,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  18,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  19,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  20,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  21,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  22,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  23,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  24,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  25,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  26,
  'grandmother sells and loses everything',
  'mother sells loses most of it',
  'daughter sells but forget to collect',
  'son refuses to sell and sinks down',
  'father does not sell and is held responsible',
  'grandfather sells happily and cover for the entire family',
  27,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  28,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  29,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  30,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  31,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  32,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  33,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  34,
  'grandmother power is completely hidden',
  'mother power is considered negative',
  'daughter power is too light',
  'son power is stable and growing',
  'father power suffers the downfall',
  'grandfather power is disolved and not respected',
  35,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  36,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  37,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  38,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  39,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  40,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  41,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  42,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  43,
  'grandmother complex wisdom is never shown',
  'mother complex wisdom is seldom shown',
  'daughter cannot breakthrough the spell',
  'son is inspired to be wise like father',
  'father is simple and happy ',
  'grandfather simple wisdom not lived',
  44,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  45,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  46,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  47,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  48,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  49,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  50,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  51,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  52,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  53,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  54,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  55,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  56,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  57,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  58,
  'grandmother joy is regreted',
  'mother joy is hidden',
  'daughter lack of joy is forgiven',
  'son joy is satisfying',
  'father joy keeps people alive',
  'grandfather joy is a disease',
  59,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  60,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  61,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  62,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  63,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
  64,
  'grandmother joy is regreted XXX NOT DONE',
  'mother joy is hidden XXX NOT DONE',
  'daughter lack of joy is forgiven XXX NOT DONE',
  'son joy is satisfying XXX NOT DONE',
  'father joy keeps people alive XXX NOT DONE',
  'grandfather joy is a disease XXX NOT DONE',
];