import 'dart:core';

final List<String> hdchannelsentenceList = [
  '1.8',
  'Breath is Inspiring',
  '2.14',
  'silence is Beating',
  '3.60',
  'silence is Mutating',
  '4.63',
  'Breath shall be Logic',
  '5.15',
  'silence shall Flow',
  '6.59',
  'silence of Mating',
  '7.31',
  'Breath shall be an Alpha ',
  '9.52',
  'silence shall Concentrate',
  '10.20',
  'Breaths is Awakening',
  '10.34',
  'silence is Being Explored',
  '10.57',
  'Breath is Surviving',
  '11.56',
  'Breath was Curious',
  '12.22',
  'COMPLEX is Openning',
  '13.33',
  'Breath was Witnessed',
  '16.48',
  'Breath shall be Talented',
  '17.62',
  'Breath shall Organize',
  '18.58',
  'Breath shall Judge',
  '19.49',
  'Breath of Synthesis',
  '20.34',
  'silence is Moving',
  '20.57',
  'Breath is Intuitive',
  '21.45',
  'COMPLEX Money',
  '23.43',
  'Breath is Genius',
  '24.61',
  'Breath is Awareness',
  '25.51',
  'Breath is Initiating',
  '26.44',
  'Breath Transmission',
  '27.50',
  'silence of Preservation',
  '28.38',
  'Breath is Struggling',
  '29.46',
  'silence was Discovered',
  '30.41',
  'Breath was Recognized',
  '32.54',
  'Breath Transformation',
  '34.57',
  'silence is empowering',
  '35.36',
  'COMPLEX was Transitioning',
  '37.40',
  'Breath of Community',
  '39.55',
  'Breath is Moody',
  '42.53',
  'silence was Matured',
  '47.64',
  'Breath was Abstract'
];

final List<String> hdchannelsList = [
  '1.8',
  'self',
  'throat',
  'inspiration',
  'inspiring',
  'breath',
  'creative role model',
  'individual',
  'knowing',
  'none',
  '2.14',
  'self',
  'sacral',
  'beat',
  'beating',
  'silence',
  'keeper of keys',
  'individual',
  'knowing',
  'none',
  '3.60',
  'sacral',
  'root',
  'mutation',
  'mutative',
  'silence',
  'fluctuation',
  'individual',
  'knowing',
  'none',
  '4.63',
  'ajna',
  'head',
  'logic',
  'logical',
  'breath',
  'mental doubt eased',
  'collective',
  'logic',
  'understanding',
  '5.15',
  'sacral',
  'self',
  'rhythm',
  'rhythmic',
  'silence',
  'being in the flow',
  'collective',
  'logic',
  'none',
  '6.59',
  'solar',
  'sacral',
  'mating',
  'mating',
  'silence',
  'reproduction',
  'tribal',
  'defense',
  'none',
  '7.31',
  'self',
  'throat',
  'alpha',
  'alpha',
  'breath',
  'being a leader',
  'collective',
  'logic',
  'none',
  '9.52',
  'sacral',
  'root',
  'concentration',
  'concetrated',
  'silence',
  'determination',
  'collective',
  'logic',
  'none',
  '10.20',
  'self',
  'throat',
  'awakening',
  'awakening',
  'breath',
  'higher principles',
  'individual',
  'integration',
  'none',
  '10.34',
  'self',
  'sacral',
  'exploration',
  'exploring',
  'silence',
  'follow your conviction',
  'individual',
  'centering',
  'none',
  '10.57',
  'self',
  'spleen',
  'perfected form',
  'surviving',
  'breath',
  'survival',
  'individual',
  'integration',
  'none',
  '11.56',
  'ajna',
  'throat',
  'curiosity',
  'curious',
  'breath',
  'seeker',
  'collective',
  'abstract',
  'sensing',
  '12.22',
  'throat',
  'solar',
  'openness',
  'open',
  'complex',
  'social being',
  'individual',
  'knowing',
  'emoting',
  '13.33',
  'self',
  'throat',
  'prodigal',
  'witnessed',
  'breath',
  'being a witness',
  'collective',
  'abstract',
  'none',
  '16.48',
  'throat',
  'spleen',
  'wavelength',
  'talented',
  'breath',
  'talent',
  'collective',
  'logic',
  'taste',
  '17.62',
  'ajna',
  'throat',
  'acceptance',
  'accepting',
  'breath',
  'organizational being',
  'collective',
  'logic',
  'understanding',
  '18.58',
  'spleen',
  'root',
  'judgement',
  'judging',
  'breath',
  'instability',
  'collective',
  'logic',
  'taste',
  '19.49',
  'solar',
  'root',
  'synthesis',
  'sensitive',
  'breath',
  'being sensitive',
  'tribal',
  'ego',
  'needs',
  '20.34',
  'throat',
  'sacral',
  'charisma',
  'moving',
  'silence',
  'move to do',
  'individual',
  'integration',
  'none',
  '20.57',
  'throat',
  'spleen',
  'brainwave',
  'penetrating',
  'breath',
  'penetrating awareness',
  'individual',
  'knowing',
  'intuition',
  '21.45',
  'heart',
  'throat',
  'moneyline',
  'money',
  'complex',
  'materialist',
  'tribal',
  'ego',
  'none',
  '23.43',
  'throat',
  'ajna',
  'structuring',
  'structuring',
  'breath',
  'individual genius or freak',
  'individual',
  'knowing',
  'knowing',
  '24.61',
  'ajna',
  'head',
  'awareness',
  'aware',
  'breath',
  'thinker or stinker',
  'individual',
  'knowing',
  'knowing',
  '25.51',
  'self',
  'heart',
  'initiation',
  'initiating',
  'breath',
  'compete to be first',
  'individual',
  'centering',
  'none',
  '26.44',
  'heart',
  'spleen',
  'surrender',
  'surrendered',
  'breath',
  'transmitter',
  'tribal',
  'ego',
  'instinct',
  '27.50',
  'sacral',
  'spleen',
  'preservation',
  'preserved',
  'silence',
  'custodianship',
  'tribal',
  'defense',
  'none',
  '28.38',
  'spleen',
  'root',
  'struggle',
  'struggling',
  'breath',
  'being stubborn',
  'individual',
  'knowing',
  'intuition',
  '29.46',
  'sacral',
  'self',
  'discovery',
  'discovered',
  'silence',
  'determination of the self',
  'collective',
  'abstract',
  'none',
  '30.41',
  'solar',
  'root',
  'recognition',
  'recognized',
  'breath',
  'focused energy',
  'collective',
  'abstract',
  'feelings',
  '32.54',
  'spleen',
  'root',
  'transformation',
  'tranformed',
  'breath',
  'being driven',
  'tribal',
  'ego',
  'intuition',
  '34.57',
  'sacral',
  'spleen',
  'power',
  'powerful',
  'silence',
  'archetype',
  'individual',
  'integration',
  'none',
  '35.36',
  'throat',
  'solar',
  'transitoriness',
  'transitoriness',
  'complex',
  'a jack of all trades',
  'collective',
  'abstract',
  'feelings',
  '37.40',
  'solar',
  'heart',
  'community',
  'communal',
  'breath',
  'a part that needs the whole',
  'tribal',
  'ego',
  'needs',
  '39.55',
  'solar',
  'root',
  'emoting',
  'emoting',
  'breath',
  'moodiness',
  'individual',
  'knowing',
  'emoting',
  '42.53',
  'sacral',
  'root',
  'maturation',
  'matured',
  'silence',
  'balanced development',
  'collective',
  'abstract',
  'none',
  '47.64',
  'ajna',
  'head',
  'abstract',
  'abstract',
  'breath',
  'mental activity mixed with clarity',
  'collective',
  'abstract',
  'sensing',
];

final List<String> hdchannelsListold = [
  '1.8',
  'self',
  'throat',
  'inspiration',
  'creative role model',
  'individual',
  'knowing',
  'none',
  '2.14',
  'self',
  'sacral',
  'beat',
  'keeper of keys',
  'individual',
  'knowing',
  'none',
  '3.60',
  'sacral',
  'root',
  'mutation',
  'fluctuation',
  'individual',
  'knowing',
  'none',
  '4.63',
  'ajna',
  'head',
  'logic',
  'mental doubt eased',
  'collective',
  'logic',
  'understanding',
  '5.15',
  'sacral',
  'self',
  'rhythm',
  'being in the flow',
  'collective',
  'logic',
  'none',
  '6.59',
  'solar',
  'sacral',
  'mating',
  'reproduction',
  'tribal',
  'defense',
  'none',
  '7.31',
  'self',
  'throat',
  'alpha',
  'being a leader',
  'collective',
  'logic',
  'none',
  '9.52',
  'sacral',
  'root',
  'concentration',
  'determination',
  'collective',
  'logic',
  'none',
  '10.20',
  'self',
  'throat',
  'awakening',
  'higher principles',
  'individual',
  'integration',
  'none',
  '10.34',
  'self',
  'sacral',
  'exploration',
  'follow your conviction',
  'individual',
  'centering',
  'none',
  '10.57',
  'self',
  'spleen',
  'perfected form',
  'survival',
  'individual',
  'integration',
  'none',
  '11.56',
  'ajna',
  'throat',
  'curiosity',
  'seeker',
  'collective',
  'abstract',
  'sensing',
  '12.22',
  'throat',
  'solar',
  'openness',
  'social being',
  'individual',
  'knowing',
  'emoting',
  '13.33',
  'self',
  'throat',
  'prodigal',
  'being a witness',
  'collective',
  'abstract',
  'none',
  '16.48',
  'throat',
  'spleen',
  'wavelength',
  'talent',
  'collective',
  'logic',
  'taste',
  '17.62',
  'ajna',
  'throat',
  'acceptance',
  'organizational being',
  'collective',
  'logic',
  'understanding',
  '18.58',
  'spleen',
  'root',
  'judgement',
  'instability',
  'collective',
  'logic',
  'taste',
  '19.49',
  'solar',
  'root',
  'synthesis',
  'being sensitive',
  'tribal',
  'ego',
  'needs',
  '20.34',
  'throat',
  'sacral',
  'charisma',
  'move to do',
  'individual',
  'integration',
  'none',
  '20.57',
  'throat',
  'spleen',
  'brainwave',
  'penetrating awareness',
  'individual',
  'knowing',
  'intuition',
  '21.45',
  'heart',
  'throat',
  'moneyline',
  'materialist',
  'tribal',
  'ego',
  'none',
  '23.43',
  'throat',
  'ajna',
  'structuring',
  'individual genius or freak',
  'individual',
  'knowing',
  'knowing',
  '24.61',
  'ajna',
  'head',
  'awareness',
  'thinker or stinker',
  'individual',
  'knowing',
  'knowing',
  '25.51',
  'self',
  'heart',
  'initiation',
  'compete to be first',
  'individual',
  'centering',
  'none',
  '26.44',
  'heart',
  'spleen',
  'surrender',
  'transmitter',
  'tribal',
  'ego',
  'instinct',
  '27.50',
  'sacral',
  'spleen',
  'preservation',
  'custodianship',
  'tribal',
  'defense',
  'none',
  '28.38',
  'spleen',
  'root',
  'struggle',
  'being stubborn',
  'individual',
  'knowing',
  'intuition',
  '29.46',
  'sacral',
  'self',
  'discovery',
  'determination of the self',
  'collective',
  'abstract',
  'none',
  '30.41',
  'solar',
  'root',
  'recognition',
  'focused energy',
  'collective',
  'abstract',
  'feelings',
  '32.54',
  'spleen',
  'root',
  'transformation',
  'being driven',
  'tribal',
  'ego',
  'intuition',
  '34.57',
  'sacral',
  'spleen',
  'power',
  'archetype',
  'individual',
  'integration',
  'none',
  '35.36',
  'throat',
  'solar',
  'transitoriness',
  'a jack of all trades',
  'collective',
  'abstract',
  'feelings',
  '37.40',
  'solar',
  'heart',
  'community',
  'a part that needs the whole',
  'tribal',
  'ego',
  'needs',
  '39.55',
  'solar',
  'root',
  'emoting',
  'moodiness',
  'individual',
  'knowing',
  'emoting',
  '42.53',
  'sacral',
  'root',
  'maturation',
  'balanced development',
  'collective',
  'abstract',
  'none',
  '47.64',
  'ajna',
  'head',
  'abstract',
  'mental activity mixed with clarity',
  'collective',
  'abstract',
  'sensing',
];

final List<String> hdtypesList = [
  'manifestor',
  'manifesting generator',
  'generator',
  'projector',
  'reflector',
];

final List<String> hdauthority = [
  'emotional',
  'sacral',
  'splenic',
  'ego manifested',
  'ego projected',
  'self projected',
  'sound board',
  'lunar'
];

final List<String> hdstrategyList = [
  'inform with emotional clarity',
  'inform spontaneously',
  'inform at will',
  'respond with emotional clarity',
  'respond in the moment',
  'recognize invitation with emotional clarity',
  'recognize spontaneous invitation',
  'recognize invitation to prove yourself',
  'recognize invitation to express who you are',
  'recognize invitation to speak your mind',
  'watch the moon cycle',
];

final List<String> hdcenters = [
  'root',
  'solar',
  'sacral',
  'spleen',
  'heart',
  'self',
  'throat',
  'ajna',
  'head'
];

final List<String> fears = [
  'fear',
  'anxiety',
  'nervousness',
];

final List<int> numbers = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
];

final List hdgates = [
  0, 'No Gate',
  'no description',
  1, 'Self Expression',
  'Creation as a primal force. The energy potential to manifest inspiration without limitation.',
  2, 'Direction of the Self',
  'Receptivity as the primal base through which any response is determined. The root of action.',
  3, 'Ordering',
  'The fundamental challenge of initiation is to transcend confusion and establish order.',
  4, 'Formulization',
  'The energy to beguile and succeed despite ignorance. Freedom from retribution.',
  5, 'Fixed Patterns',
  'The fundamental attunement to natural rhythms. Waiting as an active state of awareness.',
  6, 'Friction',
  'The fundamental design component of progress. The law that growth cannot exist without friction.',
  7, 'Role of the Self in Interaction',
  'The point of convergence. By design, the need for leadership to guide and order society.',
  8, 'Contribution',
  'The basic worth realized in contributing individual efforts to group goals.',
  9, 'Focus',
  'Potential can be fulfilled through detailed attention to all pertinent aspects.',
  10,'Behavior of the Self',
  'The underlying code of behavior which ensures successful interaction despite circumstances.',
  11, 'Ideas',
  'A harmonic condition in the individual or society that permits assessment before renewed action.',
  12, 'Caution',
  'The quality of restraint and the importance of meditation and inaction in confronting temptation.',
  13, 'the Listener',
  'Universal ideas and values in an ordered framework which inspires humanistic cooperation.',
  14, 'Power Skills',
  'The accumulation and retention of power through skilled interaction, coupling grace with control.',
  15, 'Extremes',
  'The quality of behavior which expresses the proper balance between extremes.',
  16, 'Skills',
  'The great art of enriching life by the harmonic channelling of energy.',
  17, 'Opinion',
  'The ancient law that those who wish to rule must know how to serve.',
  18, 'Correction',
  'The vigilance and determination to uphold and defend basic and fundamental human rights.',
  19, 'Wanting',
  'That all things are interrelated is apparent and manifested through the action of approach.',
  20, 'Now',
  'Recognition and awareness in the now which transforms understanding into right action.',
  21, 'Hunter(ess)',
  'The justified and necessary use of power in overcoming deliberate and persistent interference.',
  22, 'Openness',
  'A quality of behavior best suited in handling mundane and trivial situations.',
  23, 'Assimilation',
  'Amorality. the awareness and understanding which leads to the acceptance of diversity.',
  24, 'Rationalization',
  'The natural and spontaneous process of transformation and renewal.',
  25, 'Spirit of the Self',
  'The perfection of action through uncontrived and spontaneous nature.',
  26, 'the Egoist',
  'The maximization of the power of memory applied to the nurturing of continuity.',
  27, 'Caring',
  'The enhancement of the quality and the substance of all activities through caring.',
  28, 'the Game Player',
  'The transitoriness of power and influence.',
  29, 'Perseverance',
  'The deep within the deep. Persistence despite difficulties has its inevitable rewards.',
  30, 'Feelings',
  'Freedom recognized as an illusion and limitation accepted as a fate.',
  31, 'Influence',
  'The law of friction, whether active or passive, that engenders transference and thus influence.',
  32, 'Continuty',
  'The only thing which endures is change.',
  33, 'Privacy',
  'Active withdrawal and the transformation of a weak position into a strength.',
  34, 'Power',
  'Power is only great when its display or use serves the common good..',
  35, 'Change',
  'By design, progress cannot exist in a vacuum and is dependent on interaction.',
  36, 'Crisis',
  'The rule of cycles in which decline is a natural but not enduring stage.',
  37, 'Friendship',
  'The manifestation macro- and micro-cosmically of the organic nature of communities.',
  38, 'the Fighter',
  'The ability to preserve individual integrity through opposition to detrimental forces.',
  39, 'Provocation',
  'The value of obstruction in provoking analysis, assessment and reevaluation.',
  40, 'Aloneness',
  'The point of transition between struggle and liberation.',
  41, 'Contraction',
  'The limitation of resources which maximizes development of potential.',
  42, 'Growth',
  'The expansion of the resources which maximizes the development of full potential.',
  43, 'Insight',
  'In order for achievement to be maintained a new order must be fairly established.',
  44, 'Alertness',
  'The success of any interaction is based on the absence of any preconditions.',
  45, 'the Gatherer',
  'The natural and generally beneficial attraction of like forces.',
  46, 'Determination of the Self',
  'Good fortune that may be perceived as the result of serendipity but derives from effort and dedication.',
  47, 'Realization',
  'A restrictive and adverse state as a result of internal weakness or external strength or both.',
  48, 'Depth',
  'The necessary and qualitative foundation that is a prerequisite to establish the common good.',
  49, 'Principles',
  'Ideally the transformation of forms based on the highest principles and not simply for power.',
  50, 'Values',
  'The value of historical continuity whose traditional values serve and enrich the present and the future.',
  51, 'Shock',
  'The ability to respond to disorder and shock through recognition and adaptation.',
  52, 'Stillness',
  'Temporary and self-imposed inaction for the benefit of assessment.',
  53, 'Beginnings',
  'Development as a structured progression that is both steadfast and enduring.',
  54, 'Drive',
  'Interaction in its mundane social context but also one\'s mystical and cosmic relationships.',
  55, 'Spirit',
  'Abundance is strictly a question of spirit.',
  56, 'Stimulation',
  'Stability through movement. The perpetuation of continuity through the linking of short term activity.',
  57, 'Intuitive Clarity',
  'The extraordinary power of clarity.',
  58, 'Vitality',
  'Stimulation is the key to joy.',
  59, 'Sexuality',
  'The ability to break down barriers to achieve union.',
  60, 'Acceptance',
  'The acceptance of limitation is the first step in transcendence.',
  61, 'Mystery',
  'The awareness of universal underlying principles.',
  62, 'Details',
  'Caution, patience and detail produce excellence out of limitation.',
  63, 'Doubt',
  'In the spiral of life, all ends are beginnings.',
  64, 'Confusion',
  'Transition, like birth, requires a determined strength for the passage through.',
];
