import 'dart:core';

final List<String> hdchannelRotationList = [
  '6.59',
  'silence of Mating',
  '27.50',
  'silence of Preservation',
  '42.53',
  'silence was Matured',
  '29.46',
  'silence was Discovered',
  '20.34',
  'silence is Moving',
  '34.57',
  'silence is empowering',
  '10.34',
  'silence is Being Explored',
  '2.14',
  'silence is Beating',
  '3.60',
  'silence is Mutating',
  '9.52',
  'silence shall Concentrate',
  '5.15',
  'silence shall Flow',
  '19.49',
  'Breath of Synthesis',
  '37.40',
  'Breath of Community',
  '32.54',
  'Breath Transformation',
  '26.44',
  'Breath Transmission',
  '30.41',
  'Breath was Recognized',
  '13.33',
  'Breath was Witnessed',
  '11.56',
  'Breath was Curious',
  '47.64',
  'Breath was Abstract',
  '10.20',
  'Breath is Awakening',
  '10.57',
  'Breath is Surviving',
  '25.51',
  'Breath is Initiating',
  '20.57',
  'Breath is Intuitive',
  '39.55',
  'Breath is Moody',
  '28.38',
  'Breath is Struggling',
  '1.8',
  'Breath is Inspiring',
  '23.43',
  'Breath is Genius',
  '24.61',
  'Breath is Awareness',
  '18.58',
  'Breath shall Judge',
  '16.48',
  'Breath shall be Talented',
  '17.62',
  'Breath shall Organize',
  '4.63',
  'Breath shall be Logic',
  '7.31',
  'Breath shall be an Alpha',
  '35.36',
  'COMPLEX was Transitioning',
  '12.22',
  'COMPLEX is Openning',
  '21.45',
  'COMPLEX Money',
];
final List<String> hdchannelsilenceList = [
  '6.59',
  'silence of Mating',
  '27.50',
  'silence of Preservation',
  '42.53',
  'silence was Matured',
  '29.46',
  'silence was Discovered',
  '20.34',
  'silence is Moving',
  '34.57',
  'silence is empowering',
  '10.34',
  'silence is Being Explored',
  '2.14',
  'silence is Beating',
  '3.60',
  'silence is Mutating',
  '9.52',
  'silence shall Concentrate',
  '5.15',
  'silence shall Flow',
];
final List<String> hdchannelbreathList = [
  '19.49',
  'Breath of Synthesis',
  '37.40',
  'Breath of Community',
  '32.54',
  'Breath Transformation',
  '26.44',
  'Breath Transmission',
  '30.41',
  'Breath was Recognized',
  '13.33',
  'Breath was Witnessed',
  '11.56',
  'Breath was Curious',
  '47.64',
  'Breath was Abstract',
  '10.20',
  'Breath is Awakening',
  '10.57',
  'Breath is Surviving',
  '25.51',
  'Breath is Initiating',
  '20.57',
  'Breath is Intuitive',
  '39.55',
  'Breath is Moody',
  '28.38',
  'Breath is Struggling',
  '1.8',
  'Breath is Inspiring',
  '23.43',
  'Breath is Genius',
  '24.61',
  'Breath is Awareness',
  '18.58',
  'Breath shall Judge',
  '16.48',
  'Breath shall be Talented',
  '17.62',
  'Breath shall Organize',
  '4.63',
  'Breath shall be Logic',
  '7.31',
  'Breath shall be an Alpha',
];

final List<String> hdchannelcomplexList = [
  '35.36',
  'COMPLEX was Transitioning',
  '12.22',
  'COMPLEX is Openning',
  '21.45',
  'COMPLEX Money',
];

final List<String> hdchannelcomplexList_heb = [
  '35.36',
  'מורכב התחלף',
  '12.22',
  'מורכב פותח',
  '21.45',
  'מורכב חומר',
];

final List<String> hdchannelbreathList_heb = [
  '19.49',
  'נשימות משולבות',
  '37.40',
  'נשימות קהילתיות',
  '32.54',
  'נשימה קיימת',
  '26.44',
  'נשימה מקיימת',
  '30.41',
  'נשימות הורגשו',
  '13.33',
  'נשימות העידו',
  '11.56',
  'נשימות הסתקרנו',
  '47.64',
  'נשימות התפשטו',
  '10.20',
  'הנשימה מתעוררת',
  '10.57',
  'הנשימה שורדת',
  '25.51',
  'נשימה חונכת',
  '20.57',
  'נשימה נרגעת',
  '39.55',
  'נשימות רוחניות',
  '28.38',
  'נשימה נאבקת',
  '1.8',
  'נשימה מכוונת',
  '23.43',
  'נשימה יודעת',
  '24.61',
  'נשימה מודעת',
  '18.58',
  'נשימות תשפוטנה',
  '16.48',
  'נשימות תשכללנה',
  '17.62',
  'נשימות תבינה',
  '4.63',
  'נשימות תהגה',
  '7.31',
  'נשימות תדריכנה',
];

final List<String> hdchannelsilenceList_heb = [
  '6.59',
  'שתיקות פוריות',
  '27.50',
  'שתיקה שמורה',
  '42.53',
  'שתיקות הבשילו',
  '29.46',
  'שתיקות התגלו',
  '20.34',
  'השתיקה נעה',
  '34.57',
  'השתיקה בריאה',
  '10.34',
  'שתיקה אוהבת',
  '2.14',
  'שתיקה פועמת',
  '3.60',
  'שתיקה משונה',
  '9.52',
  'שתיקות תתרכזנה',
  '5.15',
  'שתיקות תזרומנה',
];

final List<String> hdchannelsentenceList_eng = [
  '1.8',
  '1.8: I Breathe the Inspiration',
  '2.14',
  '2.14: I Silence the Beat',
  '3.60',
  '3.60: It Silences the Mutation',
  '4.63',
  '4.63: They shall Breathe the Logic',
  '5.15',
  '5.15: We shall Silence the Rhythm',
  '6.59',
  '6.59: Right Silences',
  '7.31',
  '7.31: We shall Breathe the Alpha',
  '9.52',
  '9.52: They shall Silence the Concentration',
  '10.20',
  '10.20: I am Breathing Awakening',
  '10.34',
  '10.34: I Silence the Exploration',
  '10.57',
  '10.57: I am Breathing the Perfected Form',
  '11.56',
  '11.56: They Breathed the Curiosity',
  '12.22',
  '12.22: It Complicates the Openness',
  '13.33',
  '13.33: We Breathed the Prodigals',
  '16.48',
  '16.48: They shall Breathe the Talented',
  '17.62',
  '17.62: They shall Breathe the Accepted',
  '18.58',
  '18.58: They shall Breathe the Judgement',
  '19.49',
  '19.49: Right Lower Breaths',
  '20.34',
  '20.34: Silencing the Charisma',
  '20.57',
  '20.57: It Breathes the Intuitive Clarity',
  '21.45',
  '21.45: COMPLEX Nouns',
  '23.43',
  '23.43: It Breathes the Structure',
  '24.61',
  '24.61: It Breathes the Awareness',
  '25.51',
  '25.51: I Breathe the Initation',
  '26.44',
  '26.44: an Upper Left Breath',
  '27.50',
  '27.50: a Left Silence',
  '28.38',
  '28.38: It Breathes the Struggle',
  '29.46',
  '29.46: We Silenced the Discovery',
  '30.41',
  '30.41: They Breathed the Recognition',
  '32.54',
  '32.54: a Left Lower Breath',
  '34.57',
  '34.57: Silencing the Power',
  '35.36',
  '35.36: They Complicated the Transit',
  '37.40',
  '37.40: Right Upper Breaths',
  '39.55',
  '39.55: It Breathes the Emoting',
  '42.53',
  '42.53: They Silenced the Maturation',
  '47.64',
  '47.64: They Breathed the Abstract'
];

final List<String> hdchannelsentenceList = [
  '1.8',
  '1.8: אני נושמת את ההשראה',
  '2.14',
  '2.14: אני שותקת בפעימה',
  '3.60',
  '3.60: זו משתיקה את המוטציה',
  '4.63',
  '4.63: הם ינשמו את ההגיון',
  '5.15',
  '5.15: אנחנו נשתוק בקצב',
  '6.59',
  '6.59: שתיקות ימניות',
  '7.31',
  '7.31: אנחנו ננשים את בראשית',
  '9.52',
  '9.52: הן תשתוקנה בריכוז',
  '10.20',
  '10.20: אני נושם בהתעוררות',
  '10.34',
  '10.34: אני שותקת באהבה',
  '10.57',
  '10.57: אני נושמת בצורה שלמה',
  '11.56',
  '11.56: הם נשמו בסקרנות',
  '12.22',
  '12.22: זה מרכיב את הפתיחות',
  '13.33',
  '13.33: נשמנו את העדויות',
  '16.48',
  '16.48: הם ינשמו את הכשרונות',
  '17.62',
  '17.62: הם ינשמו את קבלת השפה',
  '18.58',
  '18.58: הם ינשמו את השיפוט',
  '19.49',
  '19.49: נשימות ימניות תחתונות',
  '20.34',
  '20.34: להשתיק את התנועה',
  '20.57',
  '20.57: זה נושם בבהירות מיידית',
  '21.45',
  '21.45: מורכב משמות עצם',
  '23.43',
  '23.43: זה נושם את המבנה',
  '24.61',
  '24.61: זה נושם את המודעות',
  '25.51',
  '25.51: אני נושמת את החניכה',
  '26.44',
  '26.44: נשימה שמאלית עליונה',
  '27.50',
  '27.50: שתיקה שמאלית',
  '28.38',
  '28.38: זה נושם את המאבק',
  '29.46',
  '29.46: אנחנו שתקנו את הגילוי',
  '30.41',
  '30.41: הן נשמו את ההכרה',
  '32.54',
  '32.54: נשימה שמאלית תחתונה',
  '34.57',
  '34.57: להשתיק את הכוח',
  '35.36',
  '35.36: הן רכבו על ברת החלוף',
  '37.40',
  '37.40: נשימות ימניות עליונות',
  '39.55',
  '39.55: זו נושמת מצב רוח',
  '42.53',
  '42.53: הן שתקו בהתבגרות',
  '47.64',
  '47.64: הם נשמו את המופשט'
];

final List<String> hdchannelsentenceList_temp = [
  '1.8',
  'SELF BREATH is an Inspiring Expression',
  '2.14',
  'LIVE SILENCE is a Beating Self',
  '3.60',
  'LIVE SILENCE is a Mutating Pressure',
  '4.63',
  'MENTAL BREATHs shall be Logical Questions',
  '5.15',
  'LIVE SILENCEs shall be Flowing Love',
  '6.59',
  'EMOTIONAL SILENCEs of Mating Lives',
  '7.31',
  'SELF BREATHs shall be Alpha Expressions',
  '9.52',
  'LIVE SILENCEs shall Concentrate Pressures',
  '10.20',
  '(A) SELF BREATH is an Awakening Expression',
  '10.34',
  'LIVE SILENCE is an Explored Love',
  '10.57',
  '(A) HEALTHY BREATH is a Surviving Love',
  '11.56',
  'EXPRESSED BREATHs were Curious Minds',
  '12.22',
  'EMOTIONAL COMPLEX is an Openning Expression',
  '13.33',
  'SELF BREATHs were Witnessed Expressions',
  '16.48',
  'HEALTHY BREATHs shall be Talented Expressions',
  '17.62',
  'EXPRESSED BREATHs shall Organize Minds',
  '18.58',
  'HEALTHY BREATHs shall Judge Pressures',
  '19.49',
  'EMOTIONAL BREATHs of Synthesised Pressures',
  '20.34',
  '(A) LIVE SILENCE is a Moving Expression',
  '20.57',
  'HEALTHY BREATH is an Intuitive Expression',
  '21.45',
  'EGOs COMPLEX of Money Expressions',
  '23.43',
  'EXPRESSING BREATH is a Genius Mind',
  '24.61',
  'MIND BREATH is an Aware Question',
  '25.51',
  'EGO BREATH is an Initiating Love',
  '26.44',
  'HEALTHY BREATHs of Surrendered Egos',
  '27.50',
  'LIVE SILENCEs of Preserved Healths',
  '28.38',
  'HEALTHY BREATH is a Struggling Pressure',
  '29.46',
  'LIVE SILENCEs were Discovered Love',
  '30.41',
  'EMOTIONAL BREATHs were Recognized Pressures',
  '32.54',
  'HEALTHY BREATHs of a Transformed Pressures',
  '34.57',
  '(A) LIVE SILENCE is an empowering Health',
  '35.36',
  'EMOTIONAL COMPLEXes were Transitional Expressions',
  '37.40',
  'EMOTIONAL BREATHs of Communal Egos',
  '39.55',
  'an Emotional Breath is a Moody Pressure',
  '42.53',
  'LIVE SILENCEs were Matured Pressures',
  '47.64',
  'MIND BREATHs were Abstract Questions'
];

final List<String> hdchannelsentenceList_new = [
  '1.8',
  'a Self Breath is an Inspiring Expression',
  '2.14',
  'a Live silence is a Beating Self',
  '3.60',
  'a Live silence is a Mutating Pressure',
  '4.63',
  'Mental Breaths shall be Logical Questions',
  '5.15',
  'Live silences shall be Flowing Love',
  '6.59',
  'Emotional silences of Mating Lives',
  '7.31',
  'Self Breaths shall be Alpha Expressions',
  '9.52',
  'Live silences shall Concentrate Pressures',
  '10.20',
  'a Self Breath is an Awakening Expression',
  '10.34',
  'a Live silence is an Explored Love',
  '10.57',
  'a Healthy Breath is a Surviving Love',
  '11.56',
  'Expressed Breaths were Curious Minds',
  '12.22',
  'an Emotional COMPLEX is an Openning Expression',
  '13.33',
  'Self Breaths were Witnessed Expressions',
  '16.48',
  'Healthy Breaths shall be Talented Expressions',
  '17.62',
  'Expressed Breaths shall Organize Minds',
  '18.58',
  'Healthy Breaths shall Judge Pressures',
  '19.49',
  'Emotional Breaths of Synthesised Pressures',
  '20.34',
  'a Live silence is a Moving Expression',
  '20.57',
  'a Healhy Breath is an Intuitive Expression',
  '21.45',
  'Egos COMPLEX of Money Expressions',
  '23.43',
  'Expressing Breath is a Genius Mind',
  '24.61',
  'a Mind Breath is an Aware Question',
  '25.51',
  'an Ego Breath is Initiating Love',
  '26.44',
  'Healthy Breaths of Surrendered Egos',
  '27.50',
  'Live silences of Preserved Health',
  '28.38',
  'a Healthy Breath is a Struggling Pressure',
  '29.46',
  'Live silences were Discovered Love',
  '30.41',
  'Emotional Breaths were Recognized Pressures',
  '32.54',
  'Healthy Breaths of a Transformed Pressures',
  '34.57',
  'a Live silence is an empowering Health',
  '35.36',
  'Emotional COMPLEXes were Transitional Expressions',
  '37.40',
  'Emotional Breaths of Communal Egos',
  '39.55',
  'an Emotional Breath is a Moody Pressure',
  '42.53',
  'Live silences were Matured Pressures',
  '47.64',
  'Mind Breaths were Abstract Questions'
];

final List<String> hdchannelsentenceList_old = [
  '1.8',
  'Breath is Inspiring',
  '2.14',
  'silence is Beating',
  '3.60',
  'silence is Mutating',
  '4.63',
  'Breath shall be Logic',
  '5.15',
  'silence shall Flow',
  '6.59',
  'silence of Mating',
  '7.31',
  'Breath shall be an Alpha',
  '9.52',
  'silence shall Concentrate',
  '10.20',
  'Breath is Awakening',
  '10.34',
  'silence is Being Explored',
  '10.57',
  'Breath is Surviving',
  '11.56',
  'Breath was Curious',
  '12.22',
  'COMPLEX is Openning',
  '13.33',
  'Breath was Witnessed',
  '16.48',
  'Breath shall be Talented',
  '17.62',
  'Breath shall Organize',
  '18.58',
  'Breath shall Judge',
  '19.49',
  'Breath of Synthesis',
  '20.34',
  'silence is Moving',
  '20.57',
  'Breath is Intuitive',
  '21.45',
  'COMPLEX Money',
  '23.43',
  'Breath is Genius',
  '24.61',
  'Breath is Awareness',
  '25.51',
  'Breath is Initiating',
  '26.44',
  'Breath Transmission',
  '27.50',
  'silence of Preservation',
  '28.38',
  'Breath is Struggling',
  '29.46',
  'silence was Discovered',
  '30.41',
  'Breath was Recognized',
  '32.54',
  'Breath Transformation',
  '34.57',
  'silence is empowering',
  '35.36',
  'COMPLEX was Transitioning',
  '37.40',
  'Breath of Community',
  '39.55',
  'Breath is Moody',
  '42.53',
  'silence was Matured',
  '47.64',
  'Breath was Abstract'
];

final List<String> hdchannelsList = [
  '1.8',
  'self',
  'throat',
  'inspiration',
  'inspiring',
  'breath',
  'creative role model',
  'individual',
  'knowing',
  'none',
  '2.14',
  'self',
  'sacral',
  'beat',
  'beating',
  'silence',
  'keeper of keys',
  'individual',
  'knowing',
  'none',
  '3.60',
  'sacral',
  'root',
  'mutation',
  'mutative',
  'silence',
  'fluctuation',
  'individual',
  'knowing',
  'none',
  '4.63',
  'ajna',
  'head',
  'logic',
  'logical',
  'breath',
  'mental doubt eased',
  'collective',
  'logic',
  'understanding',
  '5.15',
  'sacral',
  'self',
  'rhythm',
  'rhythmic',
  'silence',
  'being in the flow',
  'collective',
  'logic',
  'none',
  '6.59',
  'solar',
  'sacral',
  'mating',
  'mating',
  'silence',
  'reproduction',
  'tribal',
  'defense',
  'none',
  '7.31',
  'self',
  'throat',
  'alpha',
  'alpha',
  'breath',
  'being a leader',
  'collective',
  'logic',
  'none',
  '9.52',
  'sacral',
  'root',
  'concentration',
  'concetrated',
  'silence',
  'determination',
  'collective',
  'logic',
  'none',
  '10.20',
  'self',
  'throat',
  'awakening',
  'awakening',
  'breath',
  'higher principles',
  'individual',
  'integration',
  'none',
  '10.34',
  'self',
  'sacral',
  'exploration',
  'exploring',
  'silence',
  'follow your conviction',
  'individual',
  'centering',
  'none',
  '10.57',
  'self',
  'spleen',
  'perfected form',
  'surviving',
  'breath',
  'survival',
  'individual',
  'integration',
  'none',
  '11.56',
  'ajna',
  'throat',
  'curiosity',
  'curious',
  'breath',
  'seeker',
  'collective',
  'abstract',
  'sensing',
  '12.22',
  'throat',
  'solar',
  'openness',
  'open',
  'complex',
  'social being',
  'individual',
  'knowing',
  'emoting',
  '13.33',
  'self',
  'throat',
  'prodigal',
  'witnessed',
  'breath',
  'being a witness',
  'collective',
  'abstract',
  'none',
  '16.48',
  'throat',
  'spleen',
  'wavelength',
  'talented',
  'breath',
  'talent',
  'collective',
  'logic',
  'taste',
  '17.62',
  'ajna',
  'throat',
  'acceptance',
  'accepting',
  'breath',
  'organizational being',
  'collective',
  'logic',
  'understanding',
  '18.58',
  'spleen',
  'root',
  'judgement',
  'judging',
  'breath',
  'instability',
  'collective',
  'logic',
  'taste',
  '19.49',
  'solar',
  'root',
  'synthesis',
  'sensitive',
  'breath',
  'being sensitive',
  'tribal',
  'ego',
  'needs',
  '20.34',
  'throat',
  'sacral',
  'charisma',
  'moving',
  'silence',
  'move to do',
  'individual',
  'integration',
  'none',
  '20.57',
  'throat',
  'spleen',
  'brainwave',
  'penetrating',
  'breath',
  'penetrating awareness',
  'individual',
  'knowing',
  'intuition',
  '21.45',
  'heart',
  'throat',
  'moneyline',
  'money',
  'complex',
  'materialist',
  'tribal',
  'ego',
  'none',
  '23.43',
  'throat',
  'ajna',
  'structuring',
  'structuring',
  'breath',
  'individual genius or freak',
  'individual',
  'knowing',
  'knowing',
  '24.61',
  'ajna',
  'head',
  'awareness',
  'aware',
  'breath',
  'thinker or stinker',
  'individual',
  'knowing',
  'knowing',
  '25.51',
  'self',
  'heart',
  'initiation',
  'initiating',
  'breath',
  'compete to be first',
  'individual',
  'centering',
  'none',
  '26.44',
  'heart',
  'spleen',
  'surrender',
  'surrendered',
  'breath',
  'transmitter',
  'tribal',
  'ego',
  'instinct',
  '27.50',
  'sacral',
  'spleen',
  'preservation',
  'preserved',
  'silence',
  'custodianship',
  'tribal',
  'defense',
  'none',
  '28.38',
  'spleen',
  'root',
  'struggle',
  'struggling',
  'breath',
  'being stubborn',
  'individual',
  'knowing',
  'intuition',
  '29.46',
  'sacral',
  'self',
  'discovery',
  'discovered',
  'silence',
  'determination of the self',
  'collective',
  'abstract',
  'none',
  '30.41',
  'solar',
  'root',
  'recognition',
  'recognized',
  'breath',
  'focused energy',
  'collective',
  'abstract',
  'feelings',
  '32.54',
  'spleen',
  'root',
  'transformation',
  'tranformed',
  'breath',
  'being driven',
  'tribal',
  'ego',
  'intuition',
  '34.57',
  'sacral',
  'spleen',
  'power',
  'powerful',
  'silence',
  'archetype',
  'individual',
  'integration',
  'none',
  '35.36',
  'throat',
  'solar',
  'transitoriness',
  'transitoriness',
  'complex',
  'a jack of all trades',
  'collective',
  'abstract',
  'feelings',
  '37.40',
  'solar',
  'heart',
  'community',
  'communal',
  'breath',
  'a part that needs the whole',
  'tribal',
  'ego',
  'needs',
  '39.55',
  'solar',
  'root',
  'emoting',
  'emoting',
  'breath',
  'moodiness',
  'individual',
  'knowing',
  'emoting',
  '42.53',
  'sacral',
  'root',
  'maturation',
  'matured',
  'silence',
  'balanced development',
  'collective',
  'abstract',
  'none',
  '47.64',
  'ajna',
  'head',
  'abstract',
  'abstract',
  'breath',
  'mental activity mixed with clarity',
  'collective',
  'abstract',
  'sensing',
];

final List<String> hdchannelsListold = [
  '1.8',
  'self',
  'throat',
  'inspiration',
  'creative role model',
  'individual',
  'knowing',
  'none',
  '2.14',
  'self',
  'sacral',
  'beat',
  'keeper of keys',
  'individual',
  'knowing',
  'none',
  '3.60',
  'sacral',
  'root',
  'mutation',
  'fluctuation',
  'individual',
  'knowing',
  'none',
  '4.63',
  'ajna',
  'head',
  'logic',
  'mental doubt eased',
  'collective',
  'logic',
  'understanding',
  '5.15',
  'sacral',
  'self',
  'rhythm',
  'being in the flow',
  'collective',
  'logic',
  'none',
  '6.59',
  'solar',
  'sacral',
  'mating',
  'reproduction',
  'tribal',
  'defense',
  'none',
  '7.31',
  'self',
  'throat',
  'alpha',
  'being a leader',
  'collective',
  'logic',
  'none',
  '9.52',
  'sacral',
  'root',
  'concentration',
  'determination',
  'collective',
  'logic',
  'none',
  '10.20',
  'self',
  'throat',
  'awakening',
  'higher principles',
  'individual',
  'integration',
  'none',
  '10.34',
  'self',
  'sacral',
  'exploration',
  'follow your conviction',
  'individual',
  'centering',
  'none',
  '10.57',
  'self',
  'spleen',
  'perfected form',
  'survival',
  'individual',
  'integration',
  'none',
  '11.56',
  'ajna',
  'throat',
  'curiosity',
  'seeker',
  'collective',
  'abstract',
  'sensing',
  '12.22',
  'throat',
  'solar',
  'openness',
  'social being',
  'individual',
  'knowing',
  'emoting',
  '13.33',
  'self',
  'throat',
  'prodigal',
  'being a witness',
  'collective',
  'abstract',
  'none',
  '16.48',
  'throat',
  'spleen',
  'wavelength',
  'talent',
  'collective',
  'logic',
  'taste',
  '17.62',
  'ajna',
  'throat',
  'acceptance',
  'organizational being',
  'collective',
  'logic',
  'understanding',
  '18.58',
  'spleen',
  'root',
  'judgement',
  'instability',
  'collective',
  'logic',
  'taste',
  '19.49',
  'solar',
  'root',
  'synthesis',
  'being sensitive',
  'tribal',
  'ego',
  'needs',
  '20.34',
  'throat',
  'sacral',
  'charisma',
  'move to do',
  'individual',
  'integration',
  'none',
  '20.57',
  'throat',
  'spleen',
  'brainwave',
  'penetrating awareness',
  'individual',
  'knowing',
  'intuition',
  '21.45',
  'heart',
  'throat',
  'moneyline',
  'materialist',
  'tribal',
  'ego',
  'none',
  '23.43',
  'throat',
  'ajna',
  'structuring',
  'individual genius or freak',
  'individual',
  'knowing',
  'knowing',
  '24.61',
  'ajna',
  'head',
  'awareness',
  'thinker or stinker',
  'individual',
  'knowing',
  'knowing',
  '25.51',
  'self',
  'heart',
  'initiation',
  'compete to be first',
  'individual',
  'centering',
  'none',
  '26.44',
  'heart',
  'spleen',
  'surrender',
  'transmitter',
  'tribal',
  'ego',
  'instinct',
  '27.50',
  'sacral',
  'spleen',
  'preservation',
  'custodianship',
  'tribal',
  'defense',
  'none',
  '28.38',
  'spleen',
  'root',
  'struggle',
  'being stubborn',
  'individual',
  'knowing',
  'intuition',
  '29.46',
  'sacral',
  'self',
  'discovery',
  'determination of the self',
  'collective',
  'abstract',
  'none',
  '30.41',
  'solar',
  'root',
  'recognition',
  'focused energy',
  'collective',
  'abstract',
  'feelings',
  '32.54',
  'spleen',
  'root',
  'transformation',
  'being driven',
  'tribal',
  'ego',
  'intuition',
  '34.57',
  'sacral',
  'spleen',
  'power',
  'archetype',
  'individual',
  'integration',
  'none',
  '35.36',
  'throat',
  'solar',
  'transitoriness',
  'a jack of all trades',
  'collective',
  'abstract',
  'feelings',
  '37.40',
  'solar',
  'heart',
  'community',
  'a part that needs the whole',
  'tribal',
  'ego',
  'needs',
  '39.55',
  'solar',
  'root',
  'emoting',
  'moodiness',
  'individual',
  'knowing',
  'emoting',
  '42.53',
  'sacral',
  'root',
  'maturation',
  'balanced development',
  'collective',
  'abstract',
  'none',
  '47.64',
  'ajna',
  'head',
  'abstract',
  'mental activity mixed with clarity',
  'collective',
  'abstract',
  'sensing',
];

final List<String> hdtypesList_org = [
  'manifestor',
  'manifesting generator',
  'generator',
  'projector',
  'reflector',
];

final List<String> hdtypesList = [
  'חזי מניפסטור',
  'בטי גנרטורית מגשימה',
  'בטי גנרטורית',
  'ביני פרוגקטור',
  'אבי רפקלטור',
];

final List<String> hdauthority_org = [
  'emotional',
  'sacral',
  'splenic',
  'ego manifested',
  'ego projected',
  'self projected',
  'sound board',
  'lunar'
];

final List<String> hdauthority = [
  'רגש',
  'בטן',
  'טחול',
  'רצון יוזם',
  'הכרת רצון',
  'עצמי',
  'מחשבה',
  'ירח'
];

final List<String> hdstrategyList_org = [
  'inform with emotional clarity',
  'inform spontaneously',
  'inform at will',
  'respond with emotional clarity',
  'respond in the moment',
  'recognize invitation with emotional clarity',
  'recognize spontaneous invitation',
  'recognize invitation to prove yourself',
  'recognize invitation to express who you are',
  'recognize invitation to conceptualize',
  'watch the moon cycle',
];

final List<String> hdstrategyList = [
  'מרגיש ליידע בבהירות',
  'ליידע על בריאות מיידית',
  'רצון ליידע',
  'להגיב ברגש בהיר',
  'להגיב',
  'להכיר ברגש בהיר',
  'להכיר בריאות מיידית',
  'להכיר רצון עצמי',
  'להכיר את עצמי',
  'להכיר את המחשבה',
  'לצפות בירח',
];

final List<String> hdcenters = [
  'root',
  'solar',
  'sacral',
  'spleen',
  'heart',
  'self',
  'throat',
  'ajna',
  'head'
];


final List<String> fears = [
  'fear',
  'anxiety',
  'nervousness',
];

final List<int> numbers = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
];

final List hdgates = [
  0, 'No Gate',
  'no description',
  1, 'Self Expression',
  'Creation as a primal force. The energy potential to manifest inspiration without limitation.',
  2, 'Direction of the Self',
  'Receptivity as the primal base through which any response is determined. The root of action.',
  3, 'Ordering',
  'The fundamental challenge of initiation is to transcend confusion and establish order.',
  4, 'Formulization',
  'The energy to beguile and succeed despite ignorance. Freedom from retribution.',
  5, 'Fixed Patterns',
  'The fundamental attunement to natural rhythms. Waiting as an active state of awareness.',
  6, 'Friction',
  'The fundamental design component of progress. The law that growth cannot exist without friction.',
  7, 'Role of the Self in Interaction',
  'The point of convergence. By design, the need for leadership to guide and order society.',
  8, 'Contribution',
  'The basic worth realized in contributing individual efforts to group goals.',
  9, 'Focus',
  'Potential can be fulfilled through detailed attention to all pertinent aspects.',
  10,'Behavior of the Self',
  'The underlying code of behavior which ensures successful interaction despite circumstances.',
  11, 'Ideas',
  'A harmonic condition in the individual or society that permits assessment before renewed action.',
  12, 'Caution',
  'The quality of restraint and the importance of meditation and inaction in confronting temptation.',
  13, 'the Listener',
  'Universal ideas and values in an ordered framework which inspires humanistic cooperation.',
  14, 'Power Skills',
  'The accumulation and retention of power through skilled interaction, coupling grace with control.',
  15, 'Extremes',
  'The quality of behavior which expresses the proper balance between extremes.',
  16, 'Skills',
  'The great art of enriching life by the harmonic channelling of energy.',
  17, 'Opinion',
  'The ancient law that those who wish to rule must know how to serve.',
  18, 'Correction',
  'The vigilance and determination to uphold and defend basic and fundamental human rights.',
  19, 'Wanting',
  'That all things are interrelated is apparent and manifested through the action of approach.',
  20, 'Now',
  'Recognition and awareness in the now which transforms understanding into right action.',
  21, 'Hunter(ess)',
  'The justified and necessary use of power in overcoming deliberate and persistent interference.',
  22, 'Openness',
  'A quality of behavior best suited in handling mundane and trivial situations.',
  23, 'Assimilation',
  'Amorality. the awareness and understanding which leads to the acceptance of diversity.',
  24, 'Rationalization',
  'The natural and spontaneous process of transformation and renewal.',
  25, 'Spirit of the Self',
  'The perfection of action through uncontrived and spontaneous nature.',
  26, 'the Egoist',
  'The maximization of the power of memory applied to the nurturing of continuity.',
  27, 'Caring',
  'The enhancement of the quality and the substance of all activities through caring.',
  28, 'the Game Player',
  'The transitoriness of power and influence.',
  29, 'Perseverance',
  'The deep within the deep. Persistence despite difficulties has its inevitable rewards.',
  30, 'Feelings',
  'Freedom recognized as an illusion and limitation accepted as a fate.',
  31, 'Influence',
  'The law of friction, whether active or passive, that engenders transference and thus influence.',
  32, 'Continuty',
  'The only thing which endures is change.',
  33, 'Privacy',
  'Active withdrawal and the transformation of a weak position into a strength.',
  34, 'Power',
  'Power is only great when its display or use serves the common good..',
  35, 'Change',
  'By design, progress cannot exist in a vacuum and is dependent on interaction.',
  36, 'Crisis',
  'The rule of cycles in which decline is a natural but not enduring stage.',
  37, 'Friendship',
  'The manifestation macro- and micro-cosmically of the organic nature of communities.',
  38, 'the Fighter',
  'The ability to preserve individual integrity through opposition to detrimental forces.',
  39, 'Provocation',
  'The value of obstruction in provoking analysis, assessment and reevaluation.',
  40, 'Aloneness',
  'The point of transition between struggle and liberation.',
  41, 'Contraction',
  'The limitation of resources which maximizes development of potential.',
  42, 'Growth',
  'The expansion of the resources which maximizes the development of full potential.',
  43, 'Insight',
  'In order for achievement to be maintained a new order must be fairly established.',
  44, 'Alertness',
  'The success of any interaction is based on the absence of any preconditions.',
  45, 'the Gatherer',
  'The natural and generally beneficial attraction of like forces.',
  46, 'Determination of the Self',
  'Good fortune that may be perceived as the result of serendipity but derives from effort and dedication.',
  47, 'Realization',
  'A restrictive and adverse state as a result of internal weakness or external strength or both.',
  48, 'Depth',
  'The necessary and qualitative foundation that is a prerequisite to establish the common good.',
  49, 'Principles',
  'Ideally the transformation of forms based on the highest principles and not simply for power.',
  50, 'Values',
  'The value of historical continuity whose traditional values serve and enrich the present and the future.',
  51, 'Shock',
  'The ability to respond to disorder and shock through recognition and adaptation.',
  52, 'Stillness',
  'Temporary and self-imposed inaction for the benefit of assessment.',
  53, 'Beginnings',
  'Development as a structured progression that is both steadfast and enduring.',
  54, 'Drive',
  'Interaction in its mundane social context but also one\'s mystical and cosmic relationships.',
  55, 'Spirit',
  'Abundance is strictly a question of spirit.',
  56, 'Stimulation',
  'Stability through movement. The perpetuation of continuity through the linking of short term activity.',
  57, 'Intuitive Clarity',
  'The extraordinary power of clarity.',
  58, 'Vitality',
  'Stimulation is the key to joy.',
  59, 'Sexuality',
  'The ability to break down barriers to achieve union.',
  60, 'Acceptance',
  'The acceptance of limitation is the first step in transcendence.',
  61, 'Mystery',
  'The awareness of universal underlying principles.',
  62, 'Details',
  'Caution, patience and detail produce excellence out of limitation.',
  63, 'Doubt',
  'In the spiral of life, all ends are beginnings.',
  64, 'Confusion',
  'Transition, like birth, requires a determined strength for the passage through.',
];

//idk

final List rotationtimenewwallet = [
  0, 'No Gate',
  'no description',
  1, 'Self Expression',
  'He neglects Self Expression.',
  2, 'Direction of the Self',
  'She builds the Driver.',
  3, 'Ordering',
  'It thinks to Order Difficult Beginning.',
  4, 'Formulization',
  'They shall use Forumlated Answers.',
  5, 'Fixed Patterns',
  'He shall neglect Fixed Patterns.',
  6, 'Friction',
  'They use Friction.',
  7, 'Role of the Self in Interaction',
  'They shall use Interactions.',
  8, 'Contribution',
  'She builds her contribution.',
  9, 'Focus',
  'He shall neglect to focus.',
  10,'Behavior of the Self',
  'He neglects his Self Behavior.',
  11, 'Ideas',
  'He neglected his ideas.',
  12, 'Caution',
  'She builds in caution.',
  13, 'the Listener',
  'It thought to listen.',
  14, 'Power Skills',
  'He neglects his richess.',
  15, 'Extremes',
  'She shall build in Extreme modesty.',
  16, 'Skills',
  'She shall build skillfully.',
  17, 'Opinion',
  'It shall think of opinions.',
  18, 'Correction',
  'They shall use the corrections.',
  19, 'Wanting',
  'He is a neglected need.',
  20, 'Now',
  'She builds now.',
  21, 'Hunter(ess)',
  'It is a thought of control.',
  22, 'Openness',
  'It thinks to open.',
  23, 'Assimilation',
  'She builds to assimilate.',
  24, 'Rationalization',
  'It thinks rationally.',
  25, 'Spirit of the Self',
  'It thinks of itself as Spirit.',
  26, 'the Egoist',
  'He is a neglected egoist.',
  27, 'Caring',
  'It is a thought of caring.',
  28, 'the Game Player',
  'They use the Game Player.',
  29, 'Perseverance',
  'They used the perseverance to say yes.',
  30, 'Feelings',
  'It thought of feelings.',
  31, 'Influence',
  'She shall build to influence.',
  32, 'Continuty',
  'They are used to continue.',
  33, 'Privacy',
  'She built privates.',
  34, 'Power',
  'He neglects his power.',
  35, 'Change',
  'She built to change.',
  36, 'Crisis',
  'It thought of crisis.',
  37, 'Friendship',
  'It is a thought of Family and Friends.',
  38, 'the Fighter',
  'He neglects to fight.',
  39, 'Provocation',
  'She builds Provocatively.',
  40, 'Aloneness',
  'They are used to be alone.',
  41, 'Contraction',
  'He neglected to contract.',
  42, 'Growth',
  'It thought to grow.',
  43, 'Insight',
  'He neglects his insight.',
  44, 'Alertness',
  'They are used to alert.',
  45, 'the Gatherer',
  'She is a building for gathering.',
  46, 'Determination of the Self',
  'They used to Determine themselves.',
  47, 'Realization',
  'They used to realize.',
  48, 'Depth',
  'They shall use depth.',
  49, 'Principles',
  'It is a thought of principles.',
  50, 'Values',
  'They are used values.',
  51, 'Shock',
  'It thinks of shock.',
  52, 'Stillness',
  'She shall build in stillness.',
  53, 'Beginnings',
  'She built beginnings.',
  54, 'Drive',
  'He is a neglected drive.',
  55, 'Spirit',
  'It thinks of a Spirit.',
  56, 'Stimulation',
  'She built to stimulate.',
  57, 'Intuitive Clarity',
  'They use intuitive clarity.',
  58, 'Vitality',
  'He shall neglect his vitality.',
  59, 'Sexuality',
  'They are used sexually.',
  60, 'Acceptance',
  'He neglects to accept.',
  61, 'Mystery',
  'He neglects thy mystery.',
  62, 'Details',
  'She shall build details',
  63, 'Doubt',
  'It shall think in doubt.',
  64, 'Confusion',
  'They used to confuse',
];

final List rotationtimenewwallet_heb = [
  0, 'נטול שער',
  'נטול תאור',
  1, 'ביטוי עצמי',
  'הוא זונח ביטוי עצמי.',
  2, 'כיוון עצמי',
  'היא בונה את הנהגת.',
  3, 'הוראה',
  'הוא חושב על ההוראה.',
  4, 'ניסוח',
  'הם ישתמשו בניסוח.',
  5, 'תבניות קבועות',
  'הוא יזנח את התבניות הקבועות.',
  6, 'חיכוך',
  'הם בשימוש החיכוך.',
  7, 'תפקיד העצמי בין פעולות',
  'הם ישתמשו בפעולות הביניים.',
  8, 'תרומה',
  'היא בונה את תרומתה.',
  9, 'מיקוד',
  'הוא יזנח את המיקוד.',
  10,'התנהגות עצמית',
  'הוא זונח את התנהגות עצמו.',
  11, 'רעיונות',
  'הוא זנח את רעיונותיו.',
  12, 'זהירות',
  'היא בונה בזהירות.',
  13, 'המאזין',
  'זה חשב להאזין.',
  14, 'מיומנויות כוח',
  'הוא זונח את כוח המיומן.',
  15, 'קיצוניות',
  'היא תבנה באופן קיצוני.',
  16, 'מיומנויות',
  'היא תבנה באופן מיומן.',
  17, 'דעה',
  'זה יחשוב על דעות.',
  18, 'תיקון',
  'הם ישתמשו בתיקונים.',
  19, 'לצרוך',
  'הוא צורך נזנח.',
  20, 'כעת',
  'היא בונה כעת.',
  21, 'צייד',
  'זה מחשבה בשליטה.',
  22, 'פתיחות',
  'הוא חושב לפתוח.',
  23, 'הטמעה',
  'היא בונה כדי להטמיע.',
  24, 'רציונל',
  'זה חושב ברציונליות.',
  25, 'רוח העצמי',
  'זה חושב על עצמו כרוח.',
  26, 'המוכיח',
  'הוא זונח את ההוכחה.',
  27, 'טיפול',
  'זה מחשבה בטיפול.',
  28, 'המהמר',
  'הם משתמשים במהמר.',
  29, 'התמדה',
  'הם השתמשו בהתמדה באלו שנענו בחיוב.',
  30, 'הרגשות',
  'זה חשב להרגיש.',
  31, 'השפעה',
  'היא בנתה השפעה.',
  32, 'המשכיות',
  'הם שימוש המשכי.',
  33, 'פרטיות',
  'היא בנתה באופן פרטי.',
  34, 'כוח',
  'הוא זנח את כוחו.',
  35, 'שינוי',
  'היא בנתה את השינוי.',
  36, 'משבר',
  'זה חשב על משבר.',
  37, 'חברות',
  'זה מחשבה על חברים ומשפחה.',
  38, 'הלוחם',
  'הוא זונח את המלמחה.',
  39, 'פרובוקציה',
  'היא בונה באופן מתגרה.',
  40, 'לבדות',
  'הם בשימוש גאולת הלבדות.',
  41, 'כיווץ',
  'הוא זנח את הכיווץ.',
  42, 'צמיחה',
  'זה חשב על צמיחה.',
  43, 'תובנה',
  'הוא זונח את התובנה.',
  44, 'דריכות',
  'הם בשימוש הדריכות.',
  45, 'האספן',
  'היא בניין לאספנים.',
  46, 'נחישות עצמית',
  'הם בשימוש נחישות עצמית.',
  47, 'התממשות',
  'הם השתמשו בהתממשות.',
  48, 'עומק',
  'הם ישתמשו בעומק.',
  49, 'עקרונות',
  'זה מחשבה בעקרון.',
  50, 'ערכים',
  'הם ערכים משומשים.',
  51, 'זעזוע',
  'זה חושב על זעזוע.',
  52, 'דממה',
  'היא תבנה בדממה.',
  53, 'התחלות',
  'היא בנתה התחלות.',
  54, 'דחף',
  'הוא דחף נזנח.',
  55, 'נפש',
  'זה חושב על נפש.',
  56, 'גירוי',
  'היא בנתה לגרות.',
  57, 'בהירות מיידית',
  'הם משתמשים בבהירות מיידית.',
  58, 'חיוניות',
  'הוא יזנח את החיוניות.',
  59, 'מיניות',
  'הם מין משומש.',
  60, 'קבלה',
  'הוא זונח את הקבלה.',
  61, 'תעלומה',
  'הוא זונח את התעלומה.',
  62, 'פרטים',
  'היא תבנה את הפרטים',
  63, 'ספק',
  'זה יחשוב בספק.',
  64, 'בלבול',
  'הם ישתמשו בבלבול.',
];

final List rtwalletq_heb = [
  0, 'נטול שער',
  'נטול תאור',

  13, 'המאזין',
  'זה חשב להאזין.',
  49, 'עקרונות',
  'זה מחשבה בעקרון.',
  30, 'הרגשות',
  'זה חשב להרגיש.',
  55, 'נפש',
  'זה חושב על נפש.',
  37, 'חברות',
  'זה מחשבה על חברים ומשפחה.',
  63, 'ספק',
  'זה יחשוב בספק.',
  22, 'פתיחות',
  'הוא חושב לפתוח.',
  36, 'משבר',
  'זה חשב על משבר.',
  25, 'רוח העצמי',
  'זה חושב על עצמו כרוח.',
  17, 'דעה',
  'זה יחשוב על דעות.',
  21, 'צייד',
  'זה מחשבה בשליטה.',
  51, 'זעזוע',
  'זה חושב על זעזוע.',
  42, 'צמיחה',
  'זה חשב על צמיחה.',
  3, 'הוראה',
  'הוא חושב על ההוראה.',
  27, 'טיפול',
  'זה מחשבה בטיפול.',
  24, 'רציונל',
  'זה חושב ברציונליות.',

  2, 'כיוון עצמי',
  'היא בונה את הנהגת.',
  23, 'הטמעה',
  'היא בונה כדי להטמיע.',
  8, 'תרומה',
  'היא בונה את תרומתה.',
  20, 'כעת',
  'היא בונה כעת.',
  16, 'מיומנויות',
  'היא תבנה באופן מיומן.',
  45, 'האספן',
  'היא בניין לאספנים.',
  35, 'שינוי',
  'היא בנתה את השינוי.',
  12, 'זהירות',
  'היא בונה בזהירות.',
  15, 'קיצוניות',
  'היא תבנה באופן קיצוני.',
  52, 'דממה',
  'היא תבנה בדממה.',
  39, 'פרובוקציה',
  'היא בונה באופן מתגרה.',
  53, 'התחלות',
  'היא בנתה התחלות.',
  62, 'פרטים',
  'היא תבנה את הפרטים',
  56, 'גירוי',
  'היא בנתה לגרות.',
  31, 'השפעה',
  'היא בנתה השפעה.',
  33, 'פרטיות',
  'היא בנתה באופן פרטי.',

  7, 'תפקיד העצמי בין פעולות',
  'הם ישתמשו בפעולות הביניים.',
  4, 'ניסוח',
  'הם ישתמשו בניסוח.',
  29, 'התמדה',
  'הם השתמשו בהתמדה באלו שנענו בחיוב.',
  59, 'מיניות',
  'הם מין משומש.',
  40, 'לבדות',
  'הם בשימוש גאולת הלבדות.',
  64, 'בלבול',
  'הם ישתמשו בבלבול.',
  47, 'התממשות',
  'הם השתמשו בהתממשות.',
  6, 'חיכוך',
  'הם בשימוש החיכוך.',
  46, 'נחישות עצמית',
  'הם בשימוש נחישות עצמית.',
  18, 'תיקון',
  'הם ישתמשו בתיקונים.',
  48, 'עומק',
  'הם ישתמשו בעומק.',
  57, 'בהירות מיידית',
  'הם משתמשים בבהירות מיידית.',
  32, 'המשכיות',
  'הם שימוש המשכי.',
  50, 'ערכים',
  'הם ערכים משומשים.',
  28, 'המהמר',
  'הם משתמשים במהמר.',
  44, 'דריכות',
  'הם בשימוש הדריכות.',

  1, 'ביטוי עצמי',
  'הוא זונח ביטוי עצמי.',
  43, 'תובנה',
  'הוא זונח את התובנה.',
  34, 'כוח',
  'הוא זנח את כוחו.',
  14, 'מיומנויות כוח',
  'הוא זונח את כוח המיומן.',
  9, 'מיקוד',
  'הוא יזנח את המיקוד.',
  5, 'תבניות קבועות',
  'הוא יזנח את התבניות הקבועות.',
  26, 'המוכיח',
  'הוא זונח את ההוכחה.',
  11, 'רעיונות',
  'הוא זנח את רעיונותיו.',
  10,'התנהגות עצמית',
  'הוא זונח את התנהגות עצמו.',
  58, 'חיוניות',
  'הוא יזנח את החיוניות.',
  38, 'הלוחם',
  'הוא זונח את המלמחה.',
  54, 'דחף',
  'הוא דחף נזנח.',
  61, 'תעלומה',
  'הוא זונח את התעלומה.',
  60, 'קבלה',
  'הוא זונח את הקבלה.',
  41, 'כיווץ',
  'הוא זנח את הכיווץ.',
  19, 'לצרוך',
  'הוא צורך נזנח.',


];

// idk

final List hdiching_heb = [
  13, 'אחוות האדם', 'המקשיב','שומע הסודות',
  49, 'המהפכה', 'הדחייה','מודעות פוטנציאלית ורוחניות טקסית',
  30, 'האש הנאחזת', 'שער הרגשות','להיכנע לגורל',
  55,'שפע', 'הרוח','איכות הרוח היא ברגע הרגשי',
  37,'המשפחה','החברות','הנכונות לאמץ את האאוטסיידר',
  63, 'לאחר סיום', 'הספק','הספק הוא השראה חיונית',
  22, 'חסד', 'הפתיחות','שיתוף רוחניות עם אחרים',
  36, 'החשכת האור','המשבר','לחכות לבהירות רגשית',
  25, 'התמימות','הרוח של העצמי','הלוחם הרוחני',
  17, 'עוקב אחרי','הדעות', 'מקורקע בפרטים',
  21, 'נעיצת שיניים','הצייד-הציידת','כוחו של רצון',
  51, 'המעורר','הזעזוע','ההתעוררות מעצימה את כיוון האהבה',
  42, 'הגדלה','הצמיחה','-הגביע הקדוש- הוא החוויה',
  3, 'קושי בהתחלה','סידור','מוטציה שינוי גנטי נוצר ומועצם',
  27, 'הזנה','האכפתיות והטיפול','טיפול קודם כול בעצמי',
  24, 'החזרה','הרציונליזציה','ההשראה צריכה לקבל צורה רציונלית',

  2, 'הפתוח לרעיונות','כיוון העצמי','הנהג',
  23, 'היפרדות','הטמיעה','הסרת חוסר הסובלנות',
  8, 'החזקה ביחד','התרומה','להוביל על ידי דוגמה אישית',
  20, 'התבוננות','העכשיו','הנני עכשיו',
  16, 'התלהבות','הכישרונות','הכישרון לחיות את החיים כאמנות',
  35, 'התקדמות','השינוי','הסוד הוא -ללא ציפיות-',
  45, 'איסוף','האוסף','השליט',
  12, 'חוסר תנועה','הזהירות','שחרור מודעות ברוח הנכונה',
  15,'ענווה','הקיצוניות','אהבת האנושות',
  52,'ללא תזוזה (הר)','חוסר התזוזה','אנרגיה מנותבת וממוקדת',
  39,'חסימה','הפרובוקציה','המסע לקראת הרוח',
  53,'התפתחות','ההתחלות','מעבר ושינוי',
  62,'יתרונו של הקטן','הפרטים','הגשמה דרך פרטים',
  56,'הנווד','הסטימולציה','מספר הסיפורים',
  31,'השפעה','ההשפעה','אני מנהיג',
  33,'נסיגה','הפרטיות','התגלות הסודות',

  33,'','','',

  15,'','','',
// not complete
];

final hdgodheads = [
  'hades',
  'prometheus',
  'vishnu',
  'keepers of the wheel',

  'kali',
  'mitra',
  'michael',
  'janus',

  'maia',
  'lakshmi',
  'parvati',
  'maat',

  'toth',
  'harmonia',
  'christ',
  'minerva',
];

List revgodheads = hdgodheads.reversed.toList();
List revhebgodheads = hdhebgodheads.reversed.toList();
List revrtgodheads = rtgodheads.reversed.toList();


final hdhebgodheads = [
  'אליל אתרוג',
  'אליל הבטחה מקצועית',
  'אליל ניגוב נוזף',
  'אליל שומר זמן סיבוב',

  'אליל קל לי',
  'אליל מי תר גמל רע',
  'אליל מי כרטיס כאל',
  'אליל בורח למחשב',

  'האלילה מאי ה',
  'אלילת מי חברת הקש',
  'אלילה ואיתה הפרה',
  'אלילת מעט זה הרבה',

  'תות האלילה',
  'אלילת הר הכסף',
  'אלילת יש שעועית',
  'אלילת מינית רווה'
];

final rtgodheads = [
  'אליל מורכב מורכב',
  'אליל מורכב פשוט',
  'אליל מורכב נשימה',
  'אליל מורכב שתיקה',

  'אליל פשוט מורכב',
  'אליל פשוט פשוט',
  'אליל פשוט נשימה',
  'אליל פשוט שתיקה',

  'אלילה שתיקה שתיקה',
  'אלילה שתיקה נשימה',
  'אלילה שתיקה פשוט',
  'אלילה שתיקה מורכב',

  'אלילה נשימה שתיקה',
  'אלילה נשימה נשימה',
  'אלילה נשימה פשוט',
  'אלילה נשימה מורכב'
];