final List hexlinesList = [
  0,
  'six :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  1,
  'nine :: Hidden dragon. Do Not act.',
  'nine :: Dragon appears in the field. It furthers one to see the great man.',
  'nine :: All day long the superior man is creatively active. At nightfall his mind is still beset with cares. Danger. No blame.',
  'nine :: Wavering flight over the depths. No blame',
  'nine :: Flying dragon in the heavens. It furthers one to see the great man.',
  'nine :: Arrogant dragon will have cause to repent.',
  2,
  'six :: When there is hoarfrost underfoot, solid ice is not far off.',
  'six :: Straight, square, great. Without purpose, yet nothing remains unfurthered.',
  'six :: Hidden lines. One is able to remain persevering. If by chance you are in the service of a king, seek not works, but bring to completion.',
  'six :: A tied-up sack. No blame, no praise.',
  'six :: A yellow lower garment brings supreme good fortune.',
  'six :: Dragons fight in the meadow. Their blood is black and yellow.',
  3,
  'nine :: Hesitation and hindrance. It furthers one to remain persevering. It furthers one to appoint helpers.',
  'six :: Difficulties pile up. Horse and wagon part. He is not a robber, he wants to woo when the time comes. The maiden is chaste, she does not pledge herself. Ten years - then she pledges herself.',
  'six :: Whoever hunts deer without the forester only loses his way in the forest. The superior man understands the signs of the time and prefers to desist. To go on is humiliation.',
  'six :: Horse and wagon part. Strive for union. To go brings good fortune.',
  'nine :: Difficulties in blessing. A little perseverance brings good fortune. Great perseverance brings misfortune.',
  'six :: Horse and wagon part. Bloody tears flow.',
  4,
  'six :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  5,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  6,
  'six :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  7,
  'six :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  8,
  'six :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  9,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  10,
  'nine :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  11,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  12,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  13,
  'nine :: meaning.',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  14,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  15,
  'six :: meaning.',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  16,
  'six :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  17,
  'nine :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  18,
  'six :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  19,
  'nine :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  20,
  'six :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  21,
  'nine :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  22,
  'nine :: meaning.',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  23,
  'grandmother silent knowing speaks for itself',
  'mother speaks through silent knowing',
  'daughter silent knowing is heavy on her mothers',
  'son silent knowing is heavy on his sister',
  'father knows inhalation is a burden in the world',
  'grandfather knows exhalation is exalted in the beyond',
  24,
  'grandmother simple rational thought is too light',
  'mother simple rational thought is considered',
  'daughter silent rational thought supports her mother',
  'son silent rational thought is heavy on his sister',
  'father silent rational thought is a burden in the world',
  'grandfather silent rational thought falls from heaven',
  25,
  'grandmother simple innocence does not ground love',
  'mother simple innocence grounds love',
  'daughter innocent breath grounds her mothers love',
  'son innocent breath aspires family love',
  'father innocence complex aspires worldly love',
  'grandfather innocence complex aspires heavenly love',
  26,
  'grandmother complex trick is exposed too much',
  'mother complex trick is exposed to her daughter',
  'daughter simple trick escapes her mothers',
  'son simple trick block his sister',
  'father breath trick is not welcome in the world',
  'grandfather breath trick is heavenly ',
  27,
  'grandmother simple care is too positive',
  'mother simple care grounds her',
  'daughter silent care grounds her mother',
  'son silent care is heavy on his sister',
  'father inhales worldly care too heavily',
  'grandfather exhales care up to heaven',
  28,
  'grandmother inhale grounded risk',
  'mother premature risk escapes her',
  'daughter complex risk pushes her brother',
  'son complex risk aspires the family',
  'father simple risk is success in the world ',
  'grandfather simple risk is a burden to his son',
  29,
  'grandmother inhalation is persevered in the deep water',
  'mother exhalation do not persevere in mid water',
  'daughter persevere in silent high water',
  'son silent perseverance is a heavy on the family',
  'father simple swim perseveres through dark clouds',
  'grandfather simple swim do not persevere in heaven',
  30,
  'grandmother simple fire is quickly extinguished',
  'mother simple fire is long lasting',
  'daughter complex fire burns her brother',
  'son complex fire lightens the family',
  'father inhales fire and is burnt in the world',
  'grandfather exhaled fire enlightens heavenly bonfire',
  31,
  'grandmother leads silently even in the grave',
  'mother leads silently during life',
  'daughter influences her complex brother too lightly',
  'son leads the complex of the family',
  'father simple influence leads the world',
  'grandfather simple influence is heavy on his son',
  32,
  'grandmother inhales failure during wind',
  'mother exhales failure too early during wind',
  'daughter complex failure escapes the wind of her mothers',
  'son complex failure moves during thunder',
  'father silent thundering failure is ruined in the world',
  'grandfather silent failure is ruining his son',
  33,
  'grandmother silent retreat deep in the mountain',
  'mother silent retreat with her mother',
  'daughter complex retreat away from the mountain',
  'son timely advances to his fathers',
  'father timing is remembered throughout the world',
  'grandfather timing is heavenly memory',
  34,
  'grandmother complex power is blinding',
  'mother complex power is too bright',
  'daughter complex power is outshined by brother',
  'son complex power shines in the family',
  'father silent power is heavy on the world',
  'grandfather silent power is hidden from heaven',
  35,
  'grandmother silent progress does not change even in the grave',
  'mother silent progress does not change life',
  'daughter inhale progress in changing earth',
  'son exhales progress to change his family',
  'father inhales worldly changes heavily',
  'grandfather exhales change into heaven',
  36,
  'grandmother simple crisis is too easy in the firebase',
  'mother simple crisis allows the fire to burn on the ground',
  'daughter simple crisis extinguishes the fire',
  'son simple crisis is heavy on the family',
  'father silent world crisis is heavy on the sky',
  'grandfather silent heavenly crisis rejects liberation',
  37,
  'grandmother simple family escapes her',
  'mother simple family protects her',
  'daughter escapes the simple family',
  'son is stuck in the simple family',
  'father complex family shines in the world',
  'grandfather complex family shines in heaven',
  38,
  'grandmother complex fight misses the picnic on the lake',
  'mother all too often fights her daughter in the lake',
  'daughter inhales the fight to balance her mothers on the lake',
  'son exhales the firefight for family balance',
  'father inhales world firefight and is burnt',
  'grandfather exhales to heaven any firefight',
  39,
  'grandmother provokes silence deep in the mountain',
  'mother provokes grounding silence',
  'daughter simple provocation escapes the mountain',
  'son simple provocation opposes his sister escape',
  'father simple provocation is a bridge over troubled ocean',
  'grandfather simple provocation floods the world',
  40,
  'grandmother inhales family work as hard as ice',
  'mother exhales family work in premature deliverance',
  'daughter inhales family work to repent for her mother',
  'son exhales family work to shine for his fathers',
  'father work in the world is rejected',
  'grandfather work is banished from heaven',
  41,
  'grandmother fantasy time arrives too soon',
  'mother fantasy time arrives only too short',
  'daughter silent fantasy grounds her mothers',
  'son silent fantasy burdens his sister',
  'father inhale burden of world fantasy',
  'grandfather exhale his fantasy up to heaven',
  42,
  'grandmother simple growth is cut prematurely',
  'mother simple growth is safe and sound',
  'daughter silent growth grounds her mother',
  'son silent growth burdens his sister',
  'father complex growth enlightens the world',
  'grandfather complex growth penetrates heaven',
  43,
  'grandmother complex insight is too light',
  'mother complex insight is too early',
  'daughter complex insight pushes her brother',
  'son complex insight inspires the family',
  'father simple insight crosses the world',
  'grandfather simple insight is a heavy on his son',
  44,
  'grandmother is alert to inhale wind slowly',
  'mother is alert and exhales wind too fast ',
  'daughter complex alert escapes the wind',
  'son time alert aspires his family',
  'father time alert crosses the world  ',
  'grandfather time alert goes beyond the universe',
  45,
  'grandmother is the silent owner of earth',
  'mother is the silent owner of her body',
  'daughter inhales her mothers property',
  'son exhales shines the family ownership',
  'father simple ownership gathers the world',
  'grandfather simple ownership cuts through his sons',
  46,
  'grandmother determined inhalation balances the wind',
  'mother determined exhalation blows the wind too early',
  'daughter simple determination pushes her brother',
  'son simple determination is heavy on his sister',
  'father silent determination is a world burden',
  'grandfather silent determination is rejected from heaven',
  47,
  'grandmother oppresses inhalation in deep water',
  'mother oppressed exhalation escapes the water too early',
  'daughter oppressed inhalation on the water surface',
  'son oppressed exhalation is exalted in the family',
  'father simple realization polishes the world',
  'grandfather simple realization is not welcome in heaven',
  48,
  'grandmother inhales solutions deep into the wind',
  'mother exhales solutions to early into the wind',
  'daughter simple solution in blown by the wind',
  'son simple solution is is dropped on his sister',
  'father simple solution rides through the ocean',
  'grandfather simple solution is banished from heaven',
  49,
  'grandmother simple principle is a revolution too soon',
  'mother simple principle is a welcomed revolution',
  'daughter complex principle pushes her brother revolution',
  'son complex principle inspires the family revolution',
  'father simple principle is reflected in world revolution',
  'grandfather simple principle is a burden to his son',
  50,
  'grandmother value is to inhale the wind to ground',
  'mother value is to exhale the wind too early',
  'daughter complex value pushes her brother',
  'son complex value fires through the family',
  'father inhales world value too heavily',
  'grandfather exhales heavenly value',
  51,
  'grandmother simple shock roars too easily',
  'mother simple shock roars from the ground',
  'daughter inhales shock of mothers roar',
  'son exhales shock inspire family roar',
  'father silent shock depresses the world',
  'grandfather silent shock is banished from heaven',
  52,
  'grandmother silent meditation serves lifetimes',
  'mother silent meditation serves her life',
  'daughter simple meditation is to escape the mountain',
  'son simple meditation is a burden to his sister',
  'father inhales mediation to depress the world',
  'grandfather exhales meditation to exalt heaven',
  53,
  'grandmother begins silence deep in the mountain',
  'mother begins silence on the ground ',
  'daughter simple start pushes her brother',
  'son simple start is heavy on his sister',
  'father complex development begins in the world',
  'grandfather complex development begins in heaven',
  54,
  'grandmother complex ambition drives all too fast',
  'mother complex ambition drives her too early',
  'daughter inhales ambition to balance her mothers',
  'son exhales ambition to inspire his family',
  'father silent ambition is heavy on the world',
  'grandfather silent ambition is rejected from heaven',
  55,
  'grandmother simple spirit fires too fast',
  'mother simple spirit fires the ground',
  'daughter complex spirit pushes her brother',
  'son complex spirit inspires the family',
  'father silent spirit is heavy on the world',
  'grandfather silent spirit is rejected from heaven',
  56,
  'grandmother silently wanders the mountain',
  'mother silently wanders on the ground',
  'daughter complex belief pushes her brother',
  'son complex belief inspires the family',
  'father inhales world belief too seriously',
  'grandfather exhales the story of heaven',
  57,
  'grandmother inhales the wind to the ground',
  'mother exhales the wind too soon',
  'daughter exhales the wind to push her brother',
  'son inhales the wind to depress his sister',
  'father is gentle through the wind of the world',
  'grandfather gentle blow reaches heaven',
  58,
  'grandmother joy complex is brushed easily',
  'mother joy complex does not serve her',
  'daughter inhales joy to cover her mothers',
  'son exhales joy through family',
  'father simple joy keeps the world alive',
  'grandfather simple joy is rejected from heaven',
  59,
  'grandmother inhales sexuality through deep water',
  'mother exhales sexuality to disperse water early',
  'daughter silent sexuality is taken from mothers',
  'son silent sexuality is heavy on his sister',
  'father complex sexuality spreads through the world',
  'grandfather complex sexuality spreads through heaven',
  60,
  'grandmother complex limitation is too strong',
  'mother complex limitation is too early',
  'daughter silent limitation accepts her mother',
  'son silent limitation burdens his sister',
  'father simple acceptance shines in the world',
  'grandfather simple acceptance is rejected by heaven',
  61,
  'grandmother complex mystery is exposed too much',
  'mother complex mystery is exposed too early',
  'daughter silent truth grounds her mother',
  'son silent truth burdens his sister',
  'father complex mystery is truth in the world',
  'grandfather complex mystery is truth in heaven',
  62,
  'grandmother silent detail is for lifetimes',
  'mother silent detail serves her',
  'daughter complex detail pushes her brother',
  'son complex detail shines through the family',
  'father silent detail is a world burden',
  'grandfather silent detail is rejected from heaven',
  63,
  'grandmother simple doubt is all too early',
  'mother simple doubt serves her well',
  'daughter simple doubt pushes her brother',
  'son simple doubt blocks his sister',
  'father simple doubt inspires the world',
  'grandfather simple doubt in heaven rejects him afterlife',
  64,
  'grandmother inhales confusion into deep water',
  'mother exhales confusion to escape the water early',
  'daughter inhales confusion to ground her mother',
  'son exhales confusion to shine through the family',
  'father inhales a confused world too seriously',
  'grandfather exhales heaven before all is completed',
];

// Human Design
final List hdlinesList = [
  0,
  '+1 :: planet :: sentence.',
  '-1 :: planet :: sentence.',
  '+2 :: planet :: sentence.',
  '-2 :: planet :: sentence.',
  '+3 :: planet :: sentence.',
  '-3 :: planet :: sentence.',
  '+4 :: planet :: sentence.',
  '-4 :: planet :: sentence.',
  '+5 :: planet :: sentence.',
  '-5 :: planet :: sentence.',
  '+6 :: planet :: sentence.',
  '-6 :: planet :: sentence.',
  1,
  '+1 :: moon :: the moon exalted as a symbol of adaptation. Time is everything. Self Expression which has its special timing.',
  '-1 :: uranus :: instability leads to distortion. Here, patience is a virtue and revolution a vice. Creative instability unless there is patience.',
  '+2 :: venus :: venus exalted as a symbol of beauty. The required harmony between established values and ideals that enriches inspiration. Self Expression conditioned by ideals and values.',
  '-2 :: mars :: desires and passions have their place but not at the expense of Creation. Self Expression limited by desires and passions.',
  '+3 :: mars :: mars exalted as the symbol of the profound need for Self Expression. The deep need for Self Expression.',
  '-3 :: earth :: material forces can disrupt creatively and lead to overambition. Materialism disrupts creativity.'
  '+4 :: earth :: the earth as a symbol of personal perspective manifested outside of influence, where the potential magic of inspiration is diluted. Creativity that must develop outside of influence.',
  '-4 :: jupiter :: where the potential magic of inspiration is diluted. The need to influence that abandons aloneness and limits creativity.',
  '+5 :: mars :: mars exalted for its powerful ego endurance. The power and drive to stay with the Creative process.',
  '-5 :: uranus :: uranus in detriment, where eccentricity can handicap endurance. Eccentricity that though attractive will limit the drive.',
  '+6 :: earth :: clear assessment of creative value. Clarity on Creative expression.',
  '-6 :: pluto :: the risk that subjective appraisal will result in disappointment and creative frustration. Subjectivity in Self Expression that may lead to Creative frustration.',
  2,
  '+1 :: venus :: the importance of aesthetics whether inborn or acquired. Higher knowing through aesthetics.',
  '-1 :: mars :: the assertion of ego in spite of wisdom. The urge for action the will ignore the wisdom of the Higher Self.',
  '+2 :: saturn :: the inner strength to focus and realize. A natural gift for unlearnable knowing.',
  '-2 :: mars :: Genius as madness. Knowledge exclusively as power for the enhancement of the ego. The delusion that knowledge is power.',
  '+3 :: jupiter :: dedication to a lifetime of receptivity with the maturity to accept that the process never ends. When connected permanently to gate 14 through the Beat Channel, rewards for services rendered. The recognition that receptivity is a lifelong process.',
  '-3 :: uranus :: for the revolutionary patience is a vice. Higher Knowing that cannot wait and demands expression.',
  '+4 :: venus :: the Higher goal transcends personal acclaim. The team player, acknowledged as the leader but never the captain. Where Higher Knowing does not have to be expressed to be recognized.',
  '-4 :: mars :: loose lips sink ships. The unquenchable fire of the ego engenders enmity. The inability to keep silent when the opportunity arises for expression.',
  '+5 :: mercury :: the strategist with mercury exalted. Reasoned management of resources. Higher Knowing as a gift for strategy.',
  '-5 :: earth :: the inability to share responsibility or recognize the abilities of others. Higher Knowing as an exclusively individual and selfish process.',
  '+6 :: mercury :: with mercury exalted, less negative, thought the intellect becomes absorbed in constant rationalization. Higher Knowing is extremely narrow in its receptivity.',
  '-6 :: saturn :: the need for security may distort awareness to its ultimate perversion, destructiveness. The Higher Self absorbed with the mundane and the need for security.',
  3,
  '+1 :: earth :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  4,
  '+1 :: moon :: sentence.',
  '-1 :: earth :: sentence.',
  '+2 :: moon :: sentence.',
  '-2 :: mars :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: sun :: sentence.',
  '-4 :: saturn :: sentence.',
  '+5 :: jupiter :: sentence.',
  '-5 :: pluto :: sentence.',
  '+6 :: mercury :: sentence.',
  '-6 :: mars :: sentence.',
  5,
  '+1 :: mars :: sentence.',
  '-1 :: earth :: sentence.',
  '+2 :: venus :: sentence.',
  '-2 :: pluto :: sentence.',
  '+3 :: neptune :: sentence.',
  '-3 :: moon :: sentence.',
  '+4 :: uranus :: sentence.',
  '-4 :: sun :: sentence.',
  '+5 :: venus :: sentence.',
  '-5 :: pluto :: sentence.',
  '+6 :: neptune :: sentence.',
  '-6 :: none :: sentence.',
  6,
  '+1 :: pluto :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: venus :: sentence.',
  '-2 :: mars :: sentence.',
  '+3 :: neptune :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: sun :: sentence.',
  '-4 :: pluto :: sentence.',
  '+5 :: venus :: sentence.',
  '-5 :: moon :: sentence.',
  '+6 :: mercury :: sentence.',
  '-6 :: venus :: sentence.',
  7,
  '+1 :: venus :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: neptune :: sentence.',
  '-2 :: mercury :: sentence.',
  '+3 :: moon :: sentence.',
  '-3 :: mercury :: sentence.',
  '+4 :: sun :: sentence.',
  '-4 :: uranus :: sentence.',
  '+5 :: venus :: sentence.',
  '-5 :: neptune :: sentence.',
  '+6 :: mercury :: sentence.',
  '-6 :: uranus :: sentence.',
  8,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  9,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  10,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  11,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  12,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  13,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  14,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  15,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  16,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  17,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  18,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  19,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  20,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  21,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  22,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  23,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  24,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  25,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  26,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  27,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  28,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  29,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  30,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  31,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  32,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  33,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  34,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  35,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  36,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  37,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  38,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  39,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  40,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  41,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  42,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  43,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  44,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  45,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  46,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  47,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  48,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  49,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  50,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  51,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  52,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  53,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  54,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  55,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  56,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  57,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  58,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  59,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  60,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  61,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  62,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  63,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  64,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
];

// iChing
// wilhelm
final List ichinglinesList = [
  0,
  'grandmother',
  'mother',
  'daughter',
  'son',
  'father',
  'grandfather',
  1,
  'grandmother stuck in hell',
  'mother life is hell',
  'daughter complicated life',
  'son complicated life',
  'father is one foot from heaven',
  'grandfather died and is up in heaven',
  2,
  'grandmother remains silent',
  'mother tries to remain silent',
  'daughter suffers from silence',
  'son suffers from silence',
  'father is tortured from silence',
  'grandfather is silently falling from the top',
  3,
  'grandmother simple life is too easy to be expressed',
  'mother simple life is grounded and well lived',
  'silent daughter is fit for hardship',
  'silent son suffers hardship',
  'father simple life bring light to the world',
  'grandfather simple life burdens generations',
  4,
  'grandmother breath grounds her answers',
  'mother breath answers too light',
  'daughter silent answer is heavily thought',
  'son silent answer is burdens his family',
  'father breath is burdened to answer the world',
  'grandfather breath enlightens heaven ',
  5,
  'grandmother complex waiting pushes the Q too much',
  'mother complex waiting pushes her in the Q',
  'daughter simple waiting pushes her brother',
  'son simple waiting burdens his sister',
  'father simple patience crosses oceans',
  'grandfather simple patience is rejected by heaven',
  6,
  'grandmother breathe conflict and grounds herself',
  'mother breathe out conflict from herself',
  'daughter breathe in conflict properly',
  'son breathe out conflict and family suffers',
  'father resolves complex conflicts in the world',
  'grandfather conflict complex resolution reaches heaven',
  7,
  'grandmother breath interacts deeply with herself',
  'mother breath interacts to easily ',
  'daughter silently interacts with her mothers',
  'son silence burdens his interactions with the family',
  'father silence burdens world interactions',
  'grandfather silent interaction makes heaven like hell',
  8,
  'grandmother contributes to most profound silence ',
  'mother contributes to proper silence',
  'daughter contributes to silence of mothers',
  'son silent contribution burdens the family',
  'father simple contribution is known world wide',
  'grandfather simple contribution burdens his legacy',
  9,
  'grandmother complex focus has no ground at all',
  'mother complex focus is not grounded ',
  'daughter simple focus is to run from her mothers',
  'son simple focus burdens his family',
  'father complex focus reaches globally',
  'grandfather complex focus is known in heaven',
  10,
  'grandmother good behavior is never seen',
  'mother good behavior is rarely appreciated',
  'daughter negative behavior fits her role',
  'son behavior is rewarded',
  'father behavior is known world wide',
  'grandfather behavior remembered for generations',
  11,
  'grandmother idea brings war',
  'mother idea brings no resolution',
  'daughter idea is to leave the family',
  'son is not peaceful with his ideas',
  'father is not the ideal father',
  'grandfather forgets all his memory',
  12,
  'grandmother silent caution is deeply rooted',
  'mother silent caution protects her',
  'daughter breath sometimes cautions her mothers',
  'son breath moves cautiously to his fathers ',
  'father breath cautions strangers',
  'grandfather breath cautions heaven',
  13,
  'grandmother simple secret is revealed too easily',
  'mother simple secret is properly kept hidden',
  'daughter complex secret is mistakenly revealed to her brother',
  'son complex secret is properly told to father',
  'father complex secret is exposed to everyone',
  'grandfather complex secret reaches god',
  14,
  'grandmother wisdom is blackened',
  'mother wisdom is shadowed',
  'daughter wisdom cuts the feminine roots',
  'son is inspired to be like grandfather and oppose his father',
  'father breath heavily and suffer',
  'grandfather is happy his grandson carries his wealth',
  15,
  'grandmother silent modesty is her epitaph of love',
  'mother silent modesty grounds love',
  'daughter simple modesty pushes her brother',
  'son simple modesty burdens his sister',
  'father silent modesty is not loved in the world',
  'grandfather silent modesty is not accepted in heaven ',
  16,
  'grandmother silent skills are grounded for lifetimes',
  'mother silent skills grounds her',
  'daughter breathe skills from her mothers',
  'son breathe skills from his father',
  'father silent skills are not welcome in the world',
  'grandfather silent skills burdens his entire legacy',
  17,
  'grandmother light opinion do not serve her',
  'mother simple opinion grounds her',
  'daughter sound opinion grounds her mothers',
  'son sound opinion follows his father',
  'father simple opinion is followed worldwide',
  'grandfather simple opinion is hell for his legacy',
  18,
  'grandmother correctly inhales earth',
  'mother incorrectly exhales too soon',
  'daughter simple correction is too light',
  'son simple correction is too heavy',
  'father breath correction is rejected worldwide',
  'grandfather breath correction is welcome on heaven',
  19,
  'grandmother complex needs do not approach her roots',
  'mother complex needs do not yield to her mother',
  'daughter silent needs repent for her mothers',
  'son silent needs are a burden to his sister',
  'father silent needs are a burden to his son',
  'grandfather silent needs are a burden to his son',
  20,
  'grandmother is silent now all the way to the grave',
  'mother is silent now with her mother',
  'daughter contemplates the female silence',
  'son silent contemplation is not welcome by his sister',
  'father complex contemplation is worldly known',
  'grandfather complex contemplates now in heaven',
  21,
  'grandmother simple control escapes too much',
  'mother simple control grounds her',
  'daughter controlled breath of grounds her mother',
  'son controlled breath is aspired by father',
  'father controlled breath is a burden to the world',
  'grandfather controlled breath moves in heaven',
  22,
  'grandmother simple grace escapes her',
  'mother simple grace grounds her',
  'daughter simple grace pushes her brother',
  'son simple grace is heavy on his sister',
  'father gracefully inhale the burden of the world',
  'grandfather exhale grace into heaven',
  23,
  'grandmother silent knowing speaks for itself',
  'mother speaks through silent knowing',
  'daughter silent knowing is heavy on her mothers',
  'son silent knowing is heavy on his sister',
  'father knows inhalation is a burden in the world',
  'grandfather knows exhalation is exalted in the beyond',
  24,
  'grandmother simple rational thought is too light',
  'mother simple rational thought is considered',
  'daughter silent rational thought supports her mother',
  'son silent rational thought is heavy on his sister',
  'father silent rational thought is a burden in the world',
  'grandfather silent rational thought falls from heaven',
  25,
  'grandmother simple innocence does not ground love',
  'mother simple innocence grounds love',
  'daughter innocent breath grounds her mothers love',
  'son innocent breath aspires family love',
  'father innocence complex aspires worldly love',
  'grandfather innocence complex aspires heavenly love',
  26,
  'grandmother complex trick is exposed too much',
  'mother complex trick is exposed to her daughter',
  'daughter simple trick escapes her mothers',
  'son simple trick block his sister',
  'father breath trick is not welcome in the world',
  'grandfather breath trick is heavenly ',
  27,
  'grandmother simple care is too positive',
  'mother simple care grounds her',
  'daughter silent care grounds her mother',
  'son silent care is heavy on his sister',
  'father inhales worldly care too heavily',
  'grandfather exhales care up to heaven',
  28,
  'grandmother inhale grounded risk',
  'mother premature risk escapes her',
  'daughter complex risk pushes her brother',
  'son complex risk aspires the family',
  'father simple risk is success in the world ',
  'grandfather simple risk is a burden to his son',
  29,
  'grandmother inhalation is persevered in the deep water',
  'mother exhalation do not persevere in mid water',
  'daughter persevere in silent high water',
  'son silent perseverance is a heavy on the family',
  'father simple swim perseveres through dark clouds',
  'grandfather simple swim do not persevere in heaven',
  30,
  'grandmother simple fire is quickly extinguished',
  'mother simple fire is long lasting',
  'daughter complex fire burns her brother',
  'son complex fire lightens the family',
  'father inhales fire and is burnt in the world',
  'grandfather exhaled fire enlightens heavenly bonfire',
  31,
  'grandmother leads silently even in the grave',
  'mother leads silently during life',
  'daughter influences her complex brother too lightly',
  'son leads the complex of the family',
  'father simple influence leads the world',
  'grandfather simple influence is heavy on his son',
  32,
  'grandmother inhales failure during wind',
  'mother exhales failure too early during wind',
  'daughter complex failure escapes the wind of her mothers',
  'son complex failure moves during thunder',
  'father silent thundering failure is ruined in the world',
  'grandfather silent failure is ruining his son',
  33,
  'grandmother silent retreat deep in the mountain',
  'mother silent retreat with her mother',
  'daughter complex retreat away from the mountain',
  'son timely advances to his fathers',
  'father timing is remembered throughout the world',
  'grandfather timing is heavenly memory',
  34,
  'grandmother complex power is blinding',
  'mother complex power is too bright',
  'daughter complex power is outshined by brother',
  'son complex power shines in the family',
  'father silent power is heavy on the world',
  'grandfather silent power is hidden from heaven',
  35,
  'grandmother silent progress does not change even in the grave',
  'mother silent progress does not change life',
  'daughter inhale progress in changing earth',
  'son exhales progress to change his family',
  'father inhales worldly changes heavily',
  'grandfather exhales change into heaven',
  36,
  'grandmother simple crisis is too easy in the firebase',
  'mother simple crisis allows the fire to burn on the ground',
  'daughter simple crisis extinguishes the fire',
  'son simple crisis is heavy on the family',
  'father silent world crisis is heavy on the sky',
  'grandfather silent heavenly crisis rejects liberation',
  37,
  'grandmother simple family escapes her',
  'mother simple family protects her',
  'daughter escapes the simple family',
  'son is stuck in the simple family',
  'father complex family shines in the world',
  'grandfather complex family shines in heaven',
  38,
  'grandmother complex fight misses the picnic on the lake',
  'mother all too often fights her daughter in the lake',
  'daughter inhales the fight to balance her mothers on the lake',
  'son exhales the firefight for family balance',
  'father inhales world firefight and is burnt',
  'grandfather exhales to heaven any firefight',
  39,
  'grandmother provokes silence deep in the mountain',
  'mother provokes grounding silence',
  'daughter simple provocation escapes the mountain',
  'son simple provocation opposes his sister escape',
  'father simple provocation is a bridge over troubled ocean',
  'grandfather simple provocation floods the world',
  40,
  'grandmother inhales family work as hard as ice',
  'mother exhales family work in premature deliverance',
  'daughter inhales family work to repent for her mother',
  'son exhales family work to shine for his fathers',
  'father work in the world is rejected',
  'grandfather work is banished from heaven',
  41,
  'grandmother fantasy time arrives too soon',
  'mother fantasy time arrives only too short',
  'daughter silent fantasy grounds her mothers',
  'son silent fantasy burdens his sister',
  'father inhale burden of world fantasy',
  'grandfather exhale his fantasy up to heaven',
  42,
  'grandmother simple growth is cut prematurely',
  'mother simple growth is safe and sound',
  'daughter silent growth grounds her mother',
  'son silent growth burdens his sister',
  'father complex growth enlightens the world',
  'grandfather complex growth penetrates heaven',
  43,
  'grandmother complex insight is too light',
  'mother complex insight is too early',
  'daughter complex insight pushes her brother',
  'son complex insight inspires the family',
  'father simple insight crosses the world',
  'grandfather simple insight is a heavy on his son',
  44,
  'grandmother is alert to inhale wind slowly',
  'mother is alert and exhales wind too fast ',
  'daughter complex alert escapes the wind',
  'son time alert aspires his family',
  'father time alert crosses the world  ',
  'grandfather time alert goes beyond the universe',
  45,
  'grandmother is the silent owner of earth',
  'mother is the silent owner of her body',
  'daughter inhales her mothers property',
  'son exhales shines the family ownership',
  'father simple ownership gathers the world',
  'grandfather simple ownership cuts through his sons',
  46,
  'grandmother determined inhalation balances the wind',
  'mother determined exhalation blows the wind too early',
  'daughter simple determination pushes her brother',
  'son simple determination is heavy on his sister',
  'father silent determination is a world burden',
  'grandfather silent determination is rejected from heaven',
  47,
  'grandmother oppresses inhalation in deep water',
  'mother oppressed exhalation escapes the water too early',
  'daughter oppressed inhalation on the water surface',
  'son oppressed exhalation is exalted in the family',
  'father simple realization polishes the world',
  'grandfather simple realization is not welcome in heaven',
  48,
  'grandmother inhales solutions deep into the wind',
  'mother exhales solutions to early into the wind',
  'daughter simple solution in blown by the wind',
  'son simple solution is is dropped on his sister',
  'father simple solution rides through the ocean',
  'grandfather simple solution is banished from heaven',
  49,
  'grandmother simple principle is a revolution too soon',
  'mother simple principle is a welcomed revolution',
  'daughter complex principle pushes her brother revolution',
  'son complex principle inspires the family revolution',
  'father simple principle is reflected in world revolution',
  'grandfather simple principle is a burden to his son',
  50,
  'grandmother value is to inhale the wind to ground',
  'mother value is to exhale the wind too early',
  'daughter complex value pushes her brother',
  'son complex value fires through the family',
  'father inhales world value too heavily',
  'grandfather exhales heavenly value',
  51,
  'grandmother simple shock roars too easily',
  'mother simple shock roars from the ground',
  'daughter inhales shock of mothers roar',
  'son exhales shock inspire family roar',
  'father silent shock depresses the world',
  'grandfather silent shock is banished from heaven',
  52,
  'grandmother silent meditation serves lifetimes',
  'mother silent meditation serves her life',
  'daughter simple meditation is to escape the mountain',
  'son simple meditation is a burden to his sister',
  'father inhales mediation to depress the world',
  'grandfather exhales meditation to exalt heaven',
  53,
  'grandmother begins silence deep in the mountain',
  'mother begins silence on the ground ',
  'daughter simple start pushes her brother',
  'son simple start is heavy on his sister',
  'father complex development begins in the world',
  'grandfather complex development begins in heaven',
  54,
  'grandmother complex ambition drives all too fast',
  'mother complex ambition drives her too early',
  'daughter inhales ambition to balance her mothers',
  'son exhales ambition to inspire his family',
  'father silent ambition is heavy on the world',
  'grandfather silent ambition is rejected from heaven',
  55,
  'grandmother simple spirit fires too fast',
  'mother simple spirit fires the ground',
  'daughter complex spirit pushes her brother',
  'son complex spirit inspires the family',
  'father silent spirit is heavy on the world',
  'grandfather silent spirit is rejected from heaven',
  56,
  'grandmother silently wanders the mountain',
  'mother silently wanders on the ground',
  'daughter complex belief pushes her brother',
  'son complex belief inspires the family',
  'father inhales world belief too seriously',
  'grandfather exhales the story of heaven',
  57,
  'grandmother inhales the wind to the ground',
  'mother exhales the wind too soon',
  'daughter exhales the wind to push her brother',
  'son inhales the wind to depress his sister',
  'father is gentle through the wind of the world',
  'grandfather gentle blow reaches heaven',
  58,
  'grandmother joy complex is brushed easily',
  'mother joy complex does not serve her',
  'daughter inhales joy to cover her mothers',
  'son exhales joy through family',
  'father simple joy keeps the world alive',
  'grandfather simple joy is rejected from heaven',
  59,
  'grandmother inhales sexuality through deep water',
  'mother exhales sexuality to disperse water early',
  'daughter silent sexuality is taken from mothers',
  'son silent sexuality is heavy on his sister',
  'father complex sexuality spreads through the world',
  'grandfather complex sexuality spreads through heaven',
  60,
  'grandmother complex limitation is too strong',
  'mother complex limitation is too early',
  'daughter silent limitation accepts her mother',
  'son silent limitation burdens his sister',
  'father simple acceptance shines in the world',
  'grandfather simple acceptance is rejected by heaven',
  61,
  'grandmother complex mystery is exposed too much',
  'mother complex mystery is exposed too early',
  'daughter silent truth grounds her mother',
  'son silent truth burdens his sister',
  'father complex mystery is truth in the world',
  'grandfather complex mystery is truth in heaven',
  62,
  'grandmother silent detail is for lifetimes',
  'mother silent detail serves her',
  'daughter complex detail pushes her brother',
  'son complex detail shines through the family',
  'father silent detail is a world burden',
  'grandfather silent detail is rejected from heaven',
  63,
  'grandmother simple doubt is all too early',
  'mother simple doubt serves her well',
  'daughter simple doubt pushes her brother',
  'son simple doubt blocks his sister',
  'father simple doubt inspires the world',
  'grandfather simple doubt in heaven rejects him afterlife',
  64,
  'grandmother inhales confusion into deep water',
  'mother exhales confusion to escape the water early',
  'daughter inhales confusion to ground her mother',
  'son exhales confusion to shine through the family',
  'father inhales a confused world too seriously',
  'grandfather exhales heaven before all is completed',
];