//idonotknow

List reversedidklinesList = idonotknowlinesList.reversed.toList();

final List idonotknowlinesList = [
  0,
  'granny (minimother)',
  'mama (mother)',
  'daughter (sister)',
  'son (brother)',
  'papa (father)',
  'grampa (grandfather)',
  1,
  'granny complex heavenly life reach nowhere',
  'mama complex self expression inspire only herself',
  'daughter complex creativity pushes her brother',
  'son complex creativity inspires the family',
  'papa complex self expression creates the world',
  'grampa complex self expression creates heaven',
  2,
  'granny silent life is received in earth',
  'mama silent life is received by her',
  'daughter silent life is received by her mama',
  'son silent life is heavy on his sister',
  'papa silent life is not welcome in the world',
  'grampa silent life is hell',
  3,
  'granny simple beginning roars difficulties',
  'mama simple difficulty begins to ground her',
  'silent daughter is fit for hardship to begin with',
  'silent son suffers hardship',
  'papa simple difficulty begins to pour into the world',
  'grampa simple difficulty begins to burden generations',
  4,
  'granny inhalation grounds her answers to deep water',
  'mama exhalation is too light of an answer',
  'daughter silent answer is heavily weighed',
  'son silent answer burdens his sister',
  'papa inhalation is a heavy answer in the world',
  'grampa exhalation answers from the mountain into heaven',
  5,
  'granny complex waiting pushes the Q too much',
  'mama complex waiting pushes her in the Q',
  'daughter simple waiting pushes her brother',
  'son simple waiting burdens his sister',
  'papa simple patience waters the world',
  'grampa simple patience is rejected by heaven',
  6,
  'granny inhales conflict to preserve water',
  'mama exhales conflict from herself too easily',
  'daughter inhales conflict to clear water',
  'son exhales conflicts away from the family',
  'papa complex conflict enllightens the world',
  'grampa complex conflict open doors to heaven',
  7,
  'granny inhales interaction with water deeply',
  'mama exhales her interaction in stale water too soon',
  'daughter silently interacts with her mamas',
  'son silence burdens his interactions with his sister',
  'papa silent interaction burdens worldy interactions',
  'grampa silent interaction makes life as hard as hell',
  8,
  'granny contributes to ground most profound silence',
  'mama contributes to establish her grounded silence',
  'daughter silent contribution supports her mama',
  'son silent contribution burdens his sister',
  'papa simple contribution pours rain across world ground',
  'grampa simple contribution floods his legacy',
  9,
  'granny complex focus has no ground at all',
  'mama complex focus is not grounded',
  'daughter simple focus is to run away from her mama',
  'son simple focus burdens his sister',
  'papa complex focus is a fresh air to the world',
  'grampa complex focus swirls up to heaven',
  10,
  'granny complex behavior by the lake is all too soon',
  'mama complex behavior is all too early for her',
  'daughter inhales proper behavior to support her mama',
  'son exhales his behavior and is rewarded in the family',
  'papa complex behavior saves the world',
  'grampa complex behavior is a model in heaven',
  11,
  'granny complex idea shines too brightly',
  'mama complex idea get her to blossom too fast',
  'daughter simple idea is to leave her mama',
  'son simple idea is a burden to his sister',
  'papa silent idea is a heavey in the world',
  'grampa silent idea burdens his legacy',
  12,
  'granny silent caution is deeply rooted to ground',
  'mama silent caution protects her',
  'daughter inhales cautiously to support her mama',
  'son exhales cautiously to empower the family ',
  'papa complex standstill empowers the world',
  'grampa complex standstill open the gate to heaven',
  13,
  'granny simple secret fires too easily',
  'mama simple secret maintains her fire',
  'daughter complex secret burns her brother',
  'son complex secret shines through the family',
  'papa complex secret shines to the world',
  'grampa complex secret shines up to heaven',
  14,
  'granny complex wealth is too much to handle',
  'mama complex wealth is too much for her',
  'daughter complex wealth pushes her brother',
  'son complex wealth fires through the family',
  'papa inhales worldly wealth heavily',
  'grampa exahales wealth that fires to heaven',
  15,
  'granny silent modesty is her epitaph of love',
  'mama silent modesty stills love',
  'daughter simple modesty pushes her brother',
  'son simple modesty burdens his sister',
  'papa silent modesty is not loved in the world',
  'grampa silent modesty is not accepted in heaven ',
  16,
  'granny silent skill is grounded for lifetimes',
  'mama silent skill grounds her',
  'daughter inhales skill to ground her mama',
  'son exhaled skill is an enthusiasm in the family',
  'papa silent skill is not welcome in the world',
  'grampa silent skill burdens his entire legacy',
  17,
  'granny light opinion do not serve her',
  'mama simple opinion grounds her',
  'daughter sound opinion grounds her mamas',
  'son sound opinion follows his papa',
  'papa simple opinion is followed worldwide',
  'grampa simple opinion is hell for his legacy',
  18,
  'granny correctly inhales wind',
  'mama incorrectly exhales wind too soon',
  'daughter simple correction is too airy',
  'son simple correction is too mounted',
  'papa breath correction is not mounted worldwide',
  'grampa breath correction is welcome on top of the mountain',
  19,
  'granny complex needs do not approach her roots',
  'mama complex needs do not yield to her mama',
  'daughter silent needs repent for her mamas',
  'son silent needs are a burden to his sister',
  'papa silent needs are a burden to his son',
  'grampa silent needs are a burden to his son',
  20,
  'granny is silent now all the way to the grave',
  'mama is silent now with her mama',
  'daughter contemplates the female silence',
  'son silent contemplation is not welcome by his sister',
  'papa complex contemplation is worldly known',
  'grampa complex contemplates now in heaven',
  21,
  'granny simple control escapes too much',
  'mama simple control grounds her',
  'daughter controlled breath of grounds her mama',
  'son controlled breath is aspired by papa',
  'papa controlled breath is a burden to the world',
  'grampa controlled breath moves in heaven',
  22,
  'granny simple grace escapes her',
  'mama simple grace grounds her',
  'daughter simple grace pushes her brother',
  'son simple grace is heavy on his sister',
  'papa gracefully inhales the burden of the world',
  'grampa exhales grace into heaven',
  23,
  'granny silent knowing speaks for the earth',
  'mama silent knowing speaks for her',
  'daughter silent knowing supports on her mamas',
  'son silent knowing is heavy on his sister',
  'papa knows to inhale the burden in the world',
  'grampa knows how to exhale up to heaven',
  24,
  'granny simple rational thought is too light',
  'mama simple rational thought is considered',
  'daughter silent rational thought supports her mama',
  'son silent rational thought is heavy on his sister',
  'papa silent rational thought is a burden in the world',
  'grampa silent rational thought falls from heaven',
  25,
  'granny simple innocence does not ground love',
  'mama simple innocence grounds love',
  'daughter innocent breath grounds her mamas love',
  'son innocent breath aspires family love',
  'papa innocence complex aspires worldly love',
  'grampa innocence complex aspires heavenly love',
  26,
  'granny complex trick is exposed too much',
  'mama complex trick is exposed to her daughter',
  'daughter simple trick is to escape her mama',
  'son simple trick is to block his sister',
  'papa inhalation trick is not welcome in the world',
  'grampa exhalation trick is heavenly ',
  27,
  'granny simple care is too positive',
  'mama simple care grounds her',
  'daughter silent care grounds her mama',
  'son silent care is heavy on his sister',
  'papa inhales worldly care too heavily',
  'grampa exhales care up to heaven',
  28,
  'granny inhale grounded risk',
  'mama premature risk escapes her',
  'daughter complex risk pushes her brother',
  'son complex risk aspires the family',
  'papa simple risk is success in the world ',
  'grampa simple risk is a burden to his son',
  29,
  'granny inhalation is persevered in the deep water',
  'mama exhalation do not persevere in mid water',
  'daughter persevere in silent high water',
  'son silent perseverance is a heavy on the family',
  'papa simple swim perseveres through dark clouds',
  'grampa simple swim do not persevere in heaven',
  30,
  'granny simple fire is quickly extinguished',
  'mama simple fire is long lasting',
  'daughter complex fire burns her brother',
  'son complex fire lightens the family',
  'papa inhales fire and is burnt in the world',
  'grampa exhaled fire enlightens heavenly bonfire',
  31,
  'granny leads silently even in the grave',
  'mama leads silently during life',
  'daughter influences her complex brother too lightly',
  'son leads the complex of the family',
  'papa simple influence leads the world',
  'grampa simple influence is heavy on his son',
  32,
  'granny inhales failure during wind',
  'mama exhales failure too early during wind',
  'daughter complex failure escapes the wind of her mamas',
  'son complex failure moves during thunder',
  'papa silent thundering failure is ruined in the world',
  'grampa silent failure is ruining his son',
  33,
  'granny silent retreat deep in the mountain',
  'mama silent retreat with her mama',
  'daughter complex retreat away from the mountain',
  'son timely advances to his papas',
  'papa timing is remembered throughout the world',
  'grampa timing is heavenly memory',
  34,
  'granny complex power is blinding',
  'mama complex power is too bright',
  'daughter complex power is outshined by brother',
  'son complex power shines in the family',
  'papa silent power is heavy on the world',
  'grampa silent power is hidden from heaven',
  35,
  'granny silent progress does not change even in the grave',
  'mama silent progress does not change life',
  'daughter inhale progress in changing earth',
  'son exhales progress to change his family',
  'papa inhales worldly changes heavily',
  'grampa exhales change into heaven',
  36,
  'granny simple crisis is too easy in the firebase',
  'mama simple crisis allows the fire to burn on the ground',
  'daughter simple crisis extinguishes the fire',
  'son simple crisis is heavy on the family',
  'papa silent world crisis is heavy on the sky',
  'grampa silent heavenly crisis rejects liberation',
  37,
  'granny simple family escapes her',
  'mama simple family protects her',
  'daughter escapes the simple family',
  'son is stuck in the simple family',
  'papa complex family shines in the world',
  'grampa complex family shines in heaven',
  38,
  'granny complex fight misses the picnic on the lake',
  'mama all too often fights her daughter in the lake',
  'daughter inhales the fight to balance her mamas on the lake',
  'son exhales the firefight for family balance',
  'papa inhales world firefight and is burnt',
  'grampa exhales to heaven any firefight',
  39,
  'granny provokes silence deep in the mountain',
  'mama provokes grounding silence',
  'daughter simple provocation escapes the mountain',
  'son simple provocation opposes his sister escape',
  'papa simple provocation is a bridge over troubled ocean',
  'grampa simple provocation floods the world',
  40,
  'granny inhales family work as hard as ice',
  'mama exhales family work in premature deliverance',
  'daughter inhales family work to repent for her mama',
  'son exhales family work to shine for his papas',
  'papa work in the world is rejected',
  'grampa work is banished from heaven',
  41,
  'granny fantasy time arrives too soon',
  'mama fantasy time arrives only too short',
  'daughter silent fantasy grounds her mamas',
  'son silent fantasy burdens his sister',
  'papa inhale burden of world fantasy',
  'grampa exhale his fantasy up to heaven',
  42,
  'granny simple growth is cut prematurely',
  'mama simple growth is safe and sound',
  'daughter silent growth grounds her mama',
  'son silent growth burdens his sister',
  'papa complex growth enlightens the world',
  'grampa complex growth penetrates heaven',
  43,
  'granny complex insight is too light',
  'mama complex insight is too early',
  'daughter complex insight pushes her brother',
  'son complex insight inspires the family',
  'papa simple insight crosses the world',
  'grampa simple insight is a heavy on his son',
  44,
  'granny is alert to inhale wind slowly',
  'mama is alert and exhales wind too fast ',
  'daughter complex alert escapes the wind',
  'son time alert aspires his family',
  'papa time alert crosses the world  ',
  'grampa time alert goes beyond the universe',
  45,
  'granny is the silent owner of earth',
  'mama is the silent owner of her body',
  'daughter inhales her mamas property',
  'son exhales shines the family ownership',
  'papa simple ownership gathers the world',
  'grampa simple ownership cuts through his sons',
  46,
  'granny determined inhalation balances the wind',
  'mama determined exhalation blows the wind too early',
  'daughter simple determination pushes her brother',
  'son simple determination is heavy on his sister',
  'papa silent determination is a world burden',
  'grampa silent determination is rejected from heaven',
  47,
  'granny oppresses inhalation in deep water',
  'mama oppressed exhalation escapes the water too early',
  'daughter oppressed inhalation on the water surface',
  'son oppressed exhalation is exalted in the family',
  'papa simple realization polishes the world',
  'grampa simple realization is not welcome in heaven',
  48,
  'granny inhales solutions deep into the wind',
  'mama exhales solutions to early into the wind',
  'daughter simple solution in blown by the wind',
  'son simple solution is is dropped on his sister',
  'papa simple solution rides through the ocean',
  'grampa simple solution is banished from heaven',
  49,
  'granny simple principle is a revolution too soon',
  'mama simple principle is a welcomed revolution',
  'daughter complex principle pushes her brother revolution',
  'son complex principle inspires the family revolution',
  'papa simple principle is reflected in world revolution',
  'grampa simple principle is a burden to his son',
  50,
  'granny value is to inhale the wind to ground',
  'mama value is to exhale the wind too early',
  'daughter complex value pushes her brother',
  'son complex value fires through the family',
  'papa inhales world value too heavily',
  'grampa exhales heavenly value',
  51,
  'granny simple shock roars too easily',
  'mama simple shock roars from the ground',
  'daughter inhales shock of mamas roar',
  'son exhales shock inspire family roar',
  'papa silent shock depresses the world',
  'grampa silent shock is banished from heaven',
  52,
  'granny silent meditation serves lifetimes',
  'mama silent meditation serves her life',
  'daughter simple meditation is to escape the mountain',
  'son simple meditation is a burden to his sister',
  'papa inhales mediation to depress the world',
  'grampa exhales meditation to exalt heaven',
  53,
  'granny begins silence deep in the mountain',
  'mama begins silence on the ground ',
  'daughter simple start pushes her brother',
  'son simple start is heavy on his sister',
  'papa complex development begins in the world',
  'grampa complex development begins in heaven',
  54,
  'granny complex ambition drives all too fast',
  'mama complex ambition drives her too early',
  'daughter inhales ambition to balance her mamas',
  'son exhales ambition to inspire his family',
  'papa silent ambition is heavy on the world',
  'grampa silent ambition is rejected from heaven',
  55,
  'granny simple spirit fires too fast',
  'mama simple spirit fires the ground',
  'daughter complex spirit pushes her brother',
  'son complex spirit inspires the family',
  'papa silent spirit is heavy on the world',
  'grampa silent spirit is rejected from heaven',
  56,
  'granny silently wanders the mountain',
  'mama silently wanders on the ground',
  'daughter complex belief pushes her brother',
  'son complex belief inspires the family',
  'papa inhales world belief too seriously',
  'grampa exhales the story of heaven',
  57,
  'granny inhales the wind to the ground',
  'mama exhales the wind too soon',
  'daughter exhales the wind to push her brother',
  'son inhales the wind to depress his sister',
  'papa is gentle through the wind of the world',
  'grampa gentle blow reaches heaven',
  58,
  'granny joy complex is brushed easily',
  'mama joy complex does not serve her',
  'daughter inhales joy to cover her mamas',
  'son exhales joy through family',
  'papa simple joy keeps the world alive',
  'grampa simple joy is rejected from heaven',
  59,
  'granny inhales sexuality through deep water',
  'mama exhales sexuality to disperse water early',
  'daughter silent sexuality is taken from mamas',
  'son silent sexuality is heavy on his sister',
  'papa complex sexuality spreads through the world',
  'grampa complex sexuality spreads through heaven',
  60,
  'granny complex limitation is too strong',
  'mama complex limitation is too early',
  'daughter silent limitation accepts her mama',
  'son silent limitation burdens his sister',
  'papa simple acceptance shines in the world',
  'grampa simple acceptance is rejected by heaven',
  61,
  'granny complex mystery is exposed too much',
  'mama complex mystery is exposed too early',
  'daughter silent truth grounds her mama',
  'son silent truth burdens his sister',
  'papa complex mystery is truth in the world',
  'grampa complex mystery is truth in heaven',
  62,
  'granny silent detail is for lifetimes',
  'mama silent detail serves her',
  'daughter complex detail pushes her brother',
  'son complex detail shines through the family',
  'papa silent detail is a world burden',
  'grampa silent detail is rejected from heaven',
  63,
  'granny simple doubt is all too early',
  'mama simple doubt serves her well',
  'daughter simple doubt pushes her brother',
  'son simple doubt blocks his sister',
  'papa simple doubt inspires the world',
  'grampa simple doubt in heaven rejects him afterlife',
  64,
  'granny inhales confusion into deep water',
  'mama exhales confusion to escape the water early',
  'daughter inhales confusion to ground her mama',
  'son exhales confusing fire to shine in the family',
  'papa inhales confusing fire to burn in the world',
  'grampa exhales fire into heaven before all is done',
];

final List idonotknowOnlylinesList = [
  'granny (modestmother)',
  'mama (mother)',
  'daughter (sister)',
  'son (brother)',
  'papa (father)',
  'grampa (grandfather)',
  'granny complex heavenly creation rejects the ground',
  'mama complex heavenly creation rejects herself from the ground',
  'daughter heavenly creation rejects her from her mothers',
  'son complex heavenly creation inspires creators',
  'papa complex heavenly creation inspires the world',
  'grampa complex heavenly creation inspires heaven',
  'granny silent life is received by earth',
  'mama silent life on earth is received by her',
  'daughter silent life is received by her mamas',
  'son silent life is heavy on his sister',
  'papa silent life is not welcome in the world',
  'grampa silent life is hell',
  'granny simple difference roars away from earth',
  'mama simple difference is a grounded thunder',
  'daughter different roar is silent',
  'son silent difference is pouring to his sister',
  'papa simple difference waters the world',
  'grampa simple difference waters heavy rain',
  'granny inhalation pours grounded answers',
  'mama exhalation pours light answers',
  'daughter silent answer is fluid',
  'son silent answer is mounted on his sister',
  'papa inhalation will mount heavy world answer',
  'grampa exhalation will answer the mountain call to heaven',
  'granny complex waiting will push heaven away from the ground',
  'mama complex waiting will push heaven away from her',
  'daughter simple waiting will push her brother to heaven',
  'son simple waiting will pour burden on his sister',
  'papa simple patience will water the world',
  'grampa simple patience will rain rejection from heaven',
  'granny inhales conflict to preserve water',
  'mama exhales conflict from herself too easily',
  'daughter inhales conflict to clear water',
  'son exhales conflicts away from the family',
  'papa complex conflict enllightens the world',
  'grampa complex conflict open doors to heaven',
  'granny inhales interaction with water deeply',
  'mama exhales her interaction in stale water too soon',
  'daughter silently interacts with her mamas',
  'son silence burdens his interactions with his sister',
  'papa silent interaction burdens worldy interactions',
  'grampa silent interaction makes life as hard as hell',
  'granny contributes to ground most profound silence',
  'mama contributes to establish her grounded silence',
  'daughter silent contribution supports her mama',
  'son silent contribution burdens his sister',
  'papa simple contribution pours rain across world ground',
  'grampa simple contribution floods his legacy',
  'granny complex focus has no ground at all',
  'mama complex focus is not grounded',
  'daughter simple focus is to run away from her mama',
  'son simple focus burdens his sister',
  'papa complex focus is a fresh air to the world',
  'grampa complex focus swirls up to heaven',
  'granny complex behavior by the lake is all too soon',
  'mama complex behavior is all too early for her',
  'daughter inhales proper behavior to support her mama',
  'son exhales his behavior and is rewarded in the family',
  'papa complex behavior saves the world',
  'grampa complex behavior is a model in heaven',
  'granny complex idea shines too brightly',
  'mama complex idea get her to blossom too fast',
  'daughter simple idea is to leave her mama',
  'son simple idea is a burden to his sister',
  'papa silent idea is a heavey in the world',
  'grampa silent idea burdens his legacy',
  'granny silent caution is deeply rooted to ground',
  'mama silent caution protects her',
  'daughter inhales cautiously to support her mama',
  'son exhales cautiously to empower the family ',
  'papa complex standstill empowers the world',
  'grampa complex standstill open the gate to heaven',
  'granny simple secret fires too easily',
  'mama simple secret maintains her fire',
  'daughter complex secret burns her brother',
  'son complex secret shines through the family',
  'papa complex secret shines to the world',
  'grampa complex secret shines up to heaven',
  'granny complex wealth is too much to handle',
  'mama complex wealth is too much for her',
  'daughter complex wealth pushes her brother',
  'son complex wealth fires through the family',
  'papa inhales worldly wealth heavily',
  'grampa exahales wealth that fires to heaven',
  'granny silent modesty is her epitaph of love',
  'mama silent modesty stills love',
  'daughter simple modesty pushes her brother',
  'son simple modesty burdens his sister',
  'papa silent modesty is not loved in the world',
  'grampa silent modesty is not accepted in heaven ',
  'granny silent skill is grounded for lifetimes',
  'mama silent skill grounds her',
  'daughter inhales skill to ground her mama',
  'son exhaled skill is an enthusiasm in the family',
  'papa silent skill is not welcome in the world',
  'grampa silent skill burdens his entire legacy',
  'granny light opinion do not serve her',
  'mama simple opinion grounds her',
  'daughter sound opinion grounds her mamas',
  'son sound opinion follows his papa',
  'papa simple opinion is followed worldwide',
  'grampa simple opinion is hell for his legacy',
  'granny correctly inhales wind',
  'mama incorrectly exhales wind too soon',
  'daughter simple correction is too airy',
  'son simple correction is too mounted',
  'papa breath correction is not mounted worldwide',
  'grampa breath correction is welcome on top of the mountain',
  'granny complex needs do not approach her roots',
  'mama complex needs do not yield to her mama',
  'daughter silent needs repent for her mamas',
  'son silent needs are a burden to his sister',
  'papa silent needs are a burden to his son',
  'grampa silent needs are a burden to his son',
  'granny is silent now all the way to the grave',
  'mama is silent now with her mama',
  'daughter contemplates the female silence',
  'son silent contemplation is not welcome by his sister',
  'papa complex contemplation is worldly known',
  'grampa complex contemplates now in heaven',
  'granny simple control escapes too much',
  'mama simple control grounds her',
  'daughter controlled breath of grounds her mama',
  'son controlled breath is aspired by papa',
  'papa controlled breath is a burden to the world',
  'grampa controlled breath moves in heaven',
  'granny simple grace escapes her',
  'mama simple grace grounds her',
  'daughter simple grace pushes her brother',
  'son simple grace is heavy on his sister',
  'papa gracefully inhale the burden of the world',
  'grampa exhale grace into heaven',
  'granny silent knowing speaks for the earth',
  'mama silent knowing speaks for her',
  'daughter silent knowing supports on her mamas',
  'son silent knowing is heavy on his sister',
  'papa knows to inhale the burden in the world',
  'grampa knows how to exhale up to heaven',
  'granny simple rational thought is too light',
  'mama simple rational thought is considered',
  'daughter silent rational thought supports her mama',
  'son silent rational thought is heavy on his sister',
  'papa silent rational thought is a burden in the world',
  'grampa silent rational thought falls from heaven',
  'granny simple innocence does not ground love',
  'mama simple innocence grounds love',
  'daughter innocent breath grounds her mamas love',
  'son innocent breath aspires family love',
  'papa innocence complex aspires worldly love',
  'grampa innocence complex aspires heavenly love',
  'granny complex trick is exposed too much',
  'mama complex trick is exposed to her daughter',
  'daughter simple trick is to escape her mama',
  'son simple trick is to block his sister',
  'papa inhalation trick is not welcome in the world',
  'grampa exhalation trick is heavenly ',
  'granny simple care is too positive',
  'mama simple care grounds her',
  'daughter silent care grounds her mama',
  'son silent care is heavy on his sister',
  'papa inhales worldly care too heavily',
  'grampa exhales care up to heaven',
  'granny inhale grounded risk',
  'mama premature risk escapes her',
  'daughter complex risk pushes her brother',
  'son complex risk aspires the family',
  'papa simple risk is success in the world ',
  'grampa simple risk is a burden to his son',
  'granny inhalation is persevered in the deep water',
  'mama exhalation do not persevere in mid water',
  'daughter persevere in silent high water',
  'son silent perseverance is a heavy on the family',
  'papa simple swim perseveres through dark clouds',
  'grampa simple swim do not persevere in heaven',
  'granny simple fire is quickly extinguished',
  'mama simple fire is long lasting',
  'daughter complex fire burns her brother',
  'son complex fire lightens the family',
  'papa inhales fire and is burnt in the world',
  'grampa exhaled fire enlightens heavenly bonfire',
  'granny leads silently even in the grave',
  'mama leads silently during life',
  'daughter influences her complex brother too lightly',
  'son leads the complex of the family',
  'papa simple influence leads the world',
  'grampa simple influence is heavy on his son',
  'granny inhales failure during wind',
  'mama exhales failure too early during wind',
  'daughter complex failure escapes the wind of her mamas',
  'son complex failure moves during thunder',
  'papa silent thundering failure is ruined in the world',
  'grampa silent failure is ruining his son',
  'granny silent retreat deep in the mountain',
  'mama silent retreat with her mama',
  'daughter complex retreat away from the mountain',
  'son timely advances to his papas',
  'papa timing is remembered throughout the world',
  'grampa timing is heavenly memory',
  'granny complex power is blinding',
  'mama complex power is too bright',
  'daughter complex power is outshined by brother',
  'son complex power shines in the family',
  'papa silent power is heavy on the world',
  'grampa silent power is hidden from heaven',
  'granny silent progress does not change even in the grave',
  'mama silent progress does not change life',
  'daughter inhale progress in changing earth',
  'son exhales progress to change his family',
  'papa inhales worldly changes heavily',
  'grampa exhales change into heaven',
  'granny simple crisis is too easy in the firebase',
  'mama simple crisis allows the fire to burn on the ground',
  'daughter simple crisis extinguishes the fire',
  'son simple crisis is heavy on the family',
  'papa silent world crisis is heavy on the sky',
  'grampa silent heavenly crisis rejects liberation',
  'granny simple family escapes her',
  'mama simple family protects her',
  'daughter escapes the simple family',
  'son is stuck in the simple family',
  'papa complex family shines in the world',
  'grampa complex family shines in heaven',
  'granny complex fight misses the picnic on the lake',
  'mama all too often fights her daughter in the lake',
  'daughter inhales the fight to balance her mamas on the lake',
  'son exhales the firefight for family balance',
  'papa inhales world firefight and is burnt',
  'grampa exhales to heaven any firefight',
  'granny provokes silence deep in the mountain',
  'mama provokes grounding silence',
  'daughter simple provocation escapes the mountain',
  'son simple provocation opposes his sister escape',
  'papa simple provocation is a bridge over troubled ocean',
  'grampa simple provocation floods the world',
  'granny inhales family work as hard as ice',
  'mama exhales family work in premature deliverance',
  'daughter inhales family work to repent for her mama',
  'son exhales family work to shine for his papas',
  'papa work in the world is rejected',
  'grampa work is banished from heaven',
  'granny fantasy time arrives too soon',
  'mama fantasy time arrives only too short',
  'daughter silent fantasy grounds her mamas',
  'son silent fantasy burdens his sister',
  'papa inhale burden of world fantasy',
  'grampa exhale his fantasy up to heaven',
  'granny simple growth is cut prematurely',
  'mama simple growth is safe and sound',
  'daughter silent growth grounds her mama',
  'son silent growth burdens his sister',
  'papa complex growth enlightens the world',
  'grampa complex growth penetrates heaven',
  'granny complex insight is too light',
  'mama complex insight is too early',
  'daughter complex insight pushes her brother',
  'son complex insight inspires the family',
  'papa simple insight crosses the world',
  'grampa simple insight is a heavy on his son',
  'granny is alert to inhale wind slowly',
  'mama is alert and exhales wind too fast ',
  'daughter complex alert escapes the wind',
  'son time alert aspires his family',
  'papa time alert crosses the world  ',
  'grampa time alert goes beyond the universe',
  'granny is the silent owner of earth',
  'mama is the silent owner of her body',
  'daughter inhales her mamas property',
  'son exhales shines the family ownership',
  'papa simple ownership gathers the world',
  'grampa simple ownership cuts through his sons',
  'granny determined inhalation balances the wind',
  'mama determined exhalation blows the wind too early',
  'daughter simple determination pushes her brother',
  'son simple determination is heavy on his sister',
  'papa silent determination is a world burden',
  'grampa silent determination is rejected from heaven',
  'granny oppresses inhalation in deep water',
  'mama oppressed exhalation escapes the water too early',
  'daughter oppressed inhalation on the water surface',
  'son oppressed exhalation is exalted in the family',
  'papa simple realization polishes the world',
  'grampa simple realization is not welcome in heaven',
  'granny inhales solutions deep into the wind',
  'mama exhales solutions to early into the wind',
  'daughter simple solution in blown by the wind',
  'son simple solution is is dropped on his sister',
  'papa simple solution rides through the ocean',
  'grampa simple solution is banished from heaven',
  'granny simple principle is a revolution too soon',
  'mama simple principle is a welcomed revolution',
  'daughter complex principle pushes her brother revolution',
  'son complex principle inspires the family revolution',
  'papa simple principle is reflected in world revolution',
  'grampa simple principle is a burden to his son',
  'granny value is to inhale the wind to ground',
  'mama value is to exhale the wind too early',
  'daughter complex value pushes her brother',
  'son complex value fires through the family',
  'papa inhales world value too heavily',
  'grampa exhales heavenly value',
  'granny simple shock roars too easily',
  'mama simple shock roars from the ground',
  'daughter inhales shock of mamas roar',
  'son exhales shock inspire family roar',
  'papa silent shock depresses the world',
  'grampa silent shock is banished from heaven',
  'granny silent meditation serves lifetimes',
  'mama silent meditation serves her life',
  'daughter simple meditation is to escape the mountain',
  'son simple meditation is a burden to his sister',
  'papa inhales mediation to depress the world',
  'grampa exhales meditation to exalt heaven',
  'granny begins silence deep in the mountain',
  'mama begins silence on the ground ',
  'daughter simple start pushes her brother',
  'son simple start is heavy on his sister',
  'papa complex development begins in the world',
  'grampa complex development begins in heaven',
  'granny complex ambition drives all too fast',
  'mama complex ambition drives her too early',
  'daughter inhales ambition to balance her mamas',
  'son exhales ambition to inspire his family',
  'papa silent ambition is heavy on the world',
  'grampa silent ambition is rejected from heaven',
  'granny simple spirit fires too fast',
  'mama simple spirit fires the ground',
  'daughter complex spirit pushes her brother',
  'son complex spirit inspires the family',
  'papa silent spirit is heavy on the world',
  'grampa silent spirit is rejected from heaven',
  'granny silently wanders the mountain',
  'mama silently wanders on the ground',
  'daughter complex belief pushes her brother',
  'son complex belief inspires the family',
  'papa inhales world belief too seriously',
  'grampa exhales the story of heaven',
  'granny inhales the wind to the ground',
  'mama exhales the wind too soon',
  'daughter exhales the wind to push her brother',
  'son inhales the wind to depress his sister',
  'papa is gentle through the wind of the world',
  'grampa gentle blow reaches heaven',
  'granny joy complex is brushed easily',
  'mama joy complex does not serve her',
  'daughter inhales joy to cover her mamas',
  'son exhales joy through family',
  'papa simple joy keeps the world alive',
  'grampa simple joy is rejected from heaven',
  'granny inhales sexuality through deep water',
  'mama exhales sexuality to disperse water early',
  'daughter silent sexuality is taken from mamas',
  'son silent sexuality is heavy on his sister',
  'papa complex sexuality spreads through the world',
  'grampa complex sexuality spreads through heaven',
  'granny complex limitation is too strong',
  'mama complex limitation is too early',
  'daughter silent limitation accepts her mama',
  'son silent limitation burdens his sister',
  'papa simple acceptance shines in the world',
  'grampa simple acceptance is rejected by heaven',
  'granny complex mystery is exposed too much',
  'mama complex mystery is exposed too early',
  'daughter silent truth grounds her mama',
  'son silent truth burdens his sister',
  'papa complex mystery is truth in the world',
  'grampa complex mystery is truth in heaven',
  'granny silent detail is for lifetimes',
  'mama silent detail serves her',
  'daughter complex detail pushes her brother',
  'son complex detail shines through the family',
  'papa silent detail is a world burden',
  'grampa silent detail is rejected from heaven',
  'granny simple doubt is all too early',
  'mama simple doubt serves her well',
  'daughter simple doubt pushes her brother',
  'son simple doubt blocks his sister',
  'papa simple doubt inspires the world',
  'grampa simple doubt in heaven rejects him afterlife',
  'granny inhales confusion into deep water',
  'mama exhales confusion to escape the water early',
  'daughter inhales confusion to ground her mama',
  'son exhales confusion to shine through the family',
  'papa inhales a confused world too seriously',
  'grampa exhales heaven before all is completed',
];

List reversedidkonlylinesList = idonotknowOnlylinesList.reversed.toList();


// NOT IN USE

// iching wilhelm
final List iChinglinesList = [
  0,
  'six :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  1,
  'nine :: Hidden dragon. Do Not act.',
  'nine :: Dragon appears in the field. It furthers one to see the great man.',
  'nine :: All day long the superior man is creatively active. At nightfall his mind is still beset with cares. Danger. No blame.',
  'nine :: Wavering flight over the depths. No blame',
  'nine :: Flying dragon in the heavens. It furthers one to see the great man.',
  'nine :: Arrogant dragon will have cause to repent.',
  2,
  'six :: When there is hoarfrost underfoot, solid ice is not far off.',
  'six :: Straight, square, great. Without purpose, yet nothing remains unfurthered.',
  'six :: Hidden lines. One is able to remain persevering. If by chance you are in the service of a king, seek not works, but bring to completion.',
  'six :: A tied-up sack. No blame, no praise.',
  'six :: A yellow lower garment brings supreme good fortune.',
  'six :: Dragons fight in the meadow. Their blood is black and yellow.',
  3,
  'nine :: Hesitation and hindrance. It furthers one to remain persevering. It furthers one to appoint helpers.',
  'six :: Difficulties pile up. Horse and wagon part. He is not a robber, he wants to woo when the time comes. The maiden is chaste, she does not pledge herself. Ten years - then she pledges herself.',
  'six :: Whoever hunts deer without the forester only loses his way in the forest. The superior man understands the signs of the time and prefers to desist. To go on is humiliation.',
  'six :: Horse and wagon part. Strive for union. To go brings good fortune.',
  'nine :: Difficulties in blessing. A little perseverance brings good fortune. Great perseverance brings misfortune.',
  'six :: Horse and wagon part. Bloody tears flow.',
  4,
  'six :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  5,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  6,
  'six :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  7,
  'six :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  8,
  'six :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  9,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  10,
  'nine :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  11,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  12,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  13,
  'nine :: meaning.',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  14,
  'nine :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  15,
  'six :: meaning.',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  16,
  'six :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  17,
  'nine :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  18,
  'six :: meaning.',
  'nine :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  19,
  'nine :: meaning.',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  20,
  'six :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'nine :: meaning',
  21,
  'nine :: meaning.',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'nine :: meaning',
  22,
  'nine :: meaning.',
  'six :: meaning',
  'nine :: meaning',
  'six :: meaning',
  'six :: meaning',
  'nine :: meaning',
  23,
  'granny silent knowing speaks for itself',
  'mama speaks through silent knowing',
  'daughter silent knowing is heavy on her mamas',
  'son silent knowing is heavy on his sister',
  'papa knows inhalation is a burden in the world',
  'grampa knows exhalation is exalted in the beyond',
  24,
  'granny simple rational thought is too light',
  'mama simple rational thought is considered',
  'daughter silent rational thought supports her mama',
  'son silent rational thought is heavy on his sister',
  'papa silent rational thought is a burden in the world',
  'grampa silent rational thought falls from heaven',
  25,
  'granny simple innocence does not ground love',
  'mama simple innocence grounds love',
  'daughter innocent breath grounds her mamas love',
  'son innocent breath aspires family love',
  'papa innocence complex aspires worldly love',
  'grampa innocence complex aspires heavenly love',
  26,
  'granny complex trick is exposed too much',
  'mama complex trick is exposed to her daughter',
  'daughter simple trick escapes her mamas',
  'son simple trick block his sister',
  'papa breath trick is not welcome in the world',
  'grampa breath trick is heavenly ',
  27,
  'granny simple care is too positive',
  'mama simple care grounds her',
  'daughter silent care grounds her mama',
  'son silent care is heavy on his sister',
  'papa inhales worldly care too heavily',
  'grampa exhales care up to heaven',
  28,
  'granny inhale grounded risk',
  'mama premature risk escapes her',
  'daughter complex risk pushes her brother',
  'son complex risk aspires the family',
  'papa simple risk is success in the world ',
  'grampa simple risk is a burden to his son',
  29,
  'granny inhalation is persevered in the deep water',
  'mama exhalation do not persevere in mid water',
  'daughter persevere in silent high water',
  'son silent perseverance is a heavy on the family',
  'papa simple swim perseveres through dark clouds',
  'grampa simple swim do not persevere in heaven',
  30,
  'granny simple fire is quickly extinguished',
  'mama simple fire is long lasting',
  'daughter complex fire burns her brother',
  'son complex fire lightens the family',
  'papa inhales fire and is burnt in the world',
  'grampa exhaled fire enlightens heavenly bonfire',
  31,
  'granny leads silently even in the grave',
  'mama leads silently during life',
  'daughter influences her complex brother too lightly',
  'son leads the complex of the family',
  'papa simple influence leads the world',
  'grampa simple influence is heavy on his son',
  32,
  'granny inhales failure during wind',
  'mama exhales failure too early during wind',
  'daughter complex failure escapes the wind of her mamas',
  'son complex failure moves during thunder',
  'papa silent thundering failure is ruined in the world',
  'grampa silent failure is ruining his son',
  33,
  'granny silent retreat deep in the mountain',
  'mama silent retreat with her mama',
  'daughter complex retreat away from the mountain',
  'son timely advances to his papas',
  'papa timing is remembered throughout the world',
  'grampa timing is heavenly memory',
  34,
  'granny complex power is blinding',
  'mama complex power is too bright',
  'daughter complex power is outshined by brother',
  'son complex power shines in the family',
  'papa silent power is heavy on the world',
  'grampa silent power is hidden from heaven',
  35,
  'granny silent progress does not change even in the grave',
  'mama silent progress does not change life',
  'daughter inhale progress in changing earth',
  'son exhales progress to change his family',
  'papa inhales worldly changes heavily',
  'grampa exhales change into heaven',
  36,
  'granny simple crisis is too easy in the firebase',
  'mama simple crisis allows the fire to burn on the ground',
  'daughter simple crisis extinguishes the fire',
  'son simple crisis is heavy on the family',
  'papa silent world crisis is heavy on the sky',
  'grampa silent heavenly crisis rejects liberation',
  37,
  'granny simple family escapes her',
  'mama simple family protects her',
  'daughter escapes the simple family',
  'son is stuck in the simple family',
  'papa complex family shines in the world',
  'grampa complex family shines in heaven',
  38,
  'granny complex fight misses the picnic on the lake',
  'mama all too often fights her daughter in the lake',
  'daughter inhales the fight to balance her mamas on the lake',
  'son exhales the firefight for family balance',
  'papa inhales world firefight and is burnt',
  'grampa exhales to heaven any firefight',
  39,
  'granny provokes silence deep in the mountain',
  'mama provokes grounding silence',
  'daughter simple provocation escapes the mountain',
  'son simple provocation opposes his sister escape',
  'papa simple provocation is a bridge over troubled ocean',
  'grampa simple provocation floods the world',
  40,
  'granny inhales family work as hard as ice',
  'mama exhales family work in premature deliverance',
  'daughter inhales family work to repent for her mama',
  'son exhales family work to shine for his papas',
  'papa work in the world is rejected',
  'grampa work is banished from heaven',
  41,
  'granny fantasy time arrives too soon',
  'mama fantasy time arrives only too short',
  'daughter silent fantasy grounds her mamas',
  'son silent fantasy burdens his sister',
  'papa inhale burden of world fantasy',
  'grampa exhale his fantasy up to heaven',
  42,
  'granny simple growth is cut prematurely',
  'mama simple growth is safe and sound',
  'daughter silent growth grounds her mama',
  'son silent growth burdens his sister',
  'papa complex growth enlightens the world',
  'grampa complex growth penetrates heaven',
  43,
  'granny complex insight is too light',
  'mama complex insight is too early',
  'daughter complex insight pushes her brother',
  'son complex insight inspires the family',
  'papa simple insight crosses the world',
  'grampa simple insight is a heavy on his son',
  44,
  'granny is alert to inhale wind slowly',
  'mama is alert and exhales wind too fast ',
  'daughter complex alert escapes the wind',
  'son time alert aspires his family',
  'papa time alert crosses the world  ',
  'grampa time alert goes beyond the universe',
  45,
  'granny is the silent owner of earth',
  'mama is the silent owner of her body',
  'daughter inhales her mamas property',
  'son exhales shines the family ownership',
  'papa simple ownership gathers the world',
  'grampa simple ownership cuts through his sons',
  46,
  'granny determined inhalation balances the wind',
  'mama determined exhalation blows the wind too early',
  'daughter simple determination pushes her brother',
  'son simple determination is heavy on his sister',
  'papa silent determination is a world burden',
  'grampa silent determination is rejected from heaven',
  47,
  'granny oppresses inhalation in deep water',
  'mama oppressed exhalation escapes the water too early',
  'daughter oppressed inhalation on the water surface',
  'son oppressed exhalation is exalted in the family',
  'papa simple realization polishes the world',
  'grampa simple realization is not welcome in heaven',
  48,
  'granny inhales solutions deep into the wind',
  'mama exhales solutions to early into the wind',
  'daughter simple solution in blown by the wind',
  'son simple solution is is dropped on his sister',
  'papa simple solution rides through the ocean',
  'grampa simple solution is banished from heaven',
  49,
  'granny simple principle is a revolution too soon',
  'mama simple principle is a welcomed revolution',
  'daughter complex principle pushes her brother revolution',
  'son complex principle inspires the family revolution',
  'papa simple principle is reflected in world revolution',
  'grampa simple principle is a burden to his son',
  50,
  'granny value is to inhale the wind to ground',
  'mama value is to exhale the wind too early',
  'daughter complex value pushes her brother',
  'son complex value fires through the family',
  'papa inhales world value too heavily',
  'grampa exhales heavenly value',
  51,
  'granny simple shock roars too easily',
  'mama simple shock roars from the ground',
  'daughter inhales shock of mamas roar',
  'son exhales shock inspire family roar',
  'papa silent shock depresses the world',
  'grampa silent shock is banished from heaven',
  52,
  'granny silent meditation serves lifetimes',
  'mama silent meditation serves her life',
  'daughter simple meditation is to escape the mountain',
  'son simple meditation is a burden to his sister',
  'papa inhales mediation to depress the world',
  'grampa exhales meditation to exalt heaven',
  53,
  'granny begins silence deep in the mountain',
  'mama begins silence on the ground ',
  'daughter simple start pushes her brother',
  'son simple start is heavy on his sister',
  'papa complex development begins in the world',
  'grampa complex development begins in heaven',
  54,
  'granny complex ambition drives all too fast',
  'mama complex ambition drives her too early',
  'daughter inhales ambition to balance her mamas',
  'son exhales ambition to inspire his family',
  'papa silent ambition is heavy on the world',
  'grampa silent ambition is rejected from heaven',
  55,
  'granny simple spirit fires too fast',
  'mama simple spirit fires the ground',
  'daughter complex spirit pushes her brother',
  'son complex spirit inspires the family',
  'papa silent spirit is heavy on the world',
  'grampa silent spirit is rejected from heaven',
  56,
  'granny silently wanders the mountain',
  'mama silently wanders on the ground',
  'daughter complex belief pushes her brother',
  'son complex belief inspires the family',
  'papa inhales world belief too seriously',
  'grampa exhales the story of heaven',
  57,
  'granny inhales the wind to the ground',
  'mama exhales the wind too soon',
  'daughter exhales the wind to push her brother',
  'son inhales the wind to depress his sister',
  'papa is gentle through the wind of the world',
  'grampa gentle blow reaches heaven',
  58,
  'granny joy complex is brushed easily',
  'mama joy complex does not serve her',
  'daughter inhales joy to cover her mamas',
  'son exhales joy through family',
  'papa simple joy keeps the world alive',
  'grampa simple joy is rejected from heaven',
  59,
  'granny inhales sexuality through deep water',
  'mama exhales sexuality to disperse water early',
  'daughter silent sexuality is taken from mamas',
  'son silent sexuality is heavy on his sister',
  'papa complex sexuality spreads through the world',
  'grampa complex sexuality spreads through heaven',
  60,
  'granny complex limitation is too strong',
  'mama complex limitation is too early',
  'daughter silent limitation accepts her mama',
  'son silent limitation burdens his sister',
  'papa simple acceptance shines in the world',
  'grampa simple acceptance is rejected by heaven',
  61,
  'granny complex mystery is exposed too much',
  'mama complex mystery is exposed too early',
  'daughter silent truth grounds her mama',
  'son silent truth burdens his sister',
  'papa complex mystery is truth in the world',
  'grampa complex mystery is truth in heaven',
  62,
  'granny silent detail is for lifetimes',
  'mama silent detail serves her',
  'daughter complex detail pushes her brother',
  'son complex detail shines through the family',
  'papa silent detail is a world burden',
  'grampa silent detail is rejected from heaven',
  63,
  'granny simple doubt is all too early',
  'mama simple doubt serves her well',
  'daughter simple doubt pushes her brother',
  'son simple doubt blocks his sister',
  'papa simple doubt inspires the world',
  'grampa simple doubt in heaven rejects him afterlife',
  64,
  'granny inhales confusion into deep water',
  'mama exhales confusion to escape the water early',
  'daughter inhales confusion to ground her mama',
  'son exhales confusion to shine through the family',
  'papa inhales a confused world too seriously',
  'grampa exhales heaven before all is completed',
];

// NOT IN USE

// Human Design Ra Uru Hu
final List hdlinesList = [
  0,
  '+1 :: planet :: sentence.',
  '-1 :: planet :: sentence.',
  '+2 :: planet :: sentence.',
  '-2 :: planet :: sentence.',
  '+3 :: planet :: sentence.',
  '-3 :: planet :: sentence.',
  '+4 :: planet :: sentence.',
  '-4 :: planet :: sentence.',
  '+5 :: planet :: sentence.',
  '-5 :: planet :: sentence.',
  '+6 :: planet :: sentence.',
  '-6 :: planet :: sentence.',
  1,
  '+1 :: moon :: the moon exalted as a symbol of adaptation. Time is everything. Self Expression which has its special timing.',
  '-1 :: uranus :: instability leads to distortion. Here, patience is a virtue and revolution a vice. Creative instability unless there is patience.',
  '+2 :: venus :: venus exalted as a symbol of beauty. The required harmony between established values and ideals that enriches inspiration. Self Expression conditioned by ideals and values.',
  '-2 :: mars :: desires and passions have their place but not at the expense of Creation. Self Expression limited by desires and passions.',
  '+3 :: mars :: mars exalted as the symbol of the profound need for Self Expression. The deep need for Self Expression.',
  '-3 :: earth :: material forces can disrupt creatively and lead to overambition. Materialism disrupts creativity.'
      '+4 :: earth :: the earth as a symbol of personal perspective manifested outside of influence, where the potential magic of inspiration is diluted. Creativity that must develop outside of influence.',
  '-4 :: jupiter :: where the potential magic of inspiration is diluted. The need to influence that abandons aloneness and limits creativity.',
  '+5 :: mars :: mars exalted for its powerful ego endurance. The power and drive to stay with the Creative process.',
  '-5 :: uranus :: uranus in detriment, where eccentricity can handicap endurance. Eccentricity that though attractive will limit the drive.',
  '+6 :: earth :: clear assessment of creative value. Clarity on Creative expression.',
  '-6 :: pluto :: the risk that subjective appraisal will result in disappointment and creative frustration. Subjectivity in Self Expression that may lead to Creative frustration.',
  2,
  '+1 :: venus :: the importance of aesthetics whether inborn or acquired. Higher knowing through aesthetics.',
  '-1 :: mars :: the assertion of ego in spite of wisdom. The urge for action the will ignore the wisdom of the Higher Self.',
  '+2 :: saturn :: the inner strength to focus and realize. A natural gift for unlearnable knowing.',
  '-2 :: mars :: Genius as madness. Knowledge exclusively as power for the enhancement of the ego. The delusion that knowledge is power.',
  '+3 :: jupiter :: dedication to a lifetime of receptivity with the maturity to accept that the process never ends. When connected permanently to gate 14 through the Beat Channel, rewards for services rendered. The recognition that receptivity is a lifelong process.',
  '-3 :: uranus :: for the revolutionary patience is a vice. Higher Knowing that cannot wait and demands expression.',
  '+4 :: venus :: the Higher goal transcends personal acclaim. The team player, acknowledged as the leader but never the captain. Where Higher Knowing does not have to be expressed to be recognized.',
  '-4 :: mars :: loose lips sink ships. The unquenchable fire of the ego engenders enmity. The inability to keep silent when the opportunity arises for expression.',
  '+5 :: mercury :: the strategist with mercury exalted. Reasoned management of resources. Higher Knowing as a gift for strategy.',
  '-5 :: earth :: the inability to share responsibility or recognize the abilities of others. Higher Knowing as an exclusively individual and selfish process.',
  '+6 :: mercury :: with mercury exalted, less negative, thought the intellect becomes absorbed in constant rationalization. Higher Knowing is extremely narrow in its receptivity.',
  '-6 :: saturn :: the need for security may distort awareness to its ultimate perversion, destructiveness. The Higher Self absorbed with the mundane and the need for security.',
  3,
  '+1 :: earth :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  4,
  '+1 :: moon :: sentence.',
  '-1 :: earth :: sentence.',
  '+2 :: moon :: sentence.',
  '-2 :: mars :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: sun :: sentence.',
  '-4 :: saturn :: sentence.',
  '+5 :: jupiter :: sentence.',
  '-5 :: pluto :: sentence.',
  '+6 :: mercury :: sentence.',
  '-6 :: mars :: sentence.',
  5,
  '+1 :: mars :: sentence.',
  '-1 :: earth :: sentence.',
  '+2 :: venus :: sentence.',
  '-2 :: pluto :: sentence.',
  '+3 :: neptune :: sentence.',
  '-3 :: moon :: sentence.',
  '+4 :: uranus :: sentence.',
  '-4 :: sun :: sentence.',
  '+5 :: venus :: sentence.',
  '-5 :: pluto :: sentence.',
  '+6 :: neptune :: sentence.',
  '-6 :: none :: sentence.',
  6,
  '+1 :: pluto :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: venus :: sentence.',
  '-2 :: mars :: sentence.',
  '+3 :: neptune :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: sun :: sentence.',
  '-4 :: pluto :: sentence.',
  '+5 :: venus :: sentence.',
  '-5 :: moon :: sentence.',
  '+6 :: mercury :: sentence.',
  '-6 :: venus :: sentence.',
  7,
  '+1 :: venus :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: neptune :: sentence.',
  '-2 :: mercury :: sentence.',
  '+3 :: moon :: sentence.',
  '-3 :: mercury :: sentence.',
  '+4 :: sun :: sentence.',
  '-4 :: uranus :: sentence.',
  '+5 :: venus :: sentence.',
  '-5 :: neptune :: sentence.',
  '+6 :: mercury :: sentence.',
  '-6 :: uranus :: sentence.',
  8,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  9,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  10,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  11,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  12,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  13,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  14,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  15,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  16,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  17,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  18,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  19,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  20,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  21,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  22,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  23,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  24,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  25,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  26,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  27,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  28,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  29,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  30,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  31,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  32,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  33,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  34,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  35,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  36,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  37,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  38,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  39,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  40,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  41,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  42,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  43,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  44,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  45,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  46,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  47,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  48,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  49,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  50,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  51,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  52,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  53,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  54,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  55,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  56,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  57,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  58,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  59,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  60,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  61,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  62,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  63,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
  64,
  '+1 :: PLANET :: sentence.',
  '-1 :: mercury :: sentence.',
  '+2 :: mars :: sentence.',
  '-2 :: uranus :: sentence.',
  '+3 :: venus :: sentence.',
  '-3 :: pluto :: sentence.',
  '+4 :: neptune :: sentence.',
  '-4 :: mars :: sentence.',
  '+5 :: mars :: sentence.',
  '-5 :: earth :: sentence.',
  '+6 :: sun :: sentence.',
  '-6 :: pluto :: sentence.',
];

final List comparedLinesList = [
  0,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  1,
  'least positive',
  'less positive',
  'is not positive',
  'is positive',
  'more positive',
  'most positive',
  43,
  'least positive',
  'less positive',
  'is not positive',
  'is positive',
  'more positive',
  'most negative',
  14,
  'least positive',
  'less positive',
  'is not positive',
  'is positive',
  'more positive',
  'most negative',
  34,
  'least positive',
  'less positive',
  'is not positive',
  'is positive',
  'more negative',
  'most negative',
  9,
  'least positive',
  'less positive',
  'is not positive',
  'is negative',
  'more positive',
  'most positive',
  5,
  'least positive',
  'less positive',
  'is not positive',
  'is negative',
  'more positive',
  'most negative',
  26,
  'least positive',
  'less positive',
  'is not positive',
  'is negative',
  'more negative',
  'most positive',
  11,
  'least positive',
  'less positive',
  'is not positive',
  'is negative',
  'more negative',
  'most negative',
  10,
  'least positive',
  'less positive',
  'is not negative',
  'is positive',
  'more positive',
  'most positive',
  58,
  'least positive',
  'less positive',
  'is not negative',
  'is positive',
  'more positive',
  'most negative',
  38,
  'least positive',
  'less positive',
  'is not negative',
  'is positive',
  'more negative',
  'most positive',
  54,
  'least positive',
  'less positive',
  'is not negative',
  'is positive',
  'more negative',
  'most negative',
  61,
  'least positive',
  'less positive',
  'is not negative',
  'is negative',
  'more positive',
  'most positive',
  60,
  'least positive',
  'less positive',
  'is not negative',
  'is negative',
  'more positive',
  'most negative',
  41,
  'least positive',
  'less positive',
  'is not negative',
  'is negative',
  'more negative',
  'most positive',
  19,
  'least positive',
  'less positive',
  'is not negative',
  'is negative',
  'more negative',
  'most negative',
  13,
  'least positive',
  'less negative',
  'is not positive',
  'is positive',
  'more positive',
  'most positive',
  49,
  'least positive',
  'less negative',
  'is not positive',
  'is',
  'more positive',
  'most negative',
  30,
  'least positive',
  'less negative',
  'is not positive',
  'is',
  'more negative',
  'most positive',
  55,
  'least positive',
  'less negative',
  'is not positive',
  'is',
  'more negative',
  'most negative',
  37,
  'least positive',
  'less negative',
  'is not positive',
  'is',
  'more positive',
  'most positive',
  63,
  'least positive',
  'less negative',
  'is not positive',
  'is',
  'more positive',
  'most negative',
  22,
  'least positive',
  'less negative',
  'is not positive',
  'is',
  'more negative',
  'most positive',
  36,
  'least positive',
  'less negative',
  'is not positive',
  'is',
  'more negative',
  'most negative',
  25,
  'least positive',
  'less negative',
  'is not negative',
  'is',
  'more positive',
  'most positive',
  17,
  'least positive',
  'less negative',
  'is not negative',
  'is',
  'more positive',
  'most negative',
  21,
  'least positive',
  'less negative',
  'is not negative',
  'is',
  'more negative',
  'most positive',
  51,
  'least positive',
  'less negative',
  'is not negative',
  'is',
  'more negative',
  'most negative',
  42,
  'least positive',
  'less negative',
  'is not negative',
  'is',
  'more positive',
  'most positive',
  3,
  'least positive',
  'less negative',
  'is not negative',
  'is',
  'more positive',
  'most negative',
  27,
  'least positive',
  'less negative',
  'is not negative',
  'is',
  'more negative',
  'most positive',
  24,
  'least positive',
  'less negative',
  'is not negative',
  'is',
  'more negative',
  'most negative',
  44,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  28,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  32,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  50,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  57,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  48,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  18,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  46,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  6,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  47,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  64,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  40,
  'granny is the silent owner of earth',
  'mama is the silent owner of her body',
  'daughter inhales her mamas property',
  'son exhales shines the family ownership',
  'more negative',
  'most negative',
  59,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  29,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  4,
  'least',
  'less',
  'is not',
  'is',
  'more',
  'most',
  7,
  'least',
  'less',
  'is not',
  'is',
  'more negative',
  'most negative',
  33,
  'least negative',
  'less negative',
  'is not',
  'is',
  'more negative',
  'most negative',
  31,
  'least negative',
  'less negative',
  'is not',
  'is',
  'more negative',
  'most negative',
  56,
  'least negative',
  'less negative',
  'is not',
  'is',
  'more negative',
  'most negative',
  62,
  'least negative',
  'less negative',
  'is not',
  'is',
  'more negative',
  'most negative',
  53,
  'least negative',
  'less negative',
  'is not',
  'is',
  'more negative',
  'most negative',
  39,
  'least negative',
  'less negative',
  'is not',
  'is',
  'more negative',
  'most negative',
  52,
  'least negative',
  'less negative',
  'is not',
  'is',
  'more negative',
  'most negative',
  15,
  'least negative',
  'less negative',
  'is not',
  'is',
  'more negative',
  'most negative',
  12,
  'least negative',
  'less negative',
  'is not negative',
  'is',
  'more negative',
  'most negative',
  45,
  'least negative',
  'less negative',
  'is not negative',
  'is',
  'more negative',
  'most negative',
  35,
  'least negative',
  'less negative',
  'is not negative',
  'is',
  'more negative',
  'most negative',
  16,
  'least negative',
  'less negative',
  'is not negative',
  'is',
  'more negative',
  'most negative',
  20,
  'least negative',
  'less negative',
  'is not negative',
  'is negative',
  'more negative',
  'most negative',
  8,
  'least negative',
  'less negative',
  'is not negative',
  'is negative',
  'more negative',
  'most negative',
  23,
  'least negative',
  'less negative',
  'is not negative',
  'is negative',
  'more negative',
  'most negative',
  2,
  'least negative',
  'less negative',
  'is not negative',
  'is negative',
  'more negative',
  'most negative',
];