import 'package:flutter/material.dart';

const String maintitleEN = 'Rotation Time',
    language = 'ENGLISH';

final List<String> languagesList = [
  "English",
  "עברית"
];


final List<String> languagesCodeList = [
  "EN",
  "HE"
];

final List<String> titlesEN = [
  'One Hexagram',
  'Language is Hexagram',
  'Table Hexagram',
  'Atro Planets',
  'HD Chart',
];

final List<String> planetsfullList = [
  'assets/planets/northnode.png',
  'assets/planets/sun.png',
  'assets/planets/moon.png',
  'assets/planets/mercury.png',
  'assets/planets/venus.png',
  'assets/planets/mars.png',
  'assets/planets/jupiter.png',
  'assets/planets/saturn.png',
  'assets/planets/uranus.png',
  'assets/planets/neptune.png',
  'assets/planets/pluto.png',
  'assets/planets/earth.png',
  'assets/planets/southnode.png',
];

final List<String> planetspartialList = [
  'assets/planets/sun.png',
  'assets/planets/earth.png',
  'assets/planets/moon.png',
  'assets/planets/mercury.png',
  'assets/planets/venus.png',
  'assets/planets/mars.png',
  'assets/planets/jupiter.png',
  'assets/planets/saturn.png',
  'assets/planets/uranus.png',
  'assets/planets/neptune.png',
  'assets/planets/pluto.png',
];

final List<String> planetsNamesList = [
  'SUN',
  'EARTH',
  'MOON',
  'MERCURY',
  'VENUS',
  'MARS',
  'JUPITER',
  'SATURN',
  'URANUS',
  'NEPTUNE',
  'PLUTO',
];

final List<String> planetsCrossList = [
  'assets/planets/northnode.png',
  'assets/planets/sun.png',
  'assets/planets/earth.png',
  'assets/planets/southnode.png',
];

final List<String> hexList = [
  'assets/complexup.png',
  'assets/simplein.png',
  'assets/breathout.png',
  'assets/silencedown.png',
];

final List<String> fontHexOrderList = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '!',
  '@',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z'
];

final List<int> fontHexNumbersList = [
  1,
  44,
  13,
  10,
  9,
  14,
  43,
  33,
  25,
  61,
  26,
  34,
  6,
  37,
  38,
  5,
  57,
  30,
  58,
  50,
  49,
  28,
  12,
  42,
  41,
  11,
  62,
  45,
  29,
  39,
  40,
  24,
  7,
  15,
  16,
  8,
  23,
  2,
  59,
  22,
  54,
  53,
  21,
  60,
  18,
  55,
  56,
  17,
  32,
  31,
  47,
  48,
  63,
  64,
  20,
  27,
  19,
  4,
  36,
  52,
  51,
  35,
  3,
  46
];

final List<int> orderHexagramsWheel = [
  //qurater mutation complex
  1, 43, 14, 34,
  9, 5, 26, 11,
  10, 58, 38, 54,
  61, 60, 41, 19,

  //quarter initation simple
  13, 49, 30, 55,
  37, 63, 22, 36,
  25, 17, 21, 51,
  42, 3, 27, 24,

  //quarter civilization silence
  2, 23, 8, 20,
  16, 35, 45, 12,
  15, 52, 39, 53,
  62, 56, 31, 33,

  //quarter duality breath
  7, 4, 29, 59,
  40, 64, 47, 6,
  46, 18, 48, 57,
  32, 50, 28, 44,
];

final List<int> orderHexagramsToCalulateWheel = [
  //qurater mutation complex
  41, 19,

  //quarter initation simple
  13, 49, 30, 55,
  37, 63, 22, 36,
  25, 17, 21, 51,
  42, 3, 27, 24,

  //quarter civilization silence
  2, 23, 8, 20,
  16, 35, 45, 12,
  15, 52, 39, 53,
  62, 56, 31, 33,

  //quarter duality breath
  7, 4, 29, 59,
  40, 64, 47, 6,
  46, 18, 48, 57,
  32, 50, 28, 44,

  1, 43, 14, 34,
  9, 5, 26, 11,
  10, 58, 38, 54,
  61, 60
];

final List<String> orderHexagramsWheelORIGINAL = [
  //qurater mutation complex
  '1', '43', '14', '34',
  '9', '5', '26', '11',
  '10', '58', '38', '54',
  '61', '60', '41', '19',

  //quarter initation simple
  '13', '49', '30', '55',
  '37', '63', '22', '36',
  '25', '17', '21', '51',
  '42', '3', '27', '24',

  //quarter civilization silence
  '2', '23', '8', '20',
  '16', '35', '45', '12',
  '15', '52', '39', '53',
  '62', '56', '31', '33',

  //quarter duality breath
  '7', '4', '29', '59',
  '40', '64', '47', '6',
  '46', '18', '48', '57',
  '32', '50', '28', '44',
];

final List<int> hexCarouselAlignList = [
  1,
];
final List<String> hexagramNames = [
  //qurater mutation complex
  'ZERO', 'The Creative', 'The Responsive', 'Mutative', 'Logic',
  'Waiting', 'Friction', 'Interactive', 'Contribution',
  'Focus', 'Selfish', 'Ideally', 'Cautious',
  'Listening', 'Wealthy', 'Extreme', 'Skillful',

  //quarter initation simple
  'Opinions', 'Correcting', 'Needy', 'Now',
  'Control', 'Grace', 'Assimilation', 'Return',
  'Innocence', 'Tricky', 'Caring', 'Player',
  'Watery', 'Fiery', 'Leading', 'Continuity',

  //quarter civilization silence
  'Memory', 'Powerful', 'Progressive', 'Crisis',
  'Family', 'Fighter', 'Provocation', 'Employed',
  'Fantasy', 'End', 'Knowing', 'Spotted',
  'King', 'Determined', 'Oppressed', 'Deep',

  //quarter duality breath
  'Revolutionary', 'Valued', 'Shocking', 'Still',
  'Begin', 'Ambitious', 'Spirit', 'Storyteller',
  'Wind', 'Joyous', 'Sexual', 'Constrained',
  'Mysterious', 'Detailed', 'Doubtful', 'Confused',
];

/// FULL SENTENCE

final List hexSentenceList = [
  0,
  'Adjective',
  'Subject',
  'Verb',
  'Adverb',
  1,
  'Creative',
  'Creativity',
  'Creates',
  'Creatively',
  2,
  'Responsive',
  'Response',
  'Responds',
  'Responsively',
  3,
  'Different',
  'Mutation',
  'Mutates',
  'Differently',
  4,
  'Chaotic',
  'Answer',
  'Answers',
  'Chaotically',
  5,
  'Patient',
  'Patience',
  'Waits',
  'Patiently',
  6,
  'Conflicting',
  'Conflict',
  'Conflicts',
  'Conflictingly',
  7,
  'Interactive',
  'Interaction',
  'Interacts',
  'Interactively',
  8,
  'Contributing',
  'Contribution',
  'Contributes',
  'Uniquely',
  9,
  'Focused',
  'Focus',
  'Focuses',
  'Focusingly',
  10,
  'Selfing',
  'Self',
  'Selfs',
  'Selfingly',
  11,
  'Ideal',
  'Idea',
  'Ideas',
  'Ideally',
  12,
  'Cautious',
  'Caution',
  'Cautions',
  'Cautiously',
  13,
  'Secret',
  'Secret',
  'Hides',
  'Secretly',
  14,
  'Wealthy',
  'Wealth',
  'Enriches',
  'Wealthfully',
  15,
  'Extreme',
  'Extreme',
  'Extremes',
  'Extremely',
  16,
  'Skillful',
  'Skill',
  'Identifies',
  'Skillfully',
  17,
  'Hierarchical',
  'Hierarchy',
  'Organizes',
  'Hierarchically',
  18,
  'Corrective',
  'Correction',
  'Corrects',
  'Correctly',
  19,
  'Needful',
  'Need',
  'Needs',
  'Needfully',
  20,
  'Attentive',
  'Attention',
  'Attends',
  'Attentively',
  21,
  'Controlled',
  'Control',
  'Controls',
  'Controllably',
  22,
  'Graceful',
  'Grace',
  'Graces',
  'Gracefully',
  23,
  'Assimilated',
  'Assimilation',
  'Assimilates',
  'Assimilably',
  24,
  'Rationalised',
  'Rationalisation',
  'Rationalises',
  'Rationally',
  25,
  'Innocent',
  'Innocence',
  'Innocences',
  'Innocently',
  26,
  'Tricky',
  'Trickster',
  'Tricks',
  'Trickily',
  27,
  'Caring',
  'Care',
  'Cares',
  'Carefully',
  28,
  'Risky',
  'Risk',
  'Risks',
  'Riskily',
  29,
  'Persevered',
  'Perseverance',
  'Perseveres',
  'Perseveringly',
  30,
  'Fiery',
  'Fire',
  'Fires',
  'Fiercely',
  31,
  'Leading',
  'Lead',
  'Leads',
  'Leadingly',
  32,
  'Failing',
  'Failure',
  'Fails',
  'Failingly',
  33,
  'Remembered',
  'Memory',
  'Remembers',
  'Privately',
  34,
  'Powerful',
  'Power',
  'Powers',
  'Powerfully',
  35,
  'Progressive',
  'Change',
  'Changes',
  'Progressively',
  36,
  'Endarkened',
  'Feeling',
  'Feels',
  'Fully',
  37,
  'Friendful',
  'Friend',
  'Befriends',
  'Friendly',
  38,
  'Fighting',
  'Fighter',
  'Fights',
  'Oppositely',
  39,
  'Provocative',
  'Provocation',
  'Provokes',
  'Provocatively',
  40,
  'Loyal',
  'Worker',
  'Works',
  'Loyally',
  41,
  'Fanciful',
  'Fantasy',
  'Fantasises',
  'Fancifully',
  42,
  'Ending',
  'End',
  'Ends',
  'Happily Ever After',
  43,
  'Insightful',
  'Insight',
  'Insights',
  'Insightfully',
  44,
  'Alertful',
  'Alert',
  'Alerts',
  'Alertly',
  45,
  'Bossy',
  'Boss',
  'Bosses',
  'Boastfully',
  46,
  'Determined',
  'Determination',
  'Determines',
  'Determinately',
  47,
  'Oppressed',
  'Oppression',
  'Oppresses',
  'Oppressively',
  48,
  'Deep',
  'Depth',
  'Deepens',
  'Deeply',
  49,
  'Revolutionary',
  'Revolution',
  'Revolutionizes',
  'Revolutionarily',
  50,
  'Valuable',
  'Value',
  'Values',
  'Valuably',
  51,
  'Shocking',
  'Shock',
  'Shocks',
  'Shockingly',
  52,
  'Mounted',
  'Mountain',
  'Mounts',
  'Mountfully',
  53,
  'First',
  'Beginning',
  'Begins',
  'At the Beginning',
  54,
  'Ambitious',
  'Ambition',
  'Drives',
  'Ambitiously',
  55,
  'Spirited',
  'Spirit',
  'Spirits',
  'Spiritually',
  56,
  'Believed',
  'Believer',
  'Believes',
  'Wonderingly',
  57,
  'Gentle',
  'GentleWind',
  'Blows',
  'Gently',
  58,
  'Joyous',
  'Joy',
  'Enjoys',
  'Joyously',
  59,
  'Sexual',
  'Sex',
  'Disperses',
  'Sexually',
  60,
  'Limited',
  'Limitation',
  'Limits',
  'Limitedly',
  61,
  'Truthful',
  'Truth',
  'Truths',
  'Truthfully',
  62,
  'Detailed',
  'Detail',
  'Details',
  'Detailedly',
  63,
  'Doubting',
  'Doubt',
  'Doubts',
  'Doubtfully',
  64,
  'Confusing',
  'Confusion',
  'Confuses',
  'Confusingly',
];

final List hexlinesList = [
  0,
  'grandmother',
  'mother',
  'daughter',
  'son',
  'father',
  'grandfather',
  1,
  'grandmother stuck in hell',
  'mother life is hell',
  'daughter complicated life',
  'son complicated life',
  'father is one foot from heaven',
  'grandfather died and is up in heaven',
  2,
  'grandmother remains silent',
  'mother tries to remain silent',
  'daughter suffers from silence',
  'son suffers from silence',
  'father is tortured from silence',
  'grandfather is silently falling from the top',
  3,
  'grandmother simple life is too easy to be expressed',
  'mother simple life is grounded and well lived',
  'silent daughter is fit for hardship',
  'silent son suffers hardship',
  'father simple life bring light to the world',
  'grandfather simple life burdens generations',
  4,
  'grandmother breath grounds her answers',
  'mother breath answers too light',
  'daughter silent answer is heavily thought',
  'son silent answer is burdens his family',
  'father breath is burdened to ansewr the world',
  'grandfather breath enlightens heaven ',
  5,
  'grandmother complex waiting pushes the Q too much',
  'mother complex waiting pushes her in the Q',
  'daughter simple waiting pushes her brother',
  'son simple waiting burdens his sister',
  'father simple patience crosses oceans',
  'grandfather simple patience is rejected by heaven',
  6,
  'grandmother breathe conflict and grounds herself',
  'mother breathe out conflict from herself',
  'daughter breathe in conflict propely',
  'son breathe out conflict and family suffers',
  'father resolves complex conflicts in the world',
  'grandfather conflict complex resolution reaches heaven',
  7,
  'grandmother breath interacts deeply with herself',
  'mother breath interacts to easily ',
  'daughter silently interacts with her mothers',
  'son silence burdens his interactions with the family',
  'father silence burdens world interactions',
  'grandfather silent interaction makes heaven like hell',
  8,
  'grandmother contributes to most profound silence ',
  'mother contributes to proper silence',
  'daughter contributes to silence of mothers',
  'son silent contribution burdens the family',
  'father simple contribution is known world wide',
  'grandfather simple contribution burdens his legacy',
  9,
  'grandmother complex focus has no ground at all',
  'mother complex focus is not grounded ',
  'daughter simple focus is to run from her mothers',
  'son simple focus burdens his family',
  'father complex focus reaches globally',
  'grandfather copmlex focus is known in heaven',
  10,
  'grandmother good behavior is never seen',
  'mother good behavior is rarely appreciated',
  'daughter negative behavior fits her role',
  'son behavior is rewarded',
  'father behavior is known world wide',
  'grandfather behavior remembered for generations',
  11,
  'grandmother idea brings war',
  'mother idea brings no resolution',
  'daughter idea is to leave the family',
  'son is not peaceful with his ideas',
  'father is not the ideal father',
  'grandfather forgets all his memory',
  12,
  'grandmother silent caution is deeply rooted',
  'mother silent caution protects her',
  'daughter breath sometimes cautions her mothers',
  'son breath moves cautiously to his fathers ',
  'father breath cautions strangers',
  'grandfather breath cautions heaven',
  13,
  'grandmother simple secret is revealed too easily',
  'mother simple secret is properly kept hidden',
  'daughter complex secret is mistakenly revealed to her brother',
  'son complex secret is properly told to father',
  'father complex secret is exposed to everyone',
  'grandfather complex secret reaches god',
  14,
  'grandmother wisdom is blackened',
  'mother wisdom is shadowed',
  'daughter wisdom cuts the feminine roots',
  'son is inspired to be like granfather and oppose his father',
  'father breath heavily and suffer',
  'grandfather is happy his grandson carries his wealth',
  15,
  'grandmother silent modesty is her epitath of love',
  'mother silent modesty grounds love',
  'daughter simple modesty pushes her brother',
  'son simple modesty burdens his sister',
  'father silent modesty is not loved in the world',
  'grandfather silent modesty is not accepted in heaven ',
  16,
  'grandmother silent skills are grounded for lifetimes',
  'mother silent skills grounds her',
  'daughter breathe skills from her mothers',
  'son breathe skills from his father',
  'father silent skills are not welcome in the world',
  'grandfather silent skills burdens his entire legacy',
  17,
  'grandmother light opinion do not serve her',
  'mother simple opinion grounds her',
  'daughter sound opinion grounds her mothers',
  'son sound opinion follows his father',
  'father simple opinion is followed worldwide',
  'grandfather simple opinion is hell for his legacy',
  18,
  'grandmother correctly inhales earth',
  'mother incorrectly exhales too soon',
  'daughter simple correction is too light',
  'son simple correction is too heavy',
  'father breath correction is rejected worldwide',
  'grandfather breath correction is welcome on heaven',
  19,
  'grandmother complex needs do not approach her roots',
  'mother complex needs do not yield to her mother',
  'daughter silent needs repent for her mothers',
  'son silent needs are a burden to his sister',
  'father silent needs are a burden to his son',
  'grandfather silent needs are a burden to his son',
  20,
  'grandmother is silent now all the way to the grave',
  'mother is silent now with her mother',
  'daugther contemplates the female silence',
  'son silenct contemplation is not welcome by his sister',
  'father complex contemplation is worldly known',
  'grandfather complex contemplates now in heaven',
  21,
  'grandmother simple control escapes too much',
  'mother simple control grounds her',
  'daughter controlled breath of grounds her mother',
  'son controlled breath is aspired by father',
  'father controlled breath is a burden to the world',
  'grandfather controlled breath moves in heaven',
  22,
  'grandmother simple grace escapes her',
  'mother simple grace grounds her',
  'daughter simple grace pushes her brother',
  'son simple grace is heavy on his sister',
  'father gracefully inhale the burden of the world',
  'grandfather exhale grace into heaven',
  23,
  'grandmother silent knowing speaks for itself',
  'mother speaks through silent knowing',
  'daughter silent knowing is heavy on her mothers',
  'son silent knowing is heavy on his sister',
  'father knows inhalation is a burden in the world',
  'grandfather knows exhalation is exhalted in the beyond',
  24,
  'grandmother simple rational thought is too light',
  'mother simple rational thought is considered',
  'daughter silent rational thought supports her mother',
  'son silent rational thought is heavy on his sister',
  'father silent rational thought is a burden in the world',
  'grandfather silent rational thought falls from heaven',
  25,
  'grandmother simple innocence does not ground love',
  'mother simple innocence grounds love',
  'daughter innocent breath grounds her mothers love',
  'son innocent breath aspires family love',
  'father innocence complex aspires worldly love',
  'grandfather innocence complex aspires heavenly love',
  26,
  'grandmother complex trick is exposed too much',
  'mother complex trick is exposed to her daughter',
  'daughter simple trick escapes her mothers',
  'son simple trick block his sister',
  'father breath trick is not welcome in the world',
  'grandfather breath trick is heavenly ',
  27,
  'grandmother simple care is too positive',
  'mother simple care grounds her',
  'daughter silent care grounds her mother',
  'son silent care is heavy on his sister',
  'father inhales worldy care too heavily',
  'grandfather exhales care up to heaven',
  28,
  'grandmother inhale grounded risk',
  'mother premature risk escapes her',
  'daughter complex risk pushes her brother',
  'son complex risk aspires the family',
  'father simple risk is success in the world ',
  'grandfather simple risk is a burden to his son',
  29,
  'grandmother inhalation is persevered in the deep water',
  'mother exhalation do not persevere in mid water',
  'daughter persevere in silent high water',
  'son silent perseverance is a heavy on the family',
  'father simple swim perseveres through dark clouds',
  'grandfather simple swim do not persevere in heaven',
  30,
  'grandmother simple fire is quickly extinguished',
  'mother simple fire is long lasting',
  'daughter complex fire burns her brother',
  'son complex fire lightens the family',
  'father inhales fire and is burnt in the world',
  'grandfather exhaled fire enlightens heavenly bonfire',
  31,
  'grandmother leads silently even in the grave',
  'mother leads silently during life',
  'daughter influences her complex brother too lightly',
  'son leads the complex of the family',
  'father simple influence leads the world',
  'grandfather simple influence is heavy on his son',
  32,
  'grandmother inhales failure during wind',
  'mother exhales failure too early during wind',
  'daughter complex failure escapes the wind of her mothers',
  'son complex failure moves during thunder',
  'father silent thundering failure is ruined in the world',
  'grandfather silent failure is ruining his son',
  33,
  'grandmother silent retreat deep in the mountain',
  'mother silent retreat with her mother',
  'daughter complex retreat away from the mountain',
  'son timely advances to his fathers',
  'father timing is rememebered throughout the world',
  'grandfather timing is heavenly memory',
  34,
  'grandmother complex power is blinding',
  'mother complex power is too bright',
  'daughter complex power is outshined by brother',
  'son complex power shines in the family',
  'father silent power is heavy on the world',
  'grandfather silent power is hidden from heaven',
  35,
  'grandmother silent progress does not change even in the grave',
  'mother silent progress does not change life',
  'daughter inhale progress in changing earth',
  'son exhales progress to change his family',
  'father inhales worldly changes heavily',
  'grandfather exhales change into heaven',
  36,
  'grandmother simple crisis is too easy in the firebase',
  'mother simple crisis allows the fire to burn on the ground',
  'daughter simple crisis extinguishes the fire',
  'son simple crisis is heavy on the family',
  'father silent world crisis is heavy on the sky',
  'grandfather silent heavenly crisis rejects liberation',
  37,
  'grandmother simple family escapes her',
  'mother simple family protects her',
  'daughter escapes the simple family',
  'son is stuck in the simple family',
  'father complex family shines in the world',
  'grandfather complex family shines in heaven',
  38,
  'grandmother complex fight misses the picnic on the lake',
  'mother all too often fights her daughter in the lake',
  'daughter inhales the fight to balance her mothers on the lake',
  'son exhales the firefight for family balance',
  'father inhales world firefight and is burnt',
  'grandfather exhales to heaven any firefight',
  39,
  'grandmother provokes silence deep in the mountain',
  'mother provokes grounding silence',
  'daughter simple provocation escapes the mountain',
  'son simple provocation opposse his sister escape',
  'father simple provocation is a bridge over troubled ocean',
  'grandfather simple provocation floods the world',
  40,
  'grandmother inhales family work as hard as ice',
  'mother exhales family work in premature deliverance',
  'daughter inhales family work to repent for her mother',
  'son exhales family work to shine for his fathers',
  'father work in the world is rejected',
  'grandfather work is banished from heaven',
  41,
  'grandmother fantasy time arrives too soon',
  'mother fantasy time arrives only too short',
  'daughter silent fantasy grounds her mothers',
  'son silent fantasy burdens his sister',
  'father inhale burden of world fantasy',
  'grandfather exhale his fantasy up to heaven',
  42,
  'grandmother simple growth is cut prematurely',
  'mother simple growth is safe and sound',
  'daughter silent growth grounds her mother',
  'son silent growth burdens his sister',
  'father complex growth enlightens the world',
  'grandfather complex growth penetrates heaven',
  43,
  'grandmother complex insight is too light',
  'mother complex insight is too early',
  'daughter complex insight pushes her brother',
  'son complex insight inspires the family',
  'father simple insight crosses the world',
  'grandfather simple insight is a heavy on his son',
  44,
  'grandmother is alert to inhale wind slowly',
  'mother is alert and exhales wind too fast ',
  'daughter complex alert escapes the wind',
  'son time alert aspires his family',
  'father time alert crosses the world  ',
  'grandfather time alert goes beyond the univers',
  45,
  'grandmother is the silent owner of earth',
  'mother is the silent owner of her body',
  'daughter inhales her mothers property',
  'son exhales shines the family ownership',
  'father simple ownership gathers the world',
  'grandfather simple ownership cuts through his sons',
  46,
  'grandmother determined inhalation balances the wind',
  'mother determined exhalation blows the wind too early',
  'daughter simple determination pushes her brother',
  'son simple determination is heavy on his sister',
  'father silent determination is a world burden',
  'grandfather silent determination is rejected from heaven',
  47,
  'grandmother oppresses inhalation in deep water',
  'mother oppressed exhalation escapes the water too early',
  'daughter oppressed inhalation on the water surface',
  'son oppressed exhalation is exhalted in the family',
  'father simple realization polishes the world',
  'grandfather simple realization is not welcome in heaven',
  48,
  'grandmother inhales solutions deep into the wind',
  'mother exhales solutions to early into the wind',
  'daughter simple solution in blown by the wind',
  'son simple solution is is dropped on his sister',
  'father simple solution rides through the ocean',
  'grandfather simple solution is banished from heaven',
  49,
  'grandmother simple principle is a revolution too soon',
  'mother simple principle is a welcomed revolution',
  'daughter complex principle pushes her brother revolution',
  'son complex principle inspires the family revolution',
  'father simple principle is reflected in world revolution',
  'grandfather simple principle is a burden to his son',
  50,
  'grandmother value is to inhale the wind to ground',
  'mother value is to exhale the wind too early',
  'daughter complex value pushes her brother',
  'son complex value fires through the family',
  'father inhales world value too heavily',
  'grandfather exhales heavenly value',
  51,
  'grandmother simple shock roars too easily',
  'mother simple shock roars from the ground',
  'daughter inhales shock of mothers roar',
  'son exhales shock inspire family roar',
  'father silent shock depresses the world',
  'grandfather silent shock is banished from heaven',
  52,
  'grandmother silent meditation serves lifetimes',
  'mother silent meditation serves her life',
  'daughter simple meditation is to escape the mountain',
  'son simple meditation is a burden to his sister',
  'father inhales mediation to depress the world',
  'grandfather exhales meditation to exhalt heaven',
  53,
  'grandmother begins silence deep in the mountain',
  'mother begins silence on the ground ',
  'daughter simple start pushes her brother',
  'son simple start is heavy on his sister',
  'father complex development begins in the world',
  'grandfather complex development begins in heaven',
  54,
  'grandmother complex ambition drives all too fast',
  'mother complex ambition drives her too early',
  'daughter inhales ambition to balance her mothers',
  'son exhales ambition to inspire his family',
  'father silent ambition is heavy on the world',
  'grandfather silent ambition is rejected from heaven',
  55,
  'grandmother simple spirit fires too fast',
  'mother simple spirit fires the ground',
  'daughter complex spirit pushes her brother',
  'son complex spirit inspires the family',
  'father silent spirit is heavy on the world',
  'grandfather silent spirit is rejected from heaven',
  56,
  'grandmother silently wanders the mountain',
  'mother silently wanders on the ground',
  'daughter complex belief pushes her brother',
  'son complex belieft inspires the family',
  'father inhales world belief too seriously',
  'grandfather exhales the story of heaven',
  57,
  'grandmother inhales the wind to the ground',
  'mother exhales the wind too soon',
  'daughter exhales the wind to push her brother',
  'son inhales the wind to depress his sister',
  'father is gentle through the wind of the world',
  'grandfather gentle blow reaches heaven',
  58,
  'grandmother joy copmlex is brushed easily',
  'mother joy complex does not serve her',
  'daughter inhales joy to cover her mothers',
  'son exhales joy through family',
  'father simple joy keeps the world alive',
  'grandfather simple joy is rejected from heaven',
  59,
  'grandmother inhales sexuality through deep water',
  'mother exhales sexuality to disperse water early',
  'daughter silent sexuality is taken from mothers',
  'son silent sexuality is heavy on his sister',
  'father complex sexuality spreads through the world',
  'grandfather complex sexuality spreads through heaven',
  60,
  'grandmother complex limitation is too strong',
  'mother complex limitation is too early',
  'daughter silent limitation accepts her mother',
  'son silent limitation burdens his sister',
  'father simple acceptance shines in the world',
  'grandfather simple acceptance is rejected by heaven',
  61,
  'grandmother complex mystery is exposed too much',
  'mother complex mystery is exposed too early',
  'daughter silent truth grounds her mother',
  'son silent truth burdens his sister',
  'father complex mystery is truth in the world',
  'grandfather complex mystery is truth in heaven',
  62,
  'grandmother silent detail is for lifetimes',
  'mother silent detail serves her',
  'daughter complex detail pushes her brother',
  'son complex detail shines through the family',
  'father silent detail is a world burden',
  'grandfather silent detail is rejected from heaven',
  63,
  'grandmother simple doubt is all too early',
  'mother simple doubht serves her well',
  'daughter simple doubht pushes her brother',
  'son simple doubt blocks his sister',
  'father simple doubt inspires the world',
  'grandfather simple doubt in heaven rejects him afterlife',
  64,
  'grandmother inhales confusion into deep water',
  'mother exhales confusion to escape the water early',
  'daughter inhales confusion to ground her mother',
  'son exhales confusion to shine through the family',
  'father inhales a confused world too seriously',
  'grandfather exhales heaven before all is completed',
];

final List<String> hexagramOriginSentenceList = [
  '0',
  'Zero',
  'Zero',
  'Zero',
  'Zero',
  '1',
  'Creative',
  'Creativity',
  'Creates',
  'Creatively',
  '2',
  'Responsive',
  'Response',
  'Responds',
  'Responsively',
  '3',
  'Different',
  'Mutation',
  'Mutates',
  'Differently',
  '4',
  'Chaotic',
  'Answer',
  'Answers',
  'Chaotically',
  '5',
  'Patient',
  'Patience',
  'Waits',
  'Patiently',
  '6',
  'Conflicting',
  'Conflict',
  'Conflicts',
  'Conflictingly',
  '7',
  'Interactive',
  'Interaction',
  'Interacts',
  'Interactively',
  '8',
  'Contributing',
  'Contribution',
  'Contributes',
  'Uniquely',
  '9',
  'Focused',
  'Focus',
  'Focuses',
  'Focusingly',
  '10',
  'Selfing',
  'Self',
  'Selfs',
  'Selfingly',
  '11',
  'Ideal',
  'Idea',
  'Ideas',
  'Ideally',
  '12',
  'Cautious',
  'Caution',
  'Cautions',
  'Cautiously',
  '13',
  'Secret',
  'Secret',
  'Hides',
  'Secretly',
  '14',
  'Wealthy',
  'Wealth',
  'Enriches',
  'Wealthfully',
  '15',
  'Extreme',
  'Extreme',
  'Extremes',
  'Extremely',
  '16',
  'Skillful',
  'Skill',
  'Identifies',
  'Skillfully',
  '17',
  'Hierarchical',
  'Hierarchy',
  'Organizes',
  'Hierarchically',
  '18',
  'Corrective',
  'Correction',
  'Corrects',
  'Correctly',
  '19',
  'Needful',
  'Need',
  'Needs',
  'Needfully',
  '20',
  'Attentive',
  'Attention',
  'Attends',
  'Attentively',
  '21',
  'Controlled',
  'Control',
  'Controls',
  'Controllably',
  '22',
  'Graceful',
  'Grace',
  'Graces',
  'Gracefully',
  '23',
  'Assimilated',
  'Assimilation',
  'Assimilates',
  'Assimilably',
  '24',
  'Rationalised',
  'Rationalisation',
  'Rationalises',
  'Rationally',
  '25',
  'Innocent',
  'Innocence',
  'Innocences',
  'Innocently',
  '26',
  'Tricky',
  'Trickster',
  'Tricks',
  'Trickily',
  '27',
  'Caring',
  'Care',
  'Cares',
  'Carefully',
  '28',
  'Risky',
  'Risk',
  'Risks',
  'Riskily',
  '29',
  'Persevered',
  'Perseverance',
  'Perseveres',
  'Perseveringly',
  '30',
  'Fiery',
  'Fire',
  'Fires',
  'Fiercely',
  '31',
  'Leading',
  'Lead',
  'Leads',
  'Leadingly',
  '32',
  'Failing',
  'Failure',
  'Fails',
  'Failingly',
  '33',
  'Remembered',
  'Memory',
  'Remembers',
  'Privately',
  '34',
  'Powerful',
  'Power',
  'Powers',
  'Powerfully',
  '35',
  'Progressive',
  'Change',
  'Changes',
  'Progressively',
  '36',
  'Endarkened',
  'Feeling',
  'Feels',
  'Fully',
  '37',
  'Friendful',
  'Friend',
  'Befriends',
  'Friendly',
  '38',
  'Fighting',
  'Fighter',
  'Fights',
  'Oppositely',
  '39',
  'Provocative',
  'Provocation',
  'Provokes',
  'Provocatively',
  '40',
  'Loyal',
  'Worker',
  'Works',
  'Loyally',
  '41',
  'Fanciful',
  'Fantasy',
  'Fantasises',
  'Fancifully',
  '42',
  'Ending',
  'End',
  'Ends',
  'Happily Ever After',
  '43',
  'Insightful',
  'Insight',
  'Insights',
  'Insightfully',
  '44',
  'Alertful',
  'Alert',
  'Alerts',
  'Alertly',
  '45',
  'Bossy',
  'Boss',
  'Bosses',
  'Boastfully',
  '46',
  'Determined',
  'Determination',
  'Determines',
  'Determinately',
  '47',
  'Oppressed',
  'Oppression',
  'Oppresses',
  'Oppressively',
  '48',
  'Deep',
  'Depth',
  'Deepens',
  'Deeply',
  '49',
  'Revolutionary',
  'Revolution',
  'Revolutionizes',
  'Revolutionarily',
  '50',
  'Valuable',
  'Value',
  'Values',
  'Valuably',
  '51',
  'Shocking',
  'Shock',
  'Shocks',
  'Shockingly',
  '52',
  'Mounted',
  'Mountain',
  'Mounts',
  'Mountfully',
  '53',
  'First',
  'Beginning',
  'Begins',
  'At the Beginning',
  '54',
  'Ambitious',
  'Ambition',
  'Drives',
  'Ambitiously',
  '55',
  'Spirited',
  'Spirit',
  'Spirits',
  'Spiritually',
  '56',
  'Believed',
  'Believer',
  'Believes',
  'Wonderingly',
  '57',
  'Gentle',
  'GentleWind',
  'Blows',
  'Gently',
  '58',
  'Joyous',
  'Joy',
  'Enjoys',
  'Joyously',
  '59',
  'Sexual',
  'Sex',
  'Disperses',
  'Sexually',
  '60',
  'Limited',
  'Limitation',
  'Limits',
  'Limitedly',
  '61',
  'Truthful',
  'Truth',
  'Truths',
  'Truthfully',
  '62',
  'Detailed',
  'Detail',
  'Details',
  'Detailedly',
  '63',
  'Doubting',
  'Doubt',
  'Doubts',
  'Doubtfully',
  '64',
  'Confusing',
  'Confusion',
  'Confuses',
  'Confusingly',
];

final List<String> hexagramAdjectiveList = [
  'Zero',
  'Creative',
  'Responsive',
  'Different',
  'Chaotic',
  'Patient',
  'Conflicting',
  'Interactive',
  'Contributing',
  'Focused',
  'Selfing',
  'Ideal',
  'Cautious',
  'Secret',
  'Wealthy',
  'Extreme',
  'Skillful',
  'Hierarchical',
  'Corrective',
  'Needful',
  'Attentive',
  'Controlled',
  'Graceful',
  'Assimilated',
  'Rationalised',
  'Innocent',
  'Tricky',
  'Caring',
  'Risky',
  'Persevered',
  'Fiery',
  'Leading',
  'Failing',
  'Remembered',
  'Powerful',
  'Progressive',
  'Endarkened',
  'Friendful',
  'Fighting',
  'Provocative',
  'Loyal',
  'Fanciful',
  'Ending',
  'Insightful',
  'Alertful',
  'Bossy',
  'Determined',
  'Oppressed',
  'Deep',
  'Revolutionary',
  'Valuable',
  'Shocking',
  'Mounted',
  'First',
  'Ambitious',
  'Spirited',
  'Believed',
  'Gentle',
  'Joyous',
  'Sexual',
  'Limited',
  'Truthful',
  'Detailed',
  'Doubting',
  'Confusing',
];

final List<String> hexagramSubjectList = [
  'Zero',
  'Creativity',
  'Response',
  'Mutation',
  'Answer',
  'Patience',
  'Conflict',
  'Interaction',
  'Contribution',
  'Focus',
  'Self',
  'Idea',
  'Caution',
  'Secret',
  'Wealth',
  'Extreme',
  'Skill',
  'Hierarchy',
  'Correction',
  'Need',
  'Attention',
  'Control',
  'Grace',
  'Assimilation',
  'Rationalisation',
  'Innocence',
  'Trickster',
  'Care',
  'Risk',
  'Perseverance',
  'Fire',
  'Lead',
  'Failure',
  'Memory',
  'Power',
  'Change',
  'Feeling',
  'Friend',
  'Fighter',
  'Provocation',
  'Worker',
  'Fantasy',
  'End',
  'Insight',
  'Alert',
  'Boss',
  'Determination',
  'Oppression',
  'Depth',
  'Revolution',
  'Value',
  'Shock',
  'Mountain',
  'Beginning',
  'Ambition',
  'Spirit',
  'Believer',
  'GentleWind',
  'Joy',
  'Sexuality',
  'Limitation',
  'Truth',
  'Detail',
  'Doubt',
  'Confusion',
];

final List<String> hexagramVerbList = [
  'Zero',
  'Creates',
  'Responds',
  'Mutates',
  'Answers',
  'Waits',
  'Conflicts',
  'Interacts',
  'Contributes',
  'Focuses',
  'Selfs',
  'Ideas',
  'Cautions',
  'Hides',
  'Enriches',
  'Extremes',
  'Identifies',
  'Organizes',
  'Corrects',
  'Needs',
  'Attends',
  'Controls',
  'Graces',
  'Assimilates',
  'Rationalises',
  'Innocences',
  'Tricks',
  'Cares',
  'Risks',
  'Perseveres',
  'Fires',
  'Leads',
  'Fails',
  'Remembers',
  'Powers',
  'Changes',
  'Feels',
  'Befriends',
  'Fights',
  'Provokes',
  'Works',
  'Fantasises',
  'Ends',
  'Insights',
  'Alerts',
  'Bosses',
  'Determines',
  'Oppresses',
  'Deepens',
  'Revolutionizes',
  'Values',
  'Shocks',
  'Mounts',
  'Begins',
  'Drives',
  'Spirits',
  'Believes',
  'Blows',
  'Enjoys',
  'Disperses',
  'Limits',
  'Truths',
  'Details',
  'Doubts',
  'Confuses',
];

final List<String> hexagramVerbNewList = [
  'Zero',
  'Creates',
  'Responds',
  'Mutates',
  'will Answer',
  'will Wait',
  'Conflicts',
  'will Interact',
  'Contributes',
  'will Focus',
  'Selfs',
  'Idead',
  'Cautions',
  'Hid',
  'Enriches',
  'will Extreme',
  'will Identify',
  'will Organize',
  'will Correct',
  'Needs',
  'Attends',
  'Controls',
  'Graces',
  'Assimilates',
  'Rationalises',
  'Innocences',
  'Tricks',
  'Cares',
  'Risks',
  'Persevered',
  'Fired',
  'will Lead',
  'Fails',
  'Remembered',
  'Powers',
  'Changed',
  'Felt',
  'Befriends',
  'Fights',
  'Provokes',
  'Works',
  'Fantasised',
  'Ended',
  'Insights',
  'Alerts',
  'Bosses',
  'Determined',
  'Oppressed',
  'will Deepen',
  'Revolutionizes',
  'Values',
  'Shocks',
  'will Mount',
  'Began',
  'Drives',
  'Spirits',
  'Believed',
  'Blows',
  'will Enjoy',
  'Disperses',
  'Limits',
  'Truths',
  'will Detail',
  'will Doubt',
  'Confused',
];

final List<String> hexagramAdverbList = [
  'Zero',
  'Creatively',
  'Responsively',
  'Differently',
  'Chaotically',
  'Patiently',
  'Conflictingly',
  'Interactively',
  'Uniquely',
  'Focusingly',
  'Selfingly',
  'Ideally',
  'Cautiously',
  'Secretly',
  'Wealthfully',
  'Extremely',
  'Skillfully',
  'Hierarchically',
  'Correctly',
  'Needfully',
  'Attentively',
  'Controllably',
  'Gracefully',
  'Assimilably',
  'Rationally',
  'Innocently',
  'Trickily',
  'Carefully',
  'Riskily',
  'Perseveringly',
  'Fiercely',
  'Leadingly',
  'Failingly',
  'Privately',
  'Powerfully',
  'Progressively',
  'Fully',
  'Friendly',
  'Oppositely',
  'Provocatively',
  'Loyally',
  'Fancifully',
  'Happily Ever After',
  'Insightfully',
  'Alertly',
  'Boastfully',
  'Determinately',
  'Oppressively',
  'Deeply',
  'Revolutionarily',
  'Valuably',
  'Shockingly',
  'Mountfully',
  'At the Beginning',
  'Ambitiously',
  'Spiritually',
  'Wonderingly',
  'Gently',
  'Joyously',
  'Sexually',
  'Limitedly',
  'Truthfully',
  'Detailedly',
  'Doubtfully',
  'Confusingly',
];

final List<int> hexCarouselValueList = [
//'1','43'...,
  111,
  211,
  311,
  411,
  121,
  221,
  321,
  421,
  131,
  231,
  331,
  431,
  141,
  241,
  341,
  441,
  112,
  212,
  312,
  412,
  122,
  222,
  322,
  422,
  132,
  232,
  332,
  432,
  142,
  242,
  342,
  442,
  113,
  213,
  313,
  413,
  123,
  223,
  323,
  423,
  133,
  233,
  333,
  433,
  143,
  243,
  343,
  443,
  114,
  214,
  314,
  414,
  124,
  224,
  324,
  424,
  134,
  234,
  334,
  434,
  144,
  244,
  344,
  444,
];

final List<int> hexCarouselWheelOrderList = [
//'1','43'...,
  111,
  211,
  311,
  411,
  121,
  221,
  321,
  421,
  131,
  231,
  331,
  431,
  141,
  241,
  341,
  441,

  112,
  212,
  312,
  412,
  122,
  222,
  322,
  422,
  132,
  232,
  332,
  432,
  142,
  242,
  342,
  442,

  444,
  344,
  244,
  144,
  434,
  334,
  234,
  134,
  424,
  324,
  224,
  124,
  414,
  314,
  214,
  114,

  443,
  343,
  243,
  143,
  433,
  333,
  233,
  133,
  423,
  323,
  223,
  123,
  413,
  313,
  213,
  113,













];

/// FULL SENTENCE

final List<String> hexBasicList = [
  'assets/complex.png',
  'assets/simple.png',
  'assets/breath.png',
  'assets/silence.png',
];

final List<String> hexBasicMixList = [
  'assets/complexup.png',
  'assets/simplein.png',
  'assets/breathout.png',
  'assets/silencedown.png',
];

final List<String> hexBasicDownList = [
  'assets/complexdown.png',
  'assets/simpledown.png',
  'assets/breathdown.png',
  'assets/silencedown.png',
];

final List<String> hexBasicUpList = [
  'assets/complexup.png',
  'assets/simpleup.png',
  'assets/breathup.png',
  'assets/silenceup.png',
];

final List<String> hexDualList = [
  'assets/complexup.png',
  'assets/complexdown.png',
  'assets/simplein.png',
  'assets/simpledown.png',
  'assets/breathup.png',
  'assets/breathout.png',
  'assets/silenceup.png',
  'assets/silencedown.png',
];

final List<String> hexFullList = [
  'assets/complexup.png',
  'assets/complexin.png',
  'assets/complexout.png',
  'assets/complexdown.png',
  'assets/simpleup.png',
  'assets/simplein.png',
  'assets/simpleout.png',
  'assets/simpledown.png',
  'assets/breathup.png',
  'assets/breathin.png',
  'assets/breathout.png',
  'assets/breathdown.png',
  'assets/silenceup.png',
  'assets/silencein.png',
  'assets/silenceout.png',
  'assets/silencedown.png',
];

final List<String> hexNamesList = [
  'COMPLEX',
  'SIMPLE',
  'breath',
  'silence',
];

// variables
List<int> hexagramslist = List<int>.generate(65, (counter) => counter++);
var hexagramslistfinal = hexagramslist.getRange(1, hexagramslist.length);

// SLIDERS

final List<Widget> planetsFullSliders = planetsfullList
    .map((planet) => Container(
          margin: const EdgeInsets.all(5.0),
          child: ClipRRect(
              borderRadius: const BorderRadius.all(Radius.circular(5.0)),
              child: Stack(
                children: <Widget>[
                  Image.asset(planet, fit: BoxFit.cover, width: 100.0),
                ],
              )),
        ))
    .toList();

final List<Widget> planetsCrossSliders = planetsCrossList
    .map((planet) => Container(
          margin: const EdgeInsets.all(5.0),
          child: ClipRRect(
              borderRadius: const BorderRadius.all(Radius.circular(5.0)),
              child: Stack(
                children: <Widget>[
                  Image.asset(planet, fit: BoxFit.cover, width: 100.0),
                ],
              )),
        ))
    .toList();

final List<Widget> allItemsSliders = hexFullList
    .map((hexImage) => CircleAvatar(
        minRadius: 100.0,
        maxRadius: 100.0,
        backgroundImage: AssetImage(hexImage)))
    .toList();

final List<Widget> downHexagramSliders = hexBasicDownList
    .map((item) => Container(
          margin: const EdgeInsets.all(5.0),
          child: ClipRRect(
              borderRadius: const BorderRadius.all(Radius.circular(5.0)),
              child: Stack(
                children: <Widget>[
                  Image.asset(item, fit: BoxFit.cover, width: 500.0),
                ],
              )),
        ))
    .toList();

final List<Widget> mixHexagramSliders = hexBasicMixList
    .map((item) => Container(
          margin: const EdgeInsets.all(5.0),
          child: ClipRRect(
              borderRadius: const BorderRadius.all(Radius.circular(5.0)),
              child: Stack(
                children: <Widget>[
                  Image.asset(item, fit: BoxFit.cover, width: 500.0),
                ],
              )),
        ))
    .toList();

final List<Widget> mixHexagramSlidersNew = hexBasicMixList
    .map((hexagrambasicmix) => CircleAvatar(
        minRadius: 100.0,
        maxRadius: 100.0,
        backgroundImage: AssetImage(hexagrambasicmix)))
    .toList();

// DROPDOWN

final List<DropdownMenuItem<int>> hexDropDownNumbersList =
    hexagramslistfinal.map((int hexagramsnew) {
  return DropdownMenuItem(
    value: hexagramsnew,
    child: Text(
      hexagramsnew.toString(),
      style: const TextStyle(
        color: Colors.grey,
      ),
    ),
  );
}).toList();

final List<DropdownMenuItem<String>> fontHexList =
    fontHexOrderList.map((String chosenHexagrams) {
  return DropdownMenuItem(
    value: chosenHexagrams,
    child: Text(chosenHexagrams,
        style: const TextStyle(
          color: Colors.black,
          fontSize: 30.0,
          fontFamily: 'iChing',
        )),
  );
}).toList();

final List<DropdownMenuItem<int>> orderHexagramsWheelList =
    orderHexagramsWheel.map((int orderWheelHexagrams) {
  return DropdownMenuItem(
      value: orderWheelHexagrams,
      child: Text(orderWheelHexagrams.toString(),
          style: const TextStyle(
            color: Colors.grey,
          )));
}).toList();

final List<DropdownMenuItem<String>> iChingFontList =
    fontHexOrderList.map((String fontHexagrams) {
  return DropdownMenuItem(
    value: fontHexagrams,
    child: Text(fontHexagrams,
        style: const TextStyle(
          color: Colors.black,
          fontSize: 30.0,
          fontFamily: 'iChing',
        )),
  );
}).toList();

// map

final fontHexagramsMap = fontHexOrderList.asMap();
final fontHexagramsWheelMap = fontHexNumbersList.asMap();
