import 'package:flutter/material.dart';

const String maintitle = 'Rotation Time', language = 'ENGLISH';

final List<String> languagesList = ["English", "עברית"];

final List<String> languagesCodeList = ["EN", "HE"];

final List<String> titlesEN = [
  'Complex 1',
  'Complex 2',
  'Complex 3',
  'Simple 1',
  'Simple 2',
  'Simply Breathe',
  'Breathe Simply',
  '=='
];

final List<String> tempsubtitles = [
  'Complex HD',
];

// 'Simple 64 + 384 = 448',

final List<String> mainroutes_old = [
  '/rotatecomplex',
  '/rotatesimple',
  '/rotatebreath',
  '/rotatesilence',
  '/rotatesidk',
];

final List<String> temproutes = [
  '/rotatecomplexhd',
];

final List<String> rtimages = [
  'assets/minmax/mincomplex.png',
  'assets/minmax/minsimple.png',
  'assets/minmax/minbreath.png',
  'assets/minmax/minsilence.png',
  'assets/minmax/bluemax.png',
  'assets/minmax/greenmax.png',
  'assets/minmax/yellowmin.png',
  'assets/minmax/redmin.png',
  'assets/minmax/minque.gif',
  'assets/minmax/minmicex.png',
  'assets/minmax/blackmax.png',
  'assets/minmax/bluemin.png',
  'assets/minmax/greenmin.png',
  'assets/minmax/greymax.png',
  'assets/minmax/whitemax.png',
  'assets/kithe/kitcomplex.png',
  'assets/kithe/kitsimple.png',
  'assets/kithe/kitbreath.png',
  'assets/kithe/kitsilence.png',
  'assets/kithe/kitidkm.png',
  'assets/kithe/blkithe.png',
  'assets/kithe/grkithe.png',
  'assets/kithe/yelkithe.png',
  'assets/kithe/redkithe.png',
  'assets/kithe/blkithebg.png',
  'assets/kithe/grkithebg.png',
  'assets/kithe/yelkithebg.png',
  'assets/kithe/redkithebg.png',
  'assets/kithe/qkithe.gif',
  'assets/kithe/quekithe.png',
  'assets/kithe/exkithebg.png',
  'assets/coins/camel.png',
  'assets/coins/cameldog.png',
  'assets/coins/complex.png',
  'assets/coins/complexblack.png',
  'assets/coins/complexin.png',
  'assets/coins/complexout.png',
  'assets/coins/simple.png',
  'assets/coins/simpleblack.png',
  'assets/coins/simpleout.png',
  'assets/coins/simplewhite.png',
  'assets/coins/breath.png',
  'assets/coins/breathblack.png',
  'assets/coins/breathin.png',
  'assets/coins/breathwhite.png',
  'assets/coins/silence.png',
  'assets/coins/silencein.png',
  'assets/coins/silenceout.png',
  'assets/coins/silencewhite.png',
  'assets/camog/dog.png',
  'assets/coins/emptybodygraph.png',
  'assets/coins/emptymandala.png',
  'assets/coins/fullcoins.png',
  'assets/coins/fullcoinsbg.png',
  'assets/coins/fullrotateicon.png',
  'assets/coins/oldrotateicon500.png',
  'assets/coins/rotateicon2.png',
  'assets/coins/rotateicon1.png',
  'assets/coins/rotateicon500.png',
  'assets/coins/rotateiconbck.png',
  'assets/coins/yangyang.png',
  'assets/coins/yangyin.png',
  'assets/coins/yinyang.png',
  'assets/coins/yinyin.png',
  'assets/coins/rtevolution.png',
  'assets/coins/rtevolutionnobg.png',
  'assets/coins/yinyin.png',
  'assets/camog/mcamel.png',
  'assets/camog/mcameline.png',
  'assets/camog/mcamelyellow.png',
  'assets/camog/mcamog.png',
  'assets/camog/mcdog.png',
  'assets/camog/mcdogline.png',
  'assets/camog/dogstwo.gif',
  'assets/camog/dogswoofgoof.gif',
  'assets/camog/dogstwogrey.gif',
  'assets/camog/elephantajclock.png',
  'assets/camog/elephantclock.png',
  'assets/camog/bluedog.png',
  'assets/camog/greendog.png',
  'assets/camog/reddog.png',
  'assets/camog/yellowdog.png',
  'assets/camog/snoopyq.gif',
  'assets/camog/snoopyempty.png',
  'assets/planets/sun.png',
  'assets/planets/earth.png',
  'assets/planets/southnode.png',
  'assets/planets/northnode.png',
  'assets/planets/moon.png',
  'assets/planets/mars.png',
  'assets/planets/mercury.png',
  'assets/planets/venus.png',
  'assets/planets/jupiter.png',
  'assets/planets/saturn.png',
  'assets/planets/uranus.png',
  'assets/planets/neptune.png',
  'assets/planets/pluto.png',
  'assets/planets/chiron.png',
  //plants
  'assets/plants/mrbluep.png',
  'assets/plants/mrcamog.png',
  'assets/plants/mrgreavo.png',
  'assets/plants/msredtom.png',
  'assets/plants/msyelban.png',
  'assets/plants/rotav.png',
  'assets/plants/rotban.png',
  'assets/plants/rotegi.png',
  'assets/plants/rotom.png',
  'assets/plants/bimbox.png',
  //zodiac
  'assets/zodiac/pisces1.png',
  'assets/zodiac/aries2.png',
  'assets/zodiac/taurus3.png',
  'assets/zodiac/gemini4.png',
  'assets/zodiac/cancer5.png',
  'assets/zodiac/leo6.png',
  'assets/zodiac/virgo7.png',
  'assets/zodiac/libra8.png',
  'assets/zodiac/scorpio9.png',
  'assets/zodiac/sagittarius10.png',
  'assets/zodiac/capricorn11.png',
  'assets/zodiac/aquarius12.png',
  'assets/zodiac/zodiac13.png',
  // zodiac ill
  'assets/zodiac/aaries2il.png',
  'assets/zodiac/bcancer5il.png',
  'assets/zodiac/cgemini4il.png',
  'assets/zodiac/dleo6il.png',
  'assets/zodiac/elibra8il.png',
  'assets/zodiac/fsagittarius10il.png',
  'assets/zodiac/gscorpio9il.png',
  'assets/zodiac/htaurus3il.png',
  'assets/zodiac/ivirgo7il.png',
  'assets/zodiac/jcapricorn11il.png',
  'assets/zodiac/kaquarius12il.png',
  'assets/zodiac/lpisces1il.png',
];

final List zodiaclist = ['assets/zodiac/pisces1.png',
  'assets/zodiac/aries2.png',
  'assets/zodiac/taurus3.png',
  'assets/zodiac/gemini4.png',
  'assets/zodiac/cancer5.png',
  'assets/zodiac/leo6.png',
  'assets/zodiac/virgo7.png',
  'assets/zodiac/libra8.png',
  'assets/zodiac/scorpio9.png',
  'assets/zodiac/sagittarius10.png',
  'assets/zodiac/capricorn11.png',
  'assets/zodiac/aquarius12.png',];

final List zodiacNamelist = ['pisces',
  'aries',
  'taurus',
  'gemini',
  'cancer',
  'leo',
  'virgo',
  'libra',
  'scorpio',
  'sagittarius',
  'capricorn',
  'aquarius',];

final List zodiacSwephlist = [
  'aries',
  'taurus',
  'gemini',
  'cancer',
  'leo',
  'virgo',
  'libra',
  'scorpio',
  'sagittarius',
  'capricorn',
  'aquarius',
  'pisces',];

final List zodiacSwephImagelist = [
  'assets/zodiac/aries2.png',
  'assets/zodiac/taurus3.png',
  'assets/zodiac/gemini4.png',
  'assets/zodiac/cancer5.png',
  'assets/zodiac/leo6.png',
  'assets/zodiac/virgo7.png',
  'assets/zodiac/libra8.png',
  'assets/zodiac/scorpio9.png',
  'assets/zodiac/sagittarius10.png',
  'assets/zodiac/capricorn11.png',
  'assets/zodiac/aquarius12.png',
  'assets/zodiac/pisces1.png',];


final List zodiacillSwephlist = [
  'assets/zodiac/aaries2il.png',
  'assets/zodiac/htaurus3il.png',
  'assets/zodiac/cgemini4il.png',
  'assets/zodiac/bcancer5il.png',
  'assets/zodiac/dleo6il.png',
  'assets/zodiac/ivirgo7il.png',
  'assets/zodiac/elibra8il.png',
  'assets/zodiac/gscorpio9il.png',
  'assets/zodiac/fsagittarius10il.png',
  'assets/zodiac/jcapricorn11il.png',
  'assets/zodiac/kaquarius12il.png',
  'assets/zodiac/lpisces1il.png',
];

final List zodiacSwephGradeColorlist = [
  Colors.green,
  Colors.green,
  Colors.red,
  Colors.green,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.yellow,
  Colors.red,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.green,
  Colors.green,
  Colors.green,];

final List zodiacSwephNameHeblist = [
  'טל ה',
  'חד מימד תא השור',
  'תאום עם',
  'שר תן',
  'אריה',
  'בתול הא',
  'מוז נעים',
  'הקרב',
  'קש את',
  'ג די',
  'ד לי',
  'דג עם',];

final List zodiacNameHeblist = ['דג עם',
  'טל ה',
  'חד מימד תא השור',
  'תאום עם',
  'שר תן',
  'אריה',
  'בתול הא',
  'מוז נעים',
  'הקרב',
  'קש את',
  'ג די',
  'ד לי',];

final List zodiacColorlist = [
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.blue,
  Colors.blue,
  Colors.blue];

final List zodiacGradeColorlist = [
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.red,
  Colors.green,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.yellow,
  Colors.red,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.green];



List revZodiacList = zodiaclist.reversed.toList();
List revZodiacColorList = zodiacColorlist.reversed.toList();
List revzodiacGradeColorlist = zodiacGradeColorlist.reversed.toList();
List revzodiacSwephGradeColorlist = zodiacSwephGradeColorlist.reversed.toList();
List revzodiacNamelist = zodiacNamelist.reversed.toList();
List revzodiacNameHeblist = zodiacNameHeblist.reversed.toList();
List revzodiacSwephlist = zodiacSwephlist.reversed.toList();



final List rturlfull = [
  'https://rotation-time.web.app/',
  'https://rotation-time.web.app/#/rotatesilence',
  'https://rotation-time.web.app/#/rotatebreath',
  'https://rotation-time.web.app/#/rotatesimple',
  'https://rotation-time.web.app/#/rotatecomplex',
  'https://rotation-time.web.app/#/rotatesidk',
];

final List<String> rturlcoin = [
  'https://rotation-time.web.app/#/rotatecomplex',
  'https://rotation-time.web.app/#/rotatesimple',
  'https://rotation-time.web.app/#/rotatebreath',
  'https://rotation-time.web.app/#/rotatesilence',
];

final List<String> planetsfullList = [
  'assets/planets/sun.png',
  'assets/planets/earth.png',
  'assets/planets/northnode.png',
  'assets/planets/southnode.png',
  'assets/planets/moon.png',
  'assets/planets/mercury.png',
  'assets/planets/venus.png',
  'assets/planets/mars.png',
  'assets/planets/jupiter.png',
  'assets/planets/saturn.png',
  'assets/planets/uranus.png',
  'assets/planets/neptune.png',
  'assets/planets/pluto.png',
  'assets/planets/chiron.png',
];


final List<Color> planetscolorList = [
  //'assets/planets/sun.png',
  Colors.blue,
  //'assets/planets/earth.png',
  Colors.red,
  //'assets/planets/northnode.png',
  Colors.green,
  //'assets/planets/southnode.png',
  Colors.yellow,
  //'assets/planets/moon.png',
  Colors.green,
  //'assets/planets/mercury.png',
  Colors.green,
  //'assets/planets/venus.png',
  Colors.green,
  //'assets/planets/mars.png',
  Colors.green,
  //'assets/planets/jupiter.png',
  Colors.yellow,
  //'assets/planets/saturn.png',
  Colors.yellow,
  //'assets/planets/uranus.png',
  Colors.yellow,
  //'assets/planets/neptune.png',
  Colors.red,
  //'assets/planets/pluto.png',
  Colors.red,
  //'assets/planets/chiron.png',
  Colors.yellow,
];

final List<String> planetsiconList = [
  'assets/planets/sun.png',
  'assets/planets/northnode.png',
  'assets/planets/moon.png',
  'assets/planets/mercury.png',
  'assets/planets/venus.png',
  'assets/planets/mars.png',
  'assets/planets/jupiter.png',
  'assets/planets/saturn.png',
  'assets/planets/uranus.png',
  'assets/planets/neptune.png',
  'assets/planets/pluto.png',
  'assets/planets/earth.png',
  'assets/planets/southnode.png',
];

final List<String> planetsimagelist = [
  'assets/planets/sun.png',
  'assets/planets/earth.png',
  'assets/planets/northnode.png',
  'assets/planets/southnode.png',
  'assets/planets/moon.png',
  'assets/planets/mercury.png',
  'assets/planets/venus.png',
  'assets/planets/mars.png',
  'assets/planets/jupiter.png',
  'assets/planets/saturn.png',
  'assets/planets/uranus.png',
  'assets/planets/neptune.png',
  'assets/planets/pluto.png',
  //'assets/planets/chiron.png',
];

final List<String> planetspartialList = [
  'assets/planets/sun.png',
  'assets/planets/earth.png',
  'assets/planets/moon.png',
  'assets/planets/mercury.png',
  'assets/planets/venus.png',
  'assets/planets/mars.png',
  'assets/planets/jupiter.png',
  'assets/planets/saturn.png',
  'assets/planets/uranus.png',
  'assets/planets/neptune.png',
  'assets/planets/pluto.png',
];

final List<String> planetsNamesList = [
  'SUN',
  'EARTH',
  'MOON',
  'MERCURY',
  'VENUS',
  'MARS',
  'JUPITER',
  'SATURN',
  'URANUS',
  'NEPTUNE',
  'PLUTO',
];

final List<String> planetsCrossList = [
  'assets/planets/northnode.png',
  'assets/planets/sun.png',
  'assets/planets/earth.png',
  'assets/planets/southnode.png',
];

final List<String> hexList = [
  'assets/coins/complex.png',
  'assets/coins/simple.png',
  'assets/coins/breath.png',
  'assets/coins/silence.png',
];

final List<String> rtimageBolList = [
  'assets/coins/complex.png',
  'assets/coins/silence.png',
];

final List<String> fontHexOrderList = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '!',
  '@'
];

List<String> revfontHexOrderList = fontHexOrderList.reversed.toList();

final List<String> fontHexMixOrderList = [
  'a','1',
  'g','43',
  'f','14',
  'l','34',
  'e','9',
  'p','5',
  'k','26',
  'z','11',
  'd','10',
  's','58',
  'o','38',
  'C','54',
  'j','61',
  'F','60',
  'y','41',
  'S','19',

  'c','13',
  'u','49',
  'r','30',
  'H','55',
  'n','37',
  'O','63',
  'B','22',
  'U','36',
  'i','25',
  'J','17',
  'E','21',
  'W','51',
  'x','42',
  'Y','3',
  'R','27',
  '6','24',

  '@','2',
  '!','23',
  '0','8',
  'Q','20',
  '9','16',
  'X','35',
  '2','45',
  'w','12',
  '8','15',
  'V','52',
  '4','39',
  'D','53',
  '1','62',
  'I','56',
  'L','31',
  'h','33',

  '7','7',
  'T','4',
  '3','29',
  'A','59',
  '5','40',
  'P','64',
  'M','47',
  'm','6',
  'Z','46',
  'G','18',
  'N','48',
  'q','57',
  'K','32',
  't','50',
  'v','28',
  'b','44',
];
final List<String> fontWheelHexOrderList = [
  'a',//'1',
  'g',//'43',
  'f',//'14',
  'l',//'34',
  'e',//'9',
  'p',//'5',
  'k',//'26',
  'z',//'11',
  'd',//'10',
  's',//'58',
  'o',//'38',
  'C',//'54',
  'j',//'61',
  'F',//'60',
  'y',//'41',
  'S',//'19',

  'c',//'13',
  'u',//'49',
  'r',//'30',
  'H',//'55',
  'n',//'37',
  'O',//'63',
  'B',//'22',
  'U',//'36',
  'i',//'25',
  'J',//'17',
  'E',//'21',
  'W',//'51',
  'x',//'42',
  'Y',//'3',
  'R',//'27',
  '6',//'24',

  '@',//'2',
  '!',//'23',
  '0',//'8',
  'Q',//'20',
  '9',//'16',
  'X',//'35',
  '2',//'45',
  'w',//'12',
  '8',//'15',
  'V',//'52',
  '4',//'39',
  'D',//'53',
  '1',//'62',
  'I',//'56',
  'L',//'31',
  'h',//'33',

  '7',//'7',
  'T',//'4',
  '3',//'29',
  'A',//'59',
  '5',//'40',
  'P',//'64',
  'M',//'47',
  'm',//'6',
  'Z',//'46',
  'G',//'18',
  'N',//'48',
  'q',//'57',
  'K',//'32',
  't',//'50',
  'v',//'28',
  'b',//'44',
];

List<String> revfontWheelHexOrderList = fontWheelHexOrderList.reversed.toList();


List<String> revfontHexMixOrderList = fontHexMixOrderList.reversed.toList();


final List<int> fontHexNumbersList = [
  1,
  44,
  13,
  10,
  9,
  14,
  43,
  33,
  25,
  61,
  26,
  34,
  6,
  37,
  38,
  5,
  57,
  30,
  58,
  50,
  49,
  28,
  12,
  42,
  41,
  11,
  62,
  45,
  29,
  39,
  40,
  24,
  7,
  15,
  16,
  8,
  23,
  2,
  59,
  22,
  54,
  53,
  21,
  60,
  18,
  55,
  56,
  17,
  32,
  31,
  47,
  48,
  63,
  64,
  20,
  27,
  19,
  4,
  36,
  52,
  51,
  35,
  3,
  46
];
final List<int> fontHexLetterList = [
  1,
  44,
  13,
  10,
  9,
  14,
  43,
  33,
  25,
  61,
  26,
  34,
  6,
  37,
  38,
  5,
  57,
  30,
  58,
  50,
  49,
  28,
  12,
  42,
  41,
  11,
  62,
  45,
  29,
  39,
  40,
  24,
  7,
  15,
  16,
  8,
  23,
  2,
  59,
  22,
  54,
  53,
  21,
  60,
  18,
  55,
  56,
  17,
  32,
  31,
  47,
  48,
  63,
  64,
  20,
  27,
  19,
  4,
  36,
  52,
  51,
  35,
  3,
  46
];

List<int> revfontHexNumbersList = fontHexNumbersList.reversed.toList();


final List<int> orderHexagramsWheel = [
  //qurater mutation complex
  1, 43, 14, 34,
  9, 5, 26, 11,
  10, 58, 38, 54,
  61, 60, 41, 19,

  //quarter initation simple
  13, 49, 30, 55,
  37, 63, 22, 36,
  25, 17, 21, 51,
  42, 3, 27, 24,

  //quarter civilization silence
  2, 23, 8, 20,
  16, 35, 45, 12,
  15, 52, 39, 53,
  62, 56, 31, 33,

  //quarter duality breath
  7, 4, 29, 59,
  40, 64, 47, 6,
  46, 18, 48, 57,
  32, 50, 28, 44,
];

List<int> reversedHexagramsWheel = orderHexagramsWheel.reversed.toList();

final List<Color> botfourcoincolor = [
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
];

final List<Color> topfourcoincolor = [
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,
  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,
  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,
];

List<Color> revfourbotcoincolor = botfourcoincolor.reversed.toList();
List<Color> revfourtopcoincolor = topfourcoincolor.reversed.toList();

final List<Color> botcoincolor = [
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
];

final List<Color> midcoincolor = [
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,

  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,

  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,

  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,

  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,

  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,

  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,

  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,

  //change

  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,

  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,

  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,

  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,

  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,

  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,

  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,

  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
];

final List<Color> topcoincolor = [
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,

  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,

  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,

  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,

  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,

  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,

  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,

  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,

  //change

  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,

  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,

  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,

  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,

  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,

  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,

  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,

  Colors.red,
  Colors.yellow,
  Colors.green,
  Colors.blue,
];

List<Color> reversedbotcoincolor = botcoincolor.reversed.toList();
List<Color> reversedmidcoincolor = midcoincolor.reversed.toList();
List<Color> reversedtopcoincolor = topcoincolor.reversed.toList();

final List<Color> coincolors = [
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red
];

final List<Color> midyangcolor = [
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.blue,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.green,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.yellow,
  Colors.red,
  Colors.red,
  Colors.red,
  Colors.red,
];

final List<Color> topyangcolor = [
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.red,
];

List<Color> revmidyangcolor = midyangcolor.reversed.toList();
List<Color> revtopyangcolor = topyangcolor.reversed.toList();

final List<int> orderHexagramsToCalulateWheel = [
  //qurater mutation complex
  41, 19,

  //quarter initation simple
  13, 49, 30, 55,
  37, 63, 22, 36,
  25, 17, 21, 51,
  42, 3, 27, 24,

  //quarter civilization silence
  2, 23, 8, 20,
  16, 35, 45, 12,
  15, 52, 39, 53,
  62, 56, 31, 33,

  //quarter duality breath
  7, 4, 29, 59,
  40, 64, 47, 6,
  46, 18, 48, 57,
  32, 50, 28, 44,

  1, 43, 14, 34,
  9, 5, 26, 11,
  10, 58, 38, 54,
  61, 60
];

final List<String> orderHexagramsWheelORIGINAL = [
  //qurater mutation complex
  '1', '43', '14', '34',
  '9', '5', '26', '11',
  '10', '58', '38', '54',
  '61', '60', '41', '19',

  //quarter initation simple
  '13', '49', '30', '55',
  '37', '63', '22', '36',
  '25', '17', '21', '51',
  '42', '3', '27', '24',

  //quarter civilization silence
  '2', '23', '8', '20',
  '16', '35', '45', '12',
  '15', '52', '39', '53',
  '62', '56', '31', '33',

  //quarter duality breath
  '7', '4', '29', '59',
  '40', '64', '47', '6',
  '46', '18', '48', '57',
  '32', '50', '28', '44',
];


final List<String> hexagramNames = [
  //qurater mutation complex
  'ZERO', 'The Creative', 'The Responsive', 'Mutative', 'Logic',
  'Waiting', 'Friction', 'Interactive', 'Contribution',
  'Focus', 'Selfish', 'Ideally', 'Cautious',
  'Listening', 'Wealthy', 'Extreme', 'Skillful',

  //quarter initation simple
  'Opinions', 'Correcting', 'Needy', 'Now',
  'Control', 'Grace', 'Assimilation', 'Return',
  'Innocence', 'Tricky', 'Caring', 'Player',
  'Watery', 'Fiery', 'Leading', 'Continuity',

  //quarter civilization silence
  'Memory', 'Powerful', 'Progressive', 'Crisis',
  'Family', 'Fighter', 'Provocation', 'Employed',
  'Fantasy', 'End', 'Knowing', 'Spotted',
  'King', 'Determined', 'Oppressed', 'Deep',

  //quarter duality breath
  'Revolutionary', 'Valued', 'Shocking', 'Still',
  'Begin', 'Ambitious', 'Spirit', 'Storyteller',
  'Wind', 'Joyous', 'Sexual', 'Constrained',
  'Mysterious', 'Detailed', 'Doubtful', 'Confused',
];

/// FULL SENTENCE

final List LineSentenceList = [
  'Think, Build, Use, Neglect',
  'Time is Neglecting Self expression',
  'Time is Building a Driver',
  'Time is Thinking to Order Mutation',
  'Time shall Use Foolish Answers',
  'Time shall Neglect to Waiting',
  'Space - Use of Conflict',
  'Time shall Use Armed Interactions',
  'Time is Building a Contribution',
  'Time shall Neglect to Focus',
  'Time is Neglecting Self Behavior',
  'Time was Neglecting ideas',
  'Time is Bulding in Caution',
  'Time was Thinking of Secrets',
  'Time is Neglecting Empowered Wealth',
  'Time shall Build Extermely Modest',
  'Time shall Build Enthusiastic Skills',
  'Time shall Think on Following',
  'Time shall Use Corrections',
  'Space - Neglected Need',
  'Time is Building Now',
  'Space - Thought Control',
  'Time is Thinking to be Open',
  'Time is Building a Split Part',
  'Time is Thinking to Return',
  'Time is Thinking on Spirit of Self',
  'Space - Neglect Great Ego Tricks',
  'Space - Thought of Caring',
  'Time is Using a Risky Game',
  'Time was Using Perseverance',
  'Time was Thinking on Clinging',
  'Time shall Build Influence',
  'Space - Use of Continuity',
  'Time was Building Privacy',
  'Time is Neglecting Great Power',
  'Time was Building Changes',
  'Time was Thinking through Crises ',
  'Space - Thought of Family',
  'Time is Neglecting to Fight',
  'Time is Building in Provocation',
  'Space - Use of Deliverance',
  'Time was Neglecting Contractions',
  'Time was Thinking of Growth',
  'Time is Neglecting an Insight',
  'Space - Use of Meetings',
  'Space - Building to Gather',
  'Time was Using Self Determinations',
  'Time was Using Realized Oppressions',
  'Time shall Use Depth',
  'Space - Thought of Principles',
  'Space - Use of Values',
  'Time is Thinking of Arousing',
  'Time shall Build in Stillness',
  'Time was Building from the Beginnings',
  'Space - Neglected Drive',
  'Time is Thinking of Abundant Spirit',
  'Time was Building Stimulations',
  'Time is Using Intuitive Clarity',
  'Time shall Neglect Aliveness',
  'Space - Use of Sexuality',
  'Time is Neglecting an Accepted Limitation',
  'Time is Neglecting an Inner Mystery',
  'Time shall Build with Details',
  'Time shall Think After Completed Doubts',
  'Time was Using Confusions Before Completions',
];

final List LineSentenceList_old = [
  'Time and Space were are and shall be null',
  'Time is Creating a Self expression',
  'Time is Receiving a Driver',
  'Time is Mutating an Order',
  'Time shall Answer Fools',
  'Time shall Wait Fixed Patterns',
  'Space - Conflict of Friction',
  'Time shall Arm Interactions',
  'Time is Holding Together a Contribution',
  'Time shall Focus small powers',
  'Time is Treading a Love',
  'Time was Pacifying ideas',
  'Time is Stagnating a Caution',
  'Time was Listening to Secrets',
  'Time is Empowering a Wealthy Wagon',
  'Time shall Be Extermes in Modesty',
  'Time shall Enthusiast Skills',
  'Time shall Follow Hierarchies',
  'Time shall Correct Spoilt Authorities',
  'Space - Approach of Needs',
  'Time is Contemplating an Attention',
  'Space - Control Through Biting',
  'Time is Openning a Grace',
  'Time is Assimilating a Split Part',
  'Time is Returning a Rational',
  'Time is Being a Spirit Love',
  'Space - Tame of Great Tricks',
  'Space - Care to Nourish',
  'Time is Playing a Risky Game',
  'Time was Persevered in Abysses',
  'Time was Clinging to Fires',
  'Time shall Influence Leaderships',
  'Space - Endurance of Existing Continuity',
  'Time was Memorizing Private Retreats',
  'Time is Empowering a Self Greatness',
  'Time was Changing Progressions',
  'Time was Enlignthing Dark Crises ',
  'Space - Family of Friends',
  'Time is Fighting an Opposition',
  'Time is Provoking an Obstruction',
  'Space - Work of Loyalty',
  'Time was Decreased Fantasies',
  'Time was Increased Ends',
  'Time is Breaking Through an Insight',
  'Space - Come on Alert Meeting',
  'Space - Gatherers Together',
  'Time was Pushing upward Self Determinations',
  'Time was Oppressing Realizations',
  'Time shall Deepen Solutions',
  'Space - Revolution of Principles',
  'Space - Value of Coins in Pots',
  'Time is Arousing a Shock',
  'Time shall Keep Actions Still',
  'Time was Developed From Beginnings',
  'Space - Drive of Ambition',
  'Time is Freeing an Abundant Spirit',
  'Time was Lost in Beliefs',
  'Time is Clearing a Breath',
  'Time shall Enjoy Lives',
  'Space - Spread of Unity',
  'Time is Accepting a Limitation',
  'Time is Mystifying a Truth',
  'Time shall Detail Advantaged Thoughts',
  'Time shall Complete After Doubts',
  'Time was Complete Before Confusions',
];

final List LineSentenceWBreaksList = [
  'Time and Space \nwere are and shall be null',
  'Time is \nCreating a Self expression',
  'Time is \nReceiving a Driver',
  'Time is \nMutating an Order',
  'Time shall \nAnswer Fools',
  'Time shall \nWait Fixed Patterns',
  'Space - \nConflict of Friction',
  'Time shall \nArm Interactions',
  'Time is \nHolding Together a Contribution',
  'Time shall \nFocus small powers',
  'Time is \nTreading a Love',
  'Time was \nPacifying ideas',
  'Time is \nStagnating a Caution',
  'Time was \nListening to Secrets',
  'Time is \nEmpowering a Wealthy Wagon',
  'Time shall \nBe Extermes in Modesty',
  'Time shall \nEnthusiast Skills',
  'Time shall \nFollow Hierarchies',
  'Time shall \nCorrect Spoilt Authorities',
  'Space - \nApproach of Needs',
  'Time is \nContemplating an Attention',
  'Space - \nControl Through Biting',
  'Time is \nOpenning a Grace',
  'Time is \nAssimilating a Split Part',
  'Time is \nReturning a Rational',
  'Time is \nBeing a Spirit Love',
  'Space - \nTame of Great Tricks',
  'Space - \nCare to Nourish',
  'Time is \nPlaying a Risky Game',
  'Time was \nPersevered in Abysses',
  'Time was \nClinging to Fires',
  'Time shall \nInfluence Leaderships',
  'Space - \nEndurance of Existing Continuity',
  'Time was \nMemorizing Private Retreats',
  'Time is \nEmpowering a Self Greatness',
  'Time was \nChanging Progressions',
  'Time was \nEnlignthing Dark Crises ',
  'Space - \nFamily of Friends',
  'Time is \nFighting an Opposition',
  'Time is \nProvoking an Obstruction',
  'Space - \nWork of Loyalty',
  'Time was \nDecreased Fantasies',
  'Time was \nIncreased Ends',
  'Time is \nBreaking Through an Insight',
  'Space - \nCome on Alert Meeting',
  'Space - \nGatherers Together',
  'Time was \nPushing upward Self Determinations',
  'Time was \nOppressing Realizations',
  'Time shall \nDeepen Solutions',
  'Space - \nRevolution of Principles',
  'Space - \nValue of Coins in Pots',
  'Time is \nArousing a Shock',
  'Time shall \nKeep Actions Still',
  'Time was \nDeveloped From Beginnings',
  'Space - \nDrive of Ambition',
  'Time is \nFreeing an Abundant Spirit',
  'Time was \nLost in Beliefs',
  'Time is \nClearing a Breath',
  'Time shall \nEnjoy Lives',
  'Space - \nSpread of Unity',
  'Time is \nAccepting a Limitation',
  'Time is \nMystifying a Truth',
  'Time shall \nDetail Advantaged Thoughts',
  'Time shall \nComplete After Doubts',
  'Time was \nComplete Before Confusions',
];

final List hexSentenceList = [
  0,
  'Adjective',
  'Subject',
  'Verb',
  'Adverb',
  1,
  'Time',
  'is',
  'Creating',
  'Self expression',
  2,
  'Time',
  'is',
  'Received',
  'Driver',
  3,
  'Time',
  'is',
  'Mutating',
  'Orders',
  4,
  'Time',
  'shall',
  'Answer',
  'Foolishly',
  5,
  'Time',
  'shall',
  'Wait',
  'Patiently',
  6,
  'Space',
  '-',
  'Conflicts',
  'Friction',
  7,
  'Time',
  'shall',
  'Arm',
  'Interactions',
  8,
  'Time',
  'is',
  'Holding Together',
  'Contribution',
  9,
  'Time',
  'shall',
  'Tame Focused',
  'small power',
  10,
  'Time',
  'is',
  'Treading',
  'Love',
  11,
  'Time',
  'was',
  'Peacefully',
  'Idealized',
  12,
  'Time',
  'is',
  'Cautiously',
  'Stagnated',
  13,
  'Time',
  'was',
  'listening',
  'to human secret',
  14,
  'Time',
  'is',
  'Empowering',
  'Skilled Wealth',
  15,
  'Time',
  'shall',
  'be Extremly',
  'Modest',
  16,
  'Time',
  'shall',
  'Skillfuly',
  'Enthusiast',
  17,
  'Time',
  'shall',
  'Follow',
  'Hierarchy',
  18,
  'Time',
  'shall',
  'Correct',
  'Spoilt Authority',
  19,
  'Space',
  '-',
  'Approaches',
  'Needs',
  20,
  'Time',
  'is',
  'Contemplating',
  'Attention',
  21,
  'Space',
  '-',
  'Controls',
  'Through Biting',
  22,
  'Time',
  'is',
  'Gracefully',
  'Open',
  23,
  'Time',
  'is',
  'Assimilating',
  'Split Parts',
  24,
  'Time',
  'is',
  'Returning',
  'Rationally',
  25,
  'Time',
  'is',
  'Being',
  'Spirit Love',
  26,
  'Space',
  '-',
  'Tames',
  'Great Tricks',
  27,
  'Space',
  '-',
  'Nourishes',
  'Care',
  28,
  'Time',
  'is',
  'Playing',
  'Risky Game',
  29,
  'Time',
  'was',
  'Persevered',
  'Abysmally',
  30,
  'Time',
  'was',
  'Firing',
  'Clinging',
  31,
  'Time',
  'shall',
  'Influence',
  'Leadership',
  32,
  'Space',
  '-',
  'Endures',
  'Existing Continuity',
  33,
  'Time',
  'was',
  'Memorizing',
  'Private Retreat',
  34,
  'Time',
  'is',
  'Empowering',
  'Self Greatness',
  35,
  'Time',
  'was',
  'Changing',
  'Progressively',
  36,
  'Time',
  'was',
  'Endarkened',
  'Light Crisis ',
  37,
  'Space',
  '-',
  'Befriends',
  'Family',
  38,
  'Time',
  'is',
  'Fighting',
  'Opposition',
  39,
  'Time',
  'is',
  'Provoking',
  'Obstruction',
  40,
  'Space',
  '-',
  'Works',
  'Loyally',
  41,
  'Time',
  'was',
  'Decreased',
  'Fancifully',
  42,
  'Time',
  'was',
  'Increased',
  'until its end',
  43,
  'Time',
  'is',
  'Breaking Through',
  'Insight',
  44,
  'Space',
  '-',
  'Comes',
  'to Alert Meeting',
  45,
  'Space',
  '-',
  'Gathers',
  'Together',
  46,
  'Time',
  'was',
  'Pushed Upward',
  'Determinately',
  47,
  'Time',
  'was',
  'Oppression',
  'Realized',
  48,
  'Time',
  'shall',
  'Deepen',
  'Well',
  49,
  'Space',
  '-',
  'Revolutionizes',
  'Principles',
  50,
  'Space',
  '-',
  'Values',
  'Pots',
  51,
  'Time',
  'is',
  'Shockingly',
  'Arousing',
  52,
  'Time',
  'shall',
  'Keep',
  'Action Still',
  53,
  'Time',
  'was',
  'Developed',
  'From its Beginning',
  54,
  'Space',
  '-',
  'Drives',
  'Ambitiously',
  55,
  'Time',
  'is',
  'Abundant',
  'in Spirit',
  56,
  'Time',
  'was',
  'Believed',
  'to be Lost',
  57,
  'Time',
  'is',
  'Breathing',
  'Clearly',
  58,
  'Time',
  'shall',
  'Enjoy',
  'Life',
  59,
  'Space',
  '-',
  'Spreads',
  'Unity',
  60,
  'Time',
  'is',
  'Accepting',
  'Limitation',
  61,
  'Time',
  'is',
  'Mystifying',
  'Truth',
  62,
  'Time',
  'shall',
  'Detail',
  'Advantaged Thought',
  63,
  'Time',
  'shall',
  'Complete',
  'After Doubting',
  64,
  'Time',
  'was',
  'Complete',
  'Before Confusion',
];

final List hexSentenceList_heb = [
  0,
  'סוף',
  'מעלה',
  'מטה',
  'התחלה',
  1,
  'עצמו',
  'יוצר',
  'הינו',
  'זמן',
  2,
  'מיושב',
  'נהג',
  'הינו',
  'זמן',
  3,
  'מסדר',
  'אחרת',
  'הינו',
  'זמן',
  4,
  'נאורה',
  'מחשבה',
  'ישיב',
  'זמן',
  5,
  'סבלנית',
  'בתבנית',
  'ימתין',
  'זמן',
  6,
  'מתחכך',
  'עימות',
  '-',
  'מרחב',
  7,
  'משותפות',
  'פעולות',
  'יגייס',
  'זמן',
  8,
  'יחד',
  'תרומה',
  'מחזיק',
  'זמן',
  9,
  'קטן וממוקד',
  'כוח',
  'יאלף',
  'זמן',
  10,
  'אהבתו',
  'מעצם',
  'צועד',
  'זמן',
  11,
  'בשלום',
  'רעיון',
  'ראה',
  'זמן',
  12,
  'קופאת',
  'זהירות',
  'הינו',
  'זמן',
  13,
  'אדם וחווה',
  'לסודות',
  'האזין',
  'זמן',
  14,
  'גדול',
  'עושר',
  'הינו',
  'זמן',
  15,
  'קיצונית',
  'אנושיות',
  'יהיה',
  'זמן',
  16,
  'בהתלהבות',
  'מיומן',
  'יהיה',
  'זמן',
  17,
  'הסדר',
  'בעקבות',
  'ילך',
  'זמן',
  18,
  'הרוסה',
  'סמכות',
  'יתקן',
  'זמן',
  19,
  'נגיש',
  'צורך',
  '-',
  'מרחב',
  20,
  'מהדהדת',
  'הוויה',
  'הווה',
  'זמן',
  21,
  'נושך',
  'שליט',
  '-',
  'מרחב',
  22,
  'נפתח',
  'חסד',
  'הינו',
  'זמן',
  23,
  'מפוצלים',
  'חלקים',
  'מטמיע',
  'זמן',
  24,
  'היחס',
  'אל',
  'חוזר',
  'זמן',
  25,
  'הרוח',
  'אהבת',
  'הווה',
  'זמן',
  26,
  'תעלול נהדר',
  'אילוף',
  '-',
  'מרחב',
  27,
  'מתחשבת',
  'הזנה',
  '-',
  'מרחב',
  28,
  'בסיכון',
  'שחקן',
  'הינו',
  'זמן',
  29,
  'התהום',
  'דרך',
  'התמיד',
  'זמן',
  30,
  'בוערת',
  'אחיזה',
  'היה',
  'זמן',
  31,
  'משפיע',
  'מנהיג',
  'יהיה',
  'זמן',
  32,
  'המשכיות',
  'קיום',
  '-',
  'מרחב',
  33,
  'בנסיגה',
  'זיכרון',
  'היה',
  'זמן',
  34,
  'גדולה',
  'מעצמה',
  'הינו',
  'זמן',
  35,
  'קדום',
  'שינוי',
  'היה',
  'זמן',
  36,
  'שבורה',
  'חשכת אור',
  'היה',
  'זמן',
  37,
  'ומשפחה',
  'חברות',
  '-',
  'מרחב',
  38,
  'על הפוך',
  'הפוך',
  'נלחם',
  'זמן',
  39,
  'משוכה',
  'בעזרת',
  'דוקר',
  'זמן',
  40,
  'נאמן',
  'עובד',
  '-',
  'מרחב',
  41,
  'כיווץ',
  'בעת',
  'הופחת',
  'זמן',
  42,
  'הסוף',
  'עד',
  'צמח',
  'זמן',
  43,
  'התובנה',
  'פריצה דרך',
  'הינו',
  'זמן',
  44,
  'את הפגישה',
  'מגיע להדריך',
  '-',
  'מרחב',
  45,
  'יחד',
  'אוסף',
  '-',
  'מרחב',
  46,
  'מעצם הנחישות',
  'מעלה',
  'נדחף',
  'זמן',
  47,
  'שהתממש',
  'דיכוי',
  'היה',
  'זמן',
  48,
  'הפתרון',
  'לבאר',
  'יעמיק',
  'זמן',
  49,
  'של עקרונות',
  'מהפכה',
  '-',
  'מרחב',
  50,
  'תבשיל',
  'מעריך',
  '-',
  'מרחב',
  51,
  'זעזוע',
  'מעורר',
  'הינו',
  'זמן',
  52,
  'דוממת',
  'את הפעולה',
  'ישאיר',
  'זמן',
  53,
  'ההתחלה',
  'מן',
  'התפתח',
  'זמן',
  54,
  'קיים',
  'מניע דחף',
  '-',
  'מרחב',
  55,
  'רוחני',
  'שפע',
  'הינו',
  'זמן',
  56,
  'שאבדה',
  'אמונה',
  'היה',
  'זמן',
  57,
  'הרוח',
  'בהירות',
  'הינו',
  'זמן',
  58,
  'החיים',
  'מן',
  'יהנה',
  'זמן',
  59,
  'האחדות',
  'התפשטות',
  '-',
  'מרחב',
  60,
  'המגבלה',
  'קבלת',
  'הינו',
  'זמן',
  61,
  'מן האמת',
  'התעלמות',
  'הינו',
  'זמן',
  62,
  'המחשבה',
  'את יתרון',
  'יפרט',
  'זמן',
  63,
  'לאחר הספק',
  'שלם',
  'יהיה',
  'זמן',
  64,
  'לפני הבלבול',
  'שלם',
  'היה',
  'זמן'
];

final List hexSentenceList_old = [
  0,
  'Adjective',
  'Subject',
  'Verb',
  'Adverb',
  1,
  'Creative',
  'Creativity',
  'is Creating',
  'Creatively',
  2,
  'Responsive',
  'Response',
  'is Responding',
  'Responsively',
  3,
  'Different',
  'Mutation',
  'is Mutating',
  'Differently',
  4,
  'Chaotic',
  'Answer',
  'shall Answer',
  'Chaotically',
  5,
  'Patient',
  'Patience',
  'shall Wait',
  'Patiently',
  6,
  'Conflicting',
  'Conflict',
  'Conflicts',
  'Conflictingly',
  7,
  'Interactive',
  'Interaction',
  'shall Interact',
  'Interactively',
  8,
  'Contributing',
  'Contribution',
  'is Contributing',
  'Uniquely',
  9,
  'Focused',
  'Focus',
  'shall Focus',
  'Focusingly',
  10,
  'Self',
  'Behavior',
  'is Behaving',
  'Selfishly',
  11,
  'Ideal',
  'Idea',
  'Idealized',
  'Ideally',
  12,
  'Cautious',
  'Caution',
  'is Cautioning',
  'Cautiously',
  13,
  'Secret',
  'Secret',
  'Hid',
  'Secretly',
  14,
  'Wealthy',
  'Wealth',
  'is Enriching',
  'Wealthfully',
  15,
  'Extreme',
  'Extreme',
  'shall Extreme',
  'Extremely',
  16,
  'Skillful',
  'Skill',
  'shall Identify',
  'Skillfully',
  17,
  'Hierarchical',
  'Hierarchy',
  'shall Organize',
  'Hierarchically',
  18,
  'Corrective',
  'Correction',
  'shall Correct',
  'Correctly',
  19,
  'Needful',
  'Need',
  'Needs',
  'Needfully',
  20,
  'Attentive',
  'Attention',
  'is Attending',
  'Attentively',
  21,
  'Controlled',
  'Control',
  'Controls',
  'Controllably',
  22,
  'Graceful',
  'Grace',
  'is Gracing',
  'Gracefully',
  23,
  'Assimilated',
  'Assimilation',
  'is Assimilating',
  'Assimilably',
  24,
  'Rationalised',
  'Rationalisation',
  'is Rationalizing',
  'Rationally',
  25,
  'Loving',
  'Love',
  'is Loving',
  'Lovingly',
  26,
  'Tricky',
  'Trickster',
  'Tricks',
  'Trickily',
  27,
  'Caring',
  'Care',
  'Cares',
  'Carefully',
  28,
  'Risky',
  'Risk',
  'is Risking',
  'Riskily',
  29,
  'Persevered',
  'Perseverance',
  'Persevered',
  'Perseveringly',
  30,
  'Fiery',
  'Fire',
  'Fired',
  'Fiercely',
  31,
  'Influencing',
  'Influence',
  'shall Influence',
  'Influentially',
  32,
  'Failing',
  'Failure',
  'Fails',
  'Failingly',
  33,
  'Private',
  'Memory',
  'Memorized',
  'Privately',
  34,
  'Powerful',
  'Power',
  'is Powering',
  'Powerfully',
  35,
  'Progressive',
  'Change',
  'Changed',
  'Progressively',
  36,
  'Dark',
  'Crisis',
  'Endarkened',
  'Lightly',
  37,
  'Friendful',
  'Friend',
  'Befriends',
  'Friendly',
  38,
  'Fighting',
  'Fighter',
  'is Fighting',
  'Oppositely',
  39,
  'Provocative',
  'Provocation',
  'is Provoking',
  'Provocatively',
  40,
  'Loyal',
  'Worker',
  'Works',
  'Loyally',
  41,
  'Fanciful',
  'Fantasy',
  'Fantasised',
  'Fancifully',
  42,
  'Increasing',
  'End',
  'Ended',
  'Happily Ever After',
  43,
  'Insightful',
  'Breakthrough',
  'is Insighting',
  'Insightfully',
  44,
  'Alertful',
  'Alert',
  'Alerts',
  'Alertly',
  45,
  'Bossy',
  'Boss',
  'Bosses',
  'Boastfully',
  46,
  'Determined',
  'Determination',
  'Determined',
  'Determinately',
  47,
  'Oppressed',
  'Oppression',
  'Oppressed',
  'Oppressively',
  48,
  'Deep',
  'Depth',
  'shall Deepen',
  'Deeply',
  49,
  'Revolutionary',
  'Revolution',
  'Revolutionizes',
  'Revolutionarily',
  50,
  'Valuable',
  'Value',
  'Values',
  'Valuably',
  51,
  'Shocking',
  'Shock',
  'is Shocking',
  'Shockingly',
  52,
  'Inactive',
  'Stillness',
  'shall inactivate',
  'Inactively',
  53,
  'First',
  'Growth',
  'Began',
  'At the Beginning',
  54,
  'Ambitious',
  'Ambition',
  'Drives',
  'Ambitiously',
  55,
  'Spirited',
  'Abundance',
  'is Spiriting',
  'Spiritually',
  56,
  'Wandering',
  'Believer',
  'Believed',
  'Wonderingly',
  57,
  'Gentle',
  'Intuition',
  'is Blowing',
  'Gently',
  58,
  'Joyous',
  'Joy',
  'shall Enjoy',
  'Joyously',
  59,
  'Sexual',
  'Sex',
  'Disperses',
  'Sexually',
  60,
  'Limited',
  'Limitation',
  'is Limiting',
  'Limitedly',
  61,
  'Truthful',
  'Mystery',
  'is Mystifying',
  'Truthfully',
  62,
  'Small',
  'Detail',
  'shall Detail',
  'Thoughtfully',
  63,
  'Doubting',
  'Doubt',
  'shall Doubt',
  'Doubtfully',
  64,
  'Confusing',
  'Confusion',
  'Confused',
  'Confusingly',
];

final List<String> hexagramOriginSentenceList = [
  '0',
  'Zero',
  'Zero',
  'Zero',
  'Zero',
  '1',
  'Creative',
  'Creativity',
  'Creates',
  'Creatively',
  '2',
  'Responsive',
  'Response',
  'Responds',
  'Responsively',
  '3',
  'Different',
  'Mutation',
  'Mutates',
  'Differently',
  '4',
  'Chaotic',
  'Answer',
  'Answers',
  'Chaotically',
  '5',
  'Patient',
  'Patience',
  'Waits',
  'Patiently',
  '6',
  'Conflicting',
  'Conflict',
  'Conflicts',
  'Conflictingly',
  '7',
  'Interactive',
  'Interaction',
  'Interacts',
  'Interactively',
  '8',
  'Contributing',
  'Contribution',
  'Contributes',
  'Uniquely',
  '9',
  'Focused',
  'Focus',
  'Focuses',
  'Focusingly',
  '10',
  'Selfing',
  'Self',
  'Selfs',
  'Selfingly',
  '11',
  'Ideal',
  'Idea',
  'Ideas',
  'Ideally',
  '12',
  'Cautious',
  'Caution',
  'Cautions',
  'Cautiously',
  '13',
  'Secret',
  'Secret',
  'Hides',
  'Secretly',
  '14',
  'Wealthy',
  'Wealth',
  'Enriches',
  'Wealthfully',
  '15',
  'Extreme',
  'Extreme',
  'Extremes',
  'Extremely',
  '16',
  'Skillful',
  'Skill',
  'Identifies',
  'Skillfully',
  '17',
  'Hierarchical',
  'Hierarchy',
  'Organizes',
  'Hierarchically',
  '18',
  'Corrective',
  'Correction',
  'Corrects',
  'Correctly',
  '19',
  'Needful',
  'Need',
  'Needs',
  'Needfully',
  '20',
  'Attentive',
  'Attention',
  'Attends',
  'Attentively',
  '21',
  'Controlled',
  'Control',
  'Controls',
  'Controllably',
  '22',
  'Graceful',
  'Grace',
  'Graces',
  'Gracefully',
  '23',
  'Assimilated',
  'Assimilation',
  'Assimilates',
  'Assimilably',
  '24',
  'Rationalised',
  'Rationalisation',
  'Rationalises',
  'Rationally',
  '25',
  'Innocent',
  'Innocence',
  'Innocences',
  'Innocently',
  '26',
  'Tricky',
  'Trickster',
  'Tricks',
  'Trickily',
  '27',
  'Caring',
  'Care',
  'Cares',
  'Carefully',
  '28',
  'Risky',
  'Risk',
  'Risks',
  'Riskily',
  '29',
  'Persevered',
  'Perseverance',
  'Perseveres',
  'Perseveringly',
  '30',
  'Fiery',
  'Fire',
  'Fires',
  'Fiercely',
  '31',
  'Leading',
  'Lead',
  'Leads',
  'Leadingly',
  '32',
  'Failing',
  'Failure',
  'Fails',
  'Failingly',
  '33',
  'Remembered',
  'Memory',
  'Remembers',
  'Privately',
  '34',
  'Powerful',
  'Power',
  'Powers',
  'Powerfully',
  '35',
  'Progressive',
  'Change',
  'Changes',
  'Progressively',
  '36',
  'Endarkened',
  'Feeling',
  'Feels',
  'Fully',
  '37',
  'Friendful',
  'Friend',
  'Befriends',
  'Friendly',
  '38',
  'Fighting',
  'Fighter',
  'Fights',
  'Oppositely',
  '39',
  'Provocative',
  'Provocation',
  'Provokes',
  'Provocatively',
  '40',
  'Loyal',
  'Worker',
  'Works',
  'Loyally',
  '41',
  'Fanciful',
  'Fantasy',
  'Fantasises',
  'Fancifully',
  '42',
  'Ending',
  'End',
  'Ends',
  'Happily Ever After',
  '43',
  'Insightful',
  'Insight',
  'Insights',
  'Insightfully',
  '44',
  'Alertful',
  'Alert',
  'Alerts',
  'Alertly',
  '45',
  'Bossy',
  'Boss',
  'Bosses',
  'Boastfully',
  '46',
  'Determined',
  'Determination',
  'Determines',
  'Determinately',
  '47',
  'Oppressed',
  'Oppression',
  'Oppresses',
  'Oppressively',
  '48',
  'Deep',
  'Depth',
  'Deepens',
  'Deeply',
  '49',
  'Revolutionary',
  'Revolution',
  'Revolutionizes',
  'Revolutionarily',
  '50',
  'Valuable',
  'Value',
  'Values',
  'Valuably',
  '51',
  'Shocking',
  'Shock',
  'Shocks',
  'Shockingly',
  '52',
  'Mounted',
  'Mountain',
  'Mounts',
  'Mountfully',
  '53',
  'First',
  'Beginning',
  'Begins',
  'At the Beginning',
  '54',
  'Ambitious',
  'Ambition',
  'Drives',
  'Ambitiously',
  '55',
  'Spirited',
  'Spirit',
  'Spirits',
  'Spiritually',
  '56',
  'Believed',
  'Believer',
  'Believes',
  'Wonderingly',
  '57',
  'Gentle',
  'GentleWind',
  'Blows',
  'Gently',
  '58',
  'Joyous',
  'Joy',
  'Enjoys',
  'Joyously',
  '59',
  'Sexual',
  'Sex',
  'Disperses',
  'Sexually',
  '60',
  'Limited',
  'Limitation',
  'Limits',
  'Limitedly',
  '61',
  'Truthful',
  'Truth',
  'Truths',
  'Truthfully',
  '62',
  'Detailed',
  'Detail',
  'Details',
  'Detailedly',
  '63',
  'Doubting',
  'Doubt',
  'Doubts',
  'Doubtfully',
  '64',
  'Confusing',
  'Confusion',
  'Confuses',
  'Confusingly',
];

final List<String> hexagramAdjectiveList = [
  'Zero',
  'Creative',
  'Responsive',
  'Different',
  'Chaotic',
  'Patient',
  'Conflicting',
  'Interactive',
  'Contributing',
  'Focused',
  'Selfing',
  'Ideal',
  'Cautious',
  'Secret',
  'Wealthy',
  'Extreme',
  'Skillful',
  'Hierarchical',
  'Corrective',
  'Needful',
  'Attentive',
  'Controlled',
  'Graceful',
  'Assimilated',
  'Rationalised',
  'Innocent',
  'Tricky',
  'Caring',
  'Risky',
  'Persevered',
  'Fiery',
  'Leading',
  'Failing',
  'Remembered',
  'Powerful',
  'Progressive',
  'Endarkened',
  'Friendful',
  'Fighting',
  'Provocative',
  'Loyal',
  'Fanciful',
  'Ending',
  'Insightful',
  'Alertful',
  'Bossy',
  'Determined',
  'Oppressed',
  'Deep',
  'Revolutionary',
  'Valuable',
  'Shocking',
  'Mounted',
  'First',
  'Ambitious',
  'Spirited',
  'Believed',
  'Gentle',
  'Joyous',
  'Sexual',
  'Limited',
  'Truthful',
  'Detailed',
  'Doubting',
  'Confusing',
];

final List<String> hexagramSubjectList = [
  'Zero',
  'Creativity',
  'Response',
  'Mutation',
  'Answer',
  'Patience',
  'Conflict',
  'Interaction',
  'Contribution',
  'Focus',
  'Self',
  'Idea',
  'Caution',
  'Secret',
  'Wealth',
  'Extreme',
  'Skill',
  'Hierarchy',
  'Correction',
  'Need',
  'Attention',
  'Control',
  'Grace',
  'Assimilation',
  'Rationalisation',
  'Innocence',
  'Trickster',
  'Care',
  'Risk',
  'Perseverance',
  'Fire',
  'Lead',
  'Failure',
  'Memory',
  'Power',
  'Change',
  'Feeling',
  'Friend',
  'Fighter',
  'Provocation',
  'Worker',
  'Fantasy',
  'End',
  'Insight',
  'Alert',
  'Boss',
  'Determination',
  'Oppression',
  'Depth',
  'Revolution',
  'Value',
  'Shock',
  'Mountain',
  'Beginning',
  'Ambition',
  'Spirit',
  'Believer',
  'GentleWind',
  'Joy',
  'Sexuality',
  'Limitation',
  'Truth',
  'Detail',
  'Doubt',
  'Confusion',
];

final List<String> hexagramVerbList = [
  'Zero',
  'Creates',
  'Responds',
  'Mutates',
  'Answers',
  'Waits',
  'Conflicts',
  'Interacts',
  'Contributes',
  'Focuses',
  'Selfs',
  'Ideas',
  'Cautions',
  'Hides',
  'Enriches',
  'Extremes',
  'Identifies',
  'Organizes',
  'Corrects',
  'Needs',
  'Attends',
  'Controls',
  'Graces',
  'Assimilates',
  'Rationalises',
  'Innocences',
  'Tricks',
  'Cares',
  'Risks',
  'Perseveres',
  'Fires',
  'Leads',
  'Fails',
  'Remembers',
  'Powers',
  'Changes',
  'Feels',
  'Befriends',
  'Fights',
  'Provokes',
  'Works',
  'Fantasises',
  'Ends',
  'Insights',
  'Alerts',
  'Bosses',
  'Determines',
  'Oppresses',
  'Deepens',
  'Revolutionizes',
  'Values',
  'Shocks',
  'Mounts',
  'Begins',
  'Drives',
  'Spirits',
  'Believes',
  'Blows',
  'Enjoys',
  'Disperses',
  'Limits',
  'Truths',
  'Details',
  'Doubts',
  'Confuses',
];

final List<String> hexagramVerbNewList = [
  'Zero',
  'Creates',
  'Responds',
  'Mutates',
  'will Answer',
  'will Wait',
  'Conflicts',
  'will Interact',
  'Contributes',
  'will Focus',
  'Selfs',
  'Idead',
  'Cautions',
  'Hid',
  'Enriches',
  'will Extreme',
  'will Identify',
  'will Organize',
  'will Correct',
  'Needs',
  'Attends',
  'Controls',
  'Graces',
  'Assimilates',
  'Rationalises',
  'Innocences',
  'Tricks',
  'Cares',
  'Risks',
  'Persevered',
  'Fired',
  'will Lead',
  'Fails',
  'Remembered',
  'Powers',
  'Changed',
  'Felt',
  'Befriends',
  'Fights',
  'Provokes',
  'Works',
  'Fantasised',
  'Ended',
  'Insights',
  'Alerts',
  'Bosses',
  'Determined',
  'Oppressed',
  'will Deepen',
  'Revolutionizes',
  'Values',
  'Shocks',
  'will Mount',
  'Began',
  'Drives',
  'Spirits',
  'Believed',
  'Blows',
  'will Enjoy',
  'Disperses',
  'Limits',
  'Truths',
  'will Detail',
  'will Doubt',
  'Confused',
];

final List<String> hexagramAdverbList = [
  'Zero',
  'Creatively',
  'Responsively',
  'Differently',
  'Chaotically',
  'Patiently',
  'Conflictingly',
  'Interactively',
  'Uniquely',
  'Focusingly',
  'Selfingly',
  'Ideally',
  'Cautiously',
  'Secretly',
  'Wealthfully',
  'Extremely',
  'Skillfully',
  'Hierarchically',
  'Correctly',
  'Needfully',
  'Attentively',
  'Controllably',
  'Gracefully',
  'Assimilably',
  'Rationally',
  'Innocently',
  'Trickily',
  'Carefully',
  'Riskily',
  'Perseveringly',
  'Fiercely',
  'Leadingly',
  'Failingly',
  'Privately',
  'Powerfully',
  'Progressively',
  'Fully',
  'Friendly',
  'Oppositely',
  'Provocatively',
  'Loyally',
  'Fancifully',
  'Happily Ever After',
  'Insightfully',
  'Alertly',
  'Boastfully',
  'Determinately',
  'Oppressively',
  'Deeply',
  'Revolutionarily',
  'Valuably',
  'Shockingly',
  'Mountfully',
  'At the Beginning',
  'Ambitiously',
  'Spiritually',
  'Wonderingly',
  'Gently',
  'Joyously',
  'Sexually',
  'Limitedly',
  'Truthfully',
  'Detailedly',
  'Doubtfully',
  'Confusingly',
];

final List<int> hexCarouselValueList = [
//'1','43'...,
  111,
  211,
  311,
  411,
  121,
  221,
  321,
  421,
  131,
  231,
  331,
  431,
  141,
  241,
  341,
  441,
  112,
  212,
  312,
  412,
  122,
  222,
  322,
  422,
  132,
  232,
  332,
  432,
  142,
  242,
  342,
  442,
  113,
  213,
  313,
  413,
  123,
  223,
  323,
  423,
  133,
  233,
  333,
  433,
  143,
  243,
  343,
  443,
  114,
  214,
  314,
  414,
  124,
  224,
  324,
  424,
  134,
  234,
  334,
  434,
  144,
  244,
  344,
  444,
];

final List<int> hexCarouselWheelOrderList = [
//'1','43'...,
  111,
  211,
  311,
  411,
  121,
  221,
  321,
  421,
  131,
  231,
  331,
  431,
  141,
  241,
  341,
  441,

  112,
  212,
  312,
  412,
  122,
  222,
  322,
  422,
  132,
  232,
  332,
  432,
  142,
  242,
  342,
  442,

  444,
  344,
  244,
  144,
  434,
  334,
  234,
  134,
  424,
  324,
  224,
  124,
  414,
  314,
  214,
  114,

  443,
  343,
  243,
  143,
  433,
  333,
  233,
  133,
  423,
  323,
  223,
  123,
  413,
  313,
  213,
  113,
];

/// FULL SENTENCE

final List<String> rtimgcoins = [
  'assets/planets/sun.png',
  'assets/coins/complex.png',
  'assets/minmax/bluemax.png',

  'assets/planets/northnode.png',
  'assets/coins/simple.png',
  'assets/minmax/greenmax.png',

  'assets/planets/southnode.png',
  'assets/coins/breath.png',
  'assets/minmax/yellowmin.png',

  'assets/planets/earth.png',
  'assets/coins/silence.png',
  'assets/minmax/redmin.png',
];

final List<String> rtimgcoinsold = [
  'assets/planets/sun.png',
  'assets/coins/complex.png',
  'assets/plants/mrbluep.png',
  'assets/plants/rotegi.png',

  'assets/planets/northnode.png',
  'assets/coins/simple.png',
  'assets/plants/mrgreavo.png',
  'assets/plants/rotav.png',

  'assets/planets/southnode.png',
  'assets/coins/breath.png',
  'assets/plants/msyelban.png',
  'assets/plants/rotban.png',

  'assets/planets/earth.png',
  'assets/coins/silence.png',
  'assets/plants/msredtom.png',
  'assets/plants/rotom.png',
];

final List<String> hexBasicList = [
  'assets/coins/complex.png',
  'assets/coins/simple.png',
  'assets/coins/breath.png',
  'assets/coins/silence.png',
];

final List<String> hexBasicMixList = [
  'assets/coins/complex.png',
  'assets/coins/simple.png',
  'assets/coins/breath.png',
  'assets/coins/silence.png',
];

final List<String> basicKitheList = [
  'assets/kithe/blkithe.png',
  'assets/kithe/grkithe.png',
  'assets/kithe/yelkithe.png',
  'assets/kithe/redkithe.png',
];

final List<String> basicPlantsList = [
  'assets/plants/mrbluep.png',
  'assets/plants/mrgreavo.png',
  'assets/plants/rotban.png',
  'assets/plants/rotom.png',
];

final List<String> PlantsRoutes = [
  '/rotatecomplex',
  '/rotatesimple',
  '/rotatebreath',
  '/rotatesilence',
];

final List<String> titlesicon = [
  'assets/coins/fullcoins.png',
  'assets/coins/silence.png',
  'assets/coins/breath.png',
  'assets/coins/simple.png',
  'assets/coins/complex.png',
];

final List<String> titlesname_heb = [
  'א.ל.י.מ',
  'שתיקה',
  'נשימה',
  'פשוט',
  'מורכב',
];

final List<String> bimnamesheb = [
  'גמלכלב',
  'בטי',
  'ביני',
  'אבי',
  'חזי',
];

final List<String> woofgoofHebname = [
  '?גופוף',
  'גוף',
  'גוף ווף',
  'ווף',
  'ניגוף',
];

final List<String> minmaxmainHebname = [
  '?מקיא שאלה',
  'מינימום',
  'מיני',
  'מיקי',
  'מקסימום',
];

final List<String> kithename = [
  'Kit He Camel?',
  'Bet Kit He',
  'Been Kit He',
  'Have Kit He',
  'Has Kit He',
];

final List<String> titlesname = [
  'i.d.k.m',
  'silence',
  'Breath',
  'Simple',
  'COMPLEX',
];

final List<String> mplants = [
  'assets/plants/mrcamog.png',
  'assets/plants/rotom.png',
  'assets/plants/rotban.png',
  'assets/plants/mrgreavo.png',
  'assets/plants/mrbluep.png',
];

final List<String> maincoins = [
  //'assets/kithe/quekithe.png',
  'assets/kithe/qkithe.gif',
  'assets/kithe/redkithe.png',
  'assets/kithe/yelkithe.png',
  'assets/kithe/grkithe.png',
  'assets/kithe/blkithe.png',
];

final List<String> mplantsfull = [
  'assets/plants/rotom.png',
  'assets/plants/rotban.png',
  'assets/plants/rotav.png',
  'assets/plants/rotegi.png',
  'assets/plants/msredtom.png',
  'assets/plants/msyelban.png',
  'assets/plants/mrgreavo.png',
  'assets/plants/mrbluep.png',
];

final List<String> mcameldog = [
  'assets/camog/mcamog.png',
  'assets/camog/mcamel.png',
  'assets/camog/mcdog.png',
  'assets/camog/mccamelyellow.png',
];

final List<String> pdftitle = [
  'מילים',
  'מאייטי אל גורוגי ומטאגי',
  'from IT to Guru G and Mata G',
  'בחיפוש אחר גוגל',
  'In Search Of Google',
];

final List<double> titlesangle = [
  //'/rotatesidk',
  -80,
  //'/rotatesilence',
  20,
  //'/rotatebreath',
  120,
  //'/rotatesimple',
  180,
  //'/rotatecomplex',
  220,
];

final List<String> mainroutes = [
  '/rotatesidk',
  '/rotatesilence',
  '/rotatebreath',
  '/rotatesimple',
  '/rotatecomplex',
  //'/rotatecomplexhd',
];

final List<String> subroutes = [
  '/rotatecomplexhd',
];

final List<String> pdfroutes = [
  '/rotatepdf',
  '/rotatefitgamhe',
  '/rotatefitgam',
  '/rotateisoghe',
  '/rotateisog',
];

final List<String> subtitles = [
  'I Don\'t Know',
  'silence',
  'breath',
  'Simple',
  'Complex',
];

final List<String> subtitles_heb = [
  'אני לא יודעת',
  'שתיקה',
  'נשימה',
  'פשוט',
  'מורכב',
];

final List<String> hebsub_rev = [
  'בלכלמג',
  'יטב',
  'יניב',
  'מהרבא',
  'לאקזחי',
];

final List<String> maintxt = [
  'IDK KIT He!',
  'Bet KIT She!',
  'Been KIT She!',
  'Have KIT He!',
  'Has KIT He!',
];

final List<String> hebsub_rev_old = [
  'תעדוי אל ינא',
  'הקיתש',
  'המישנ',
  'טושפ',
  'בכרומ',
];

final List<String> subtitles_old = [
  'Complex',
  'Simple',
  'breath',
  'silence',
  'I don\'t know',
];


final List<String> hexNamesList = [
  'מורכב',
  'פשוט',
  'נשימה',
  'שתיקה',
];

final List<String> hexNamesEngList = [
  'COMPLEX',
  'Simple',
  'Breath',
  'silence',
];

final List<String> hexNamesHebList = [
  'מורכב',
  'פשוט',
  'נשימה',
  'שתיקה',
];

final List<String> bimboxlist = [
  'חזי בימשו',
  'אבי בים',
  'ביני',
  'בטי',
];

final List<String> newCoinNames = [
  'לזנוח',
  'לחשוב',
  'להשתמש',
  'לבנות',
];

final List<String> newCoinNames_old = [
  'NEGLECT',
  'Think',
  'Use',
  'build',
];

final List<String> timecoins = [
  'seconds',
  'minutes',
  'hours',
  'days',
  'weeks',
  'months',
  'years',
];

final List<String> timecoinsheb = [
  'שניות',
  'דקות',
  'שעות',
  'ימים',
  'שבועות',
  'חודשים',
  'שנים',
];

// variables
List<int> hexagramslist = List<int>.generate(65, (counter) => counter++);

var hexagramslistfinal = hexagramslist.getRange(1, hexagramslist.length);

// SLIDERS

final List<Widget> planetsFullSliders = planetsfullList
    .map((planet) => Container(
          margin: const EdgeInsets.all(5.0),
          child: ClipRRect(
              borderRadius: const BorderRadius.all(Radius.circular(5.0)),
              child: Stack(
                children: <Widget>[
                  Image.asset(planet, fit: BoxFit.cover, width: 100.0),
                ],
              )),
        ))
    .toList();

final List<Widget> planetsCrossSliders = planetsCrossList
    .map((planet) => Container(
          margin: const EdgeInsets.all(5.0),
          child: ClipRRect(
              borderRadius: const BorderRadius.all(Radius.circular(5.0)),
              child: Stack(
                children: <Widget>[
                  Image.asset(planet, fit: BoxFit.cover, width: 100.0),
                ],
              )),
        ))
    .toList();

final List<Widget> mixHexagramSliders = hexBasicMixList
    .map((item) => Container(
          margin: const EdgeInsets.all(5.0),
          child: ClipRRect(
              borderRadius: const BorderRadius.all(Radius.circular(5.0)),
              child: Stack(
                children: <Widget>[
                  Image.asset(item, fit: BoxFit.cover, width: 500.0),
                ],
              )),
        ))
    .toList();

final List<Widget> mixHexagramSlidersNew = hexBasicMixList
    .map((hexagrambasicmix) => CircleAvatar(
        minRadius: 100.0,
        maxRadius: 100.0,
        backgroundImage: AssetImage(hexagrambasicmix)))
    .toList();

final List<Widget> miximageslider = rtimages
    .map(
      (rtimagesmix) => Container(
        height: 200,
        width: 200,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage(rtimagesmix),
            fit: BoxFit.scaleDown,
          ),
          shape: BoxShape.rectangle,
        ),
      ),
    )
    .toList();

final List<Widget> mixKitheSliders = basicKitheList
    .map(
      (kithemix) => Container(
        height: 200,
        width: 200,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage(kithemix),
            fit: BoxFit.scaleDown,
          ),
          shape: BoxShape.rectangle,
        ),
      ),
    )
    .toList();

final List<Widget> mixPlantsSliders = basicPlantsList
    .map(
      (plantsmix) => Container(
        height: 200,
        width: 200,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage(plantsmix),
            fit: BoxFit.scaleDown,
          ),
          shape: BoxShape.rectangle,
        ),
      ),
    )
    .toList();

final List<Widget> mixHexagramSlidersBol = [
  hexBasicMixList.first,
  hexBasicMixList.last
]
    .map((hexagrambasicmix) => CircleAvatar(
        minRadius: 100.0,
        maxRadius: 100.0,
        backgroundImage: AssetImage(hexagrambasicmix)))
    .toList();

// DROPDOWN

final List<DropdownMenuItem<int>> hexDropDownNumbersList =
    hexagramslistfinal.map((int hexagramsnew) {
  return DropdownMenuItem(
    value: hexagramsnew,
    child: Text(
      hexagramsnew.toString(),
      style: const TextStyle(
        fontSize: 15,
        color: Colors.black,
      ),
    ),
  );
}).toList();

final List<DropdownMenuItem<String>> fontHexList =
    fontHexOrderList.map((String chosenHexagrams) {
  return DropdownMenuItem(
    value: chosenHexagrams,
    child: Text(chosenHexagrams,
        style: const TextStyle(
          color: Colors.black,
          fontSize: 20.0,
          fontFamily: 'iChing',
        )),
  );
}).toList();

final List<DropdownMenuItem<int>> orderHexagramsWheelList =
    orderHexagramsWheel.map((int orderWheelHexagrams) {
  return DropdownMenuItem(
      value: orderWheelHexagrams,
      child: Text(orderWheelHexagrams.toString(),
          style: const TextStyle(
            fontSize: 15,
            color: Colors.black,
          )));
}).toList();

final List<DropdownMenuItem<String>> iChingFontList =
    fontHexOrderList.map((String fontHexagrams) {
  return DropdownMenuItem(
    value: fontHexagrams,
    child: Text(fontHexagrams,
        style: const TextStyle(
          color: Colors.black,
          fontSize: 30.0,
          fontFamily: 'iChing',
        )),
  );
}).toList();

final List<DropdownMenuItem<String>> timecoinsDropDownLst =
timecoinsheb.map((String newtimecoin) {
  return DropdownMenuItem(
    value: newtimecoin,
    child: Text(newtimecoin,
        style: const TextStyle(
          color: Colors.black,
          fontSize: 15.0
        )),
  );
}).toList();

// map

final fontHexagramsMap = fontHexOrderList.asMap();
final fontHexagramsWheelMap = fontHexNumbersList.asMap();

// gene keys spectrum of consciousness
final List spectrumOfWords = [
  0,
  'shadow',
  'gift',
  'siddhi',
  1,
  'entropy',
  'freshness',
  'beauty',
  2,
  'dislocation',
  'orientation',
  'unity',
  3,
  'chaos',
  'innovation',
  'innocence',
  4,
  'intolerance',
  'understanding',
  'forgiveness',
  5,
  'impatience',
  'patience',
  'timelessness',
  6,
  'conflict',
  'diplomacy',
  'peace',
  7,
  'division',
  'guidance',
  'virtue',
  8,
  'mediocracy',
  'style',
  'exquisiteness',
  9,
  'inertia',
  'determination',
  'invincibility',
  10,
  'self-obsession',
  'naturalness',
  'being',
  11,
  'obscurity',
  'idealism',
  'light',
  12,
  'vanity',
  'discrimination',
  'purity',
  13,
  'discord',
  'discernment',
  'empathy',
  14,
  'compromise',
  'competence',
  'bounteousness',
  15,
  'dullness',
  'magnetism',
  'florescence',
  16,
  'indifference',
  'versatility',
  'mastery',
  17,
  'opinion',
  'far-sightedness',
  'omniscience',
  18,
  'judgement',
  'integrity',
  'perfrection',
  19,
  'co-dependence',
  'sensitivity',
  'sacrifice',
  20,
  'superficiality',
  'self assurance',
  'presence',
  21,
  'control',
  'authority',
  'valour',
  22,
  'dishonour',
  'graciousness',
  'grace',
  23,
  'complexity',
  'simplicity',
  'quintessence',
  24,
  'addiction',
  'invention',
  'silence',
  25,
  'constriction',
  'acceptance',
  'universal love',
  26,
  'pride',
  'artfulness',
  'invisbility',
  27,
  'selfishness',
  'altruism',
  'selflessness',
  28,
  'purposelessness',
  'totality',
  'immorality',
  29,
  'half-heartedness',
  'commitment',
  'devotion',
  30,
  'desire',
  'lightness',
  'rapture',
  31,
  'arrogance',
  'leadership',
  'humility',
  32,
  'failure',
  'preservation',
  'veneration',
  33,
  'forgetting',
  'mindfullness',
  'revelation',
  34,
  'force',
  'strength',
  'majesty',
  35,
  'hunger',
  'adventure',
  'boundlessness',
  36,
  'turbulence',
  'humanity',
  'compassion',
  37,
  'weakness',
  'equality',
  'tenderness',
  38,
  'struggle',
  'perseverance',
  'honour',
  39,
  'provocation',
  'dynamism',
  'liberation',
  40,
  'exhaustion',
  'resolve',
  'divine will',
  41,
  'fantasy',
  'anticipation',
  'emanation',
  42,
  'expectation',
  'detachment',
  'celebration',
  43,
  'deafness',
  'insight',
  'epiphany',
  44,
  'interference',
  'teamwork',
  'synarchy',
  45,
  'dominance',
  'synergy',
  'communion',
  46,
  'seriousness',
  'delight',
  'ecstasy',
  47,
  'oppression',
  'transmutation',
  'transfiguration',
  48,
  'inadequacy',
  'resourcefulness',
  'wisdom',
  49,
  'reaction',
  'revolution',
  'rebirth',
  50,
  'corruption',
  'equilibrium',
  'harmony',
  51,
  'agitation',
  'initiative',
  'awakening',
  52,
  'stress',
  'restraint',
  'stillness',
  53,
  'immaturity',
  'expansion',
  'superabundance',
  54,
  'greed',
  'aspiration',
  'ascension',
  55,
  'victimisation',
  'freedom',
  'FREEDOM',
  56,
  'distraction',
  'enrichment',
  'intoxication',
  57,
  'unease',
  'intuition',
  'clarity',
  58,
  'dissatisfaction',
  'vitality',
  'bliss',
  59,
  'dishonesty',
  'intimacy',
  'transparency',
  60,
  'limitation',
  'realism',
  'justice',
  61,
  'psychosis',
  'inspiration',
  'sanctity',
  62,
  'intellect',
  'precision',
  'impeccability',
  63,
  'doubt',
  'inquiry',
  'truth',
  64,
  'confusion',
  'imagination',
  'illumination',
];